### ISSUE TITLE
go:latest uses 1.15 instead of the newer 1.21 images which are present

### ISSUE THREAD

**Issue by dcatwoohoo** [GoogleCloudPlatform/cloud-builders#1000]
## Affected builder image

gcr.io/cloud-builders/go:latest

## Expected Behavior

latest applies to latest (1.21 at this time)

## Actual Behavior

latest tag applies to 1.15

## Steps to Reproduce the Problem

Use gcr.io/cloud-builders/go on any application that requires 1.16+
Watch it fail.

## Additional Info
I am wondering if this is by accident or by design.

**Comment by haroonc** [comment]
Thanks @dcatwoohoo for the report. 
Unfortunately updating the `latest` tag to the current go version introduces breaking change for some users. Therefore we will not be able to update the `latest` tag

**Comment by dcatwoohoo** [comment]
I can appreciate this but at some point though you need to rectify that you're using an EOS golang build, right?

Go 1.12, 1.13, 1.14, 1.15, 1.16, and 1.18 have reached [end of support](https://cloud.google.com/appengine/docs/standard/lifecycle/runtime-lifecycle#end_of_support) on January 30, 2024
