### ISSUE TITLE
Permission error when using gcloud container images describe

### ISSUE THREAD

**Issue by dminkovsky** [GoogleCloudPlatform/cloud-builders#101]
I am trying to inspect an image and am getting an error:

    $ gcloud container images describe gcr.io/my-project/my-image:latest

> ERROR: (gcloud.container.images.describe) You do not have permission to access project [my-project] (or it may not exist): permission "containeranalysis.occurrences.list" denied for project "my-project": Service 'containeranalysis.googleapis.com' is not enabled for consumer 'project_number:12345'.

All other gcloud commands work. I am using an owner account, or so I think.

**Comment by ImJasonH** [comment]
This is related to an private alpha service that we haven't launched publicly yet. Sorry for the confusion, but stay tuned! :)

**Comment by dminkovsky** [comment]
Cool, thank you.

Any thoughts on how to get `docker images`-like output for the registry: sorted by time, containing image IDs?

Closest I am seeing now is `gcloud container images list-tags`, but that only shows digests and not tags, and is for a particular image.

**Comment by ImJasonH** [comment]
I've filed an internal feature request for this on the GCR team.
