### ISSUE TITLE
[BUG] curl no longer available in gcr.io/cloud-builders/gcloud

### ISSUE THREAD

**Issue by henkish** [GoogleCloudPlatform/cloud-builders#1014]
## Notice

We use `gcr.io/cloud-builders/gcloud` to build and deploy endpoints-runtime-serverless - and one step of the build script is to download service configuration using curl. Since some days ago, this stopped working. Possibly due to switch of base ubuntu image?

## Affected builder image

gcr.io/cloud-builders/gcloud

## Expected Behavior

Running curl command should work

## Actual Behavior

curl: command not found

**Comment by RyanBrutonCAT** [comment]
Also seeing the same behaviour this morning, affecting a number of our cloudbuild pipelines where we use curl to run a healtcheck

**Comment by andreasbrgmn** [comment]
We got hit with this morning as well. I can see it's not part of the new base image `gcr.io/cloud-marketplace/google/ubuntu2204` [change](https://github.com/GoogleCloudPlatform/cloud-builders/commit/6952e4d81384f0ea24554b309720ee3a786c0752#diff-d8bd04822cdfc67dd9f05521b87b74bb060bbd329d407b0d73d2f1aa007aca41R1). If this was unintentional it'd be great to have it back in. I think we noticed `gsutil` also went missing?

**Comment by mtohmaz** [comment]
We're also seeing this issue. Any potential workarounds?

**Comment by RyanBrutonCAT** [comment]
> We're also seeing this issue. Any potential workarounds?

We've switched the following image which has resolved this for us whilst this issue is open`gcr.io/google.com/cloudsdktool/cloud-sdk:493.0.0-slim`

**Comment by ollosh** [comment]
Works again. Reverted in here https://github.com/GoogleCloudPlatform/cloud-builders/pull/1015

**Comment by liggitt** [comment]
thanks, the updated git builder image resolved the issue on our side

**Comment by haroonc** [comment]
Changes to `gcr.io/cloud-builders/gcloud-slim` are rolled back. I am closing this issue for now, please re-open if you are still experiencing any issues related to this change.
