### ISSUE TITLE
HTTPError 403: Insufficient Permission from "gcloud container builds" in Jenkins

### ISSUE THREAD

**Issue by gylu** [GoogleCloudPlatform/cloud-builders#104]
Running either of the following two commands in a Jenkinsfile executed on a Jenkins slave node running on Kubernetes (GKE) results in Insufficient Permission error.

```
gcloud container builds submit -t gcr.io/<project>/gceme:development.1 .
gcloud container builds submit --config=cloudbuild.yaml .
```

Results in:
```
ERROR: (gcloud.container.builds.submit) HTTPError 403: Insufficient Permission
```

The Jenkins slave docker image I'm using is: gcr.io/cloud-solutions-images/jenkins-k8s-slave

Running ```gcloud info``` on that Jenkins slave pod shows that I am using gcloud as the service account, which has EDITOR permissions on the project IAM.

**Comment by bendory** [comment]
If the credentials account used to initiate the `gcloud container builds submit` has Editor access to the resource project, the build should be created successfully. If that is not the case and you would like our help debugging further, please e-mail gcr-support@google.com including:

- the output from `gcloud config list`
- the exact command line you are running
- the full output of the command, including both stdout and stderr

I am closing this Issue as we can't debug a user problem here when it requires sharing personally identifiable information like the above.
