### ISSUE TITLE
How to pass environment variables or output between build steps especially standard ones.

### ISSUE THREAD

**Issue by richtera** [GoogleCloudPlatform/cloud-builders#11]
Not quite sure if this is the correct repo to post this.

But when calling any of these or custom build steps how can I pass either STDOUT or some environment variable to the next build step or to the images array. We are calculating the version tag to use for a build within a bash script but I am not sure how to get it into the images property of the build file for example.

I guess other variables I could do "printenv > somewhere.sh" and then execute ". somewhere.sh" in the next task. If the task is on of the standard ones here ("cp", "npm" or "docker") then things become more complicated.

Although it would be possible to write a new entrypoint, pull in the variables and then run the original entrypoint script. Since most of the entrypoints in these commands are not resolved through a path but by full path it seems things would become a bit fragile.

**Comment by bendory** [comment]
Hi @richtera,

The [Build Steps documentation](https://cloud.google.com/container-builder/docs/api/build-steps) describes one way to do this:

> If you specify more than one build step, the assets produced by one step can be passed to the next one via the persistence of the /workspace directory. This allows you to set up a pipeline of build steps that result in the final built asset(s).

Are you calculating the version tag within a build step or do you know it prior to the build? If you know it prior to the build, you can make a static build template that uses a user-defined substitution variable and then pass the value for the substitution at execution time. This is described in the [substitutions section of the Build Requests documentation](https://cloud.google.com/container-builder/docs/api/build-requests#substitutions).

Does that answer your question?

Note: you can also contact the Container Builder team via gcr-contact@google.com.

David

**Comment by richtera** [comment]
I changed the version to be precalculated and then used gcloud beta add-tag to add other docker tags within a shell script. Not ideal but works for sure.
