### ISSUE TITLE
[Request] Clojure Build Tools

### ISSUE THREAD

**Issue by flyboarder** [GoogleCloudPlatform/cloud-builders#113]
Request to add boot and lein clojure build tools.

**Comment by christophersanson** [comment]
Hi, thanks for the request. We're working to create a process for users to contribute new builder images directly. Will update this thread when we have more to share. Thanks.

**Comment by ImJasonH** [comment]
Until such a process exists, you can build your own builder and link it here and we'll be happy to review it.
