### ISSUE TITLE
Private external registry with certificat

### ISSUE THREAD

**Issue by cedrelek** [GoogleCloudPlatform/cloud-builders#117]
Hi,
During my project build I would like to push a docker image to a private docker registry.
So i got an image tag like : `team1.priv-registry.io/$PROJECT_ID/audit-service`
As the `gcr.io/cloud-builders/docker` run docker in a docker, when I copy the CA certificat of `team1.priv-registry.io`  in the directory `/etc/docker/certs.d/team1.priv-registry.io`. I still get an error : `x509: certificate signed by unknown authority`

This is because the docker deamon run in the host and I can add what I want in the /ect/docker/certs.d in the container, the deamon will never see these changes. Do you have any suggestion about this issue ?

**Comment by ImJasonH** [comment]
Hi, unfortunately I don't know of a good way to support this case today, since the Docker daemon's configuration is not accessible during the scope of your build.

Sorry that's not very helpful, we haven't had many requests to support this.
