### ISSUE TITLE
caching between builds

### ISSUE THREAD

**Issue by Fabian-K** [GoogleCloudPlatform/cloud-builders#118]
Hi,

I have a build setup which downloads dependencies from a maven repository, from npm and using bower. Are there plans to add a caching possibility between build e.g. for directories like node_modules, bower_components or a local maven repository? Bitbucket Pipelines e.g. has support for such a feature (https://confluence.atlassian.com/bitbucket/caching-dependencies-895552876.html)

Thanks,
Fabian

**Comment by bendory** [comment]
Hi Fabian,

Thank you for your feature request. We've had discussions about first-class support for this sort of functionality, but nothing in the works just yet.

In the interim, you can use the [gcr.io/cloud-builders/gsutil](gcr.io/cloud-builders/gsutil) cloud-builder as a workaround by copying artifacts to / from a GCS bucket (or other location) as needed.

**Comment by Fabian-K** [comment]
Thanks for the hint with the interim solution. Are the builds always executed in the same region? If so it might make sense to place the GCS bucket in the same region :)

**Comment by ImJasonH** [comment]
As of today, all builds are executed in the US multi-region, so using a GCS bucket in US would probably be moderately better.
