### ISSUE TITLE
Missing permissions on cloud container builder role 

### ISSUE THREAD

**Issue by stevenbarragan** [GoogleCloudPlatform/cloud-builders#120]
I created a service account to build my images, I assigned it the "cloud container builder" role, it builds the image fine, but then it "fails" reading the logs.

```
ERROR: (gcloud.container.builds.submit) HTTPError 403: <?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>circleci@project.iam.gserviceaccount.com does not have storage.objects.get access to 45129378560.cloudbuild-logs.googleusercontent.com/log-afb39b5-fb91-4069-b145-4fdd2321bdd.txt.</Details></Error>
```

Am I missing something?

**Comment by bendory** [comment]
I assume that when you say:
> I created a service account to build my images

you mean that you created a service account that you are using to submit builds? If so, this service account needs the [Cloud Container Builder Editor role](https://cloud.google.com/container-builder/docs/how-to/access-control#roles).

If that does not answer your question, please clarify for me...

**Comment by stevenbarragan** [comment]
Yes, I created a service account and I assigned the "Cloud Container Builder Editor" role to it,  and I'm still getting the same error when I try to submit.

The image gets created fine, but it fails on getting the logs.

**Comment by bendory** [comment]
GCS permissions predate IAM and thus work a little differently. To view the logs, the Service Account in question needs to be a Viewer on the project in addition to have the Builder Editor role.

**Comment by ofpiyush** [comment]
@bendory `Viewer` permission is too broad. For example it grants read access to all buckets. 

This is highly undesirable if you have any deployment strategy that stores secrets in these buckets.

Is there a permission that I can specifically grant to someone to enable them to see just the logs?

**Comment by ImJasonH** [comment]
If you'd like, you can set the `logsBucket` field on the `Build` resource to specify a custom location for your logs in GCS, and grant whatever permissions you want to those logs. At that point you can explicitly add your service account as a reader (or writer, or owner) of that bucket.

Note that the builder service account (`PROJECT_NUM@cloudbuild.gserviceaccount.com`) must have write access to that bucket.

**Comment by ofpiyush** [comment]
Is there a way to configure that for [build triggers](https://console.cloud.google.com/gcr/triggers)?

Much appreciated!

**Comment by ImJasonH** [comment]
@ofpiyush Yes, but you'll need to use the API to do so. Either create a trigger in the UI and [update it using the API](https://cloud.google.com/container-builder/docs/api/reference/rest/v1/projects.triggers/patch), or just [create the trigger using the API](https://cloud.google.com/container-builder/docs/api/reference/rest/v1/projects.triggers/create) in the first place.

**Comment by hiroshi** [comment]
> -> You need to specify a subdir, e.g `gs://my-log-bucket/foo`

Hey, Please update document ;-)
https://cloud.google.com/cloud-build/docs/build-config#logsbucket
<a href="https://gyazo.com/803fd1e22923f871118729a2bd8a4fe9"><img src="https://i.gyazo.com/803fd1e22923f871118729a2bd8a4fe9.png" alt="Image from Gyazo" width="846"/></a>

**Comment by dwdraju** [comment]
Quick way:

```
gsutil mb gs://[BUCKET-NAME]/
gsutil iam ch serviceAccount:[SERVICE-ACCOUNT-ID]:objectCreator gs://[BUCKET-NAME]
```

```yaml
steps:
- name: gcr.io/cloud-builders/docker
  args: 
logsBucket: 'gs://[BUCKET-NAME]'
```

**Comment by northtree** [comment]
If you just build from `Dockerfile`, use `--gcs-log-dir=gs://[BUCKET-NAME]/[FOLDER-NAME]`

**Comment by SpaceNet** [comment]
I could also do this, with objectView not  objectCreator
```
gsutil mb gs://[BUCKET-NAME]/
gsutil iam ch user:[user@email]:objectView gs://[BUCKET-NAME]
```

```
steps:
- name: gcr.io/cloud-builders/gcloud
  args: 
logsBucket: 'gs://[BUCKET-NAME]'
```

**Comment by mindovermiles262** [comment]
@SpaceNet buckets need to be globally unique - your chosen bucket name of `cloud-build-logs` is already in use.
