### ISSUE TITLE
Golang 1.9 support

### ISSUE THREAD

**Issue by cove** [GoogleCloudPlatform/cloud-builders#123]
Any ETA as to when the golang builder updated for 1.9?

**Comment by skelterjohn** [comment]
The `gcr.io/cloud-builders/go` image uses whatever Go distribution is found in the public `golang:alpine` or `golang:wheezy` distributions. Currently that is 1.7.5, but that seems pretty old at this point so I'll see if we can get something more recent.

**Comment by cove** [comment]
Cool thanks, I wonder if it would make sense to pin it to a version, so it's a little clearer from the Dockerfile what version of go is being used.

**Comment by skelterjohn** [comment]
Would you ever want to use not-the-latest-version?

**Comment by cove** [comment]
In our case no, but if it's set to `latest` it's hard to tell what version it's at, and it's not clear what causes it to get rebuilt when a new version is out if it's not rebuilding on commit is my thought.

**Comment by iwata** [comment]
And, how about using `golang:stretch`?
Because `golang:wheezy` is not followed 1.8.x and 1.9.x on [Go public registry](https://store.docker.com/images/golang).

**Comment by skelterjohn** [comment]
@cove Perfectly valid reason to want a pin, thank you.

@iwata We might use `golang:stretch`, or we might just use `golang` since we don't *really* care about the debian version for the go builder - it just needs to be *a* debian.

**Comment by skelterjohn** [comment]
`gcr.io/cloud-builders/go:wheezy` is now deprecated in favor of `gcr.io/cloud-builders/go:debian`, which supports go 1.9 (and whatever `golang:latest` supports).
