### ISSUE TITLE
Tag logs with build step instead of only having it in the textPayload

### ISSUE THREAD

**Issue by tlbdk** [GoogleCloudPlatform/cloud-builders#125]

**Comment by bendory** [comment]
Can you please clarify this request?

1. I assume this is in reference to Google Cloud Logging? (If yes, please confirm; if not, please clarify.)
2. What does "tag" mean? Are you suggesting that we add a resource label like 'build_step: <identifier>'?

**Comment by tlbdk** [comment]
Yes to both, fx. some kind of jsonPayload that would have a bit more information about what step is running.

**Comment by bendory** [comment]
Nice idea, I see how this would be helpful for users of Google Cloud Logging. We'll add a label for this in the coming week.
