### ISSUE TITLE
The npm builder is not public

### ISSUE THREAD

**Issue by OlivierBoucher** [GoogleCloudPlatform/cloud-builders#13]
As the title says, the npm builder is not available under https://console.cloud.google.com/gcr/images/cloud-builders?project=cloud-builders as the README suggests..

I know this is still beta but can we have an ETA on the availability?

**Comment by Philmod** [comment]
Hey Olivier, 

I added the npm builder in our next release, it should be public tomorrow.

**Comment by Philmod** [comment]
You got it. :)
