### ISSUE TITLE
fetch cloudbuild.yaml from GCS bucket

### ISSUE THREAD

**Issue by rimusz** [GoogleCloudPlatform/cloud-builders#130]
as already discussed in the slack, having an option to fetch `cloudbuild.yaml` from GCS bucket would be a very welcome option. 
Some uses cases:
1) releases from different branches can download it from GCS 
2) easier to update `cloudbuild.yaml` as it is not stored with the the code, specially in a team work
3) share the same `cloudbuild.yaml` between different repos, in that case pipeline changes only needed in one pleace

**Comment by Philmod** [comment]
Hey @rimusz, thanks for this great idea. We already added it internally as a feature request. We'll keep up updated here.

**Comment by rimusz** [comment]
awesome 👍

**Comment by rimusz** [comment]
@Philmod any updates on this one?

**Comment by Philmod** [comment]
@rimusz We have not prioritized this feature yet. I'll keep this bug up to date when I have more information.

**Comment by rimusz** [comment]
thanks

**Comment by bendory** [comment]
Feature requests for the hosted Google Clou Build Service or for the Github app should be filed on the public issue tracker. I've opened http://issuetracker.google.com/issues/156969165 for you.
