### ISSUE TITLE
Please support Gradle 4.2 for GCS integration

### ISSUE THREAD

**Issue by wyaeld** [GoogleCloudPlatform/cloud-builders#136]
Currently I see the cloudbuilders support gradle 3.5 and 4.0

There is however an extremely useful feature present in Gradle 4.2 where it allow for GCS to be used directly as a dependency source.

https://docs.gradle.org/current/userguide/dependency_management.html#mavenIvyGCSRepositoriesAuthDefault

This would obviously be quite useful on big projects.  Even if 4.2 is not the default version, it would be extremely useful to have available.

**Comment by skelterjohn** [comment]
aslo - can you vet the request?

**Comment by meltsufin** [comment]
@loosebazooka Is the move from 4.0 to 4.2 safe/compatible?
Otherwise, seems reasonable to me.

**Comment by loosebazooka** [comment]
I mean, presumably 4.2 should be backwards compatible.

So using 4.2 on projects that expect 4.0 should be okay, they never remove features between minor versions.

**Comment by bendory** [comment]
Closing as obsolete; we are currently at Gradle 4.6:

```
gcloud docker -- run gcr.io/cloud-builders/gradle --version

------------------------------------------------------------
Gradle 4.6
------------------------------------------------------------

Build time:   2018-02-28 13:36:36 UTC
Revision:     8fa6ce7945b640e6168488e4417f9bb96e4ab46c

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_131 (Oracle Corporation 25.131-b11)
OS:           Linux 4.9.0-6-amd64 amd64
```
