### ISSUE TITLE
Filter build steps by branch

### ISSUE THREAD

**Issue by sourcec0de** [GoogleCloudPlatform/cloud-builders#138]
Hey, everyone!
Great work on container builder. I'm loving the flexibility so far and the security model using KMS.
I'm currently working on a pipeline that will use a deis workflow container to deploy my app into GKE.

However, I don't want the deploy step to executed everytime a build is triggered. Only if I push to select branches. The plan is actually to use the `$BRANCH` var as the app name to deploy.

Branch filtering is a pretty common thing I've used in other CI systems like Codeship, Buildkite, etc.

I realize I could just create a trigger for each branch I want to deploy and use a different `.yaml` config but this seems a little redundant and wasteful.

It would be awesome if we could do something like this to only allow a step to execute when there is a branch match.

```yaml
steps:
# build and push steps
- id: deploy
  name: 'gcr.io/$PROJECT_ID/deis-cli:latest'
  args: ['pull', 'gcr.io/$PROJECT_ID/app:$REVISION_ID', '-a', '$BRANCH']
  branches: ['*-staging', 'testing', 'master']
  env:
    - 'DEIS_PROFILE=/workspace/deis.json'

```

Is there anything like this on the horizon?

**Comment by bendory** [comment]
You can do this already. When you define your trigger, the "Branch" field is a regex. Just put in a pattern there that matches the branches you want to fire your trigger.

Note that Container Builder uses [Go regular expressions](https://github.com/google/re2/wiki/Syntax). You can play with patterns in the Go Playground; a match on multiple branches is as simple as `branch_match_1|branch_match_2` as seen in [this sample code](https://play.golang.org/p/nAzqG2uirV).

Also note that during trigger setup, the UI will helpfully tell you which branches your pattern currently matches.

**Comment by sourcec0de** [comment]
@bendory I did mention that I knew we could do this. I was more interested in finding out if we could submit feature requests here. I think it would be helpful to allow this in the `cloudbuild.yaml` instead of the triggers themselves.

Thank you for following up so quickly though. :+1:

**Comment by skelterjohn** [comment]
This is an interesting idea - could have things like a step at the end that only ran on the master branch that published binaries to GCS (or pushed an image to GCR). Other branches, where people develop features or vet PRs, would skip this last step while still doing the rest of the build so that it's verified that artifacts are build properly and any unit tests pass.

I'll note that you can do this now by having your build step run a script that checks $BRANCH_NAME before continuing. I'd like to see how well that works in practice before we consider baking anything into the service config itself.

**Comment by sourcec0de** [comment]
@skelterjohn this is a very popular feature that [Buildkite implemented][1] based on requests on their slack channel a while back. I already went in the direction you mentioned above. It was the only way I could find to conditionally allow a build step. I think it would be nice to have a more declarative way to do this.

Again, thank you both for really fast response times. :+1:
You're killing it!

[1]: https://buildkite.com/docs/pipelines/branch-configuration#step-level-branch-filtering

**Comment by rimusz** [comment]
yes, this feature would make pipelines more powerful. and as long buildkite user really would love GCB to support it.

**Comment by sourcec0de** [comment]
@bendory it seems I'm not the only one interested in this. 
Could we reopen the ticket and keep the conversation going?

@rimusz thanks for chiming in.

**Comment by christophersanson** [comment]
we're looking at implementing this in a more first class way (and will leave this issue open to update when supported). In the meantime though here's a workaround script example that will filter a build step by branch. https://bit.googleplex.com/#/jasmuth/5847651643817984

**Comment by sourcec0de** [comment]
@christophersanson that link is inaccessible to anyone outside of google.

**Comment by skelterjohn** [comment]
Contents of the link @christophersanson posted:

    steps:
    - name: 'gcr.io/cloud-builders/docker'
      entrypoint: 'bash'
      args:
      - '-c'
      - |
        echo "Here's a convenient pattern to use for embedding shell scripts in cloudbuild.yaml."
        echo "This step only pushes an image if this build was triggered by a push to master."
        [[ "$BRANCH_NAME" == "master" ]] && docker push gcr.io/$PROJECT_ID/image

**Comment by andrew-waters** [comment]
The examples above are good workarounds. I'd like to see this as a native feature after this weeks GH integration.

There is a lot of value in adding these filters without having to resort to bash - not because it's complicated, but it's verbose and not so easy to follow just by sight.

My scenario is that I would like to build docker images with a `latest` tag on master and a SHA tag on branches to preserve commits to images at the expense of a denser registry. At the moment I actually build them both on trigger:

```
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:latest',
      '-t', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$COMMIT_SHA',
      '.']
```

Whereas my ideal definition would be:

```
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:latest', '.']
    branches: ['master']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$COMMIT_SHA', '.']
    branches: ['*']
```

As mentioned, I know this can be achieved verbosely with bash but that doesn't seem like the right way this should be done. Also, because the trigger's can't be edited when using the [new GH marketplace app](https://github.com/marketplace/google-cloud-build) I think that this is going to be a blocking issue for people onboarding.

**Comment by MichielDeMey** [comment]
Came here looking for the exact same solution to @andrew-waters issue.
With the new Google Cloud Build integration, there's currently no way to limit build steps to certain branches other than using bash scripts as mentioned above.

We're currently also looking at using https://github.com/keel-hq/keel for CD to our Kubernetes cluster.
As it currently stands, Keel requires semver versioning on your containers for deploying new k8s deployments/charts (which is the way to do it IMO).

However, I fear that when I use the `$TAG_NAME` variable substitution we might up automatically building a container with a `$TAG_NAME` from a branch other than master and overwrite existing containers.

**Comment by ardagnir** [comment]
Configurable GitHub app triggers are coming. (demo here: https://www.youtube.com/watch?v=iyGHW4UQ_Ts)

Once this happens, you should be able to configure app triggers to run only on specific branches similarly to the non-app triggers.

**Comment by sourcec0de** [comment]
I think we can finally close this 1 year later.
Cloud build can now filter triggers on tags, pr's and file globs.
There are other ways to think about running your triggering builds. 😉 

Thanks google cloud build team 👍

**Comment by fcollman** [comment]
can someone point to the documentation for this?

**Comment by NeoJRotary** [comment]
I make a docker image https://github.com/NeoJRotary/GCB-bridge with private Github App to temporarily solve this issue. Still hope GCB team can support those amazing features. It would be great to have integration with rich interface at GCP console.

**Comment by leo-baltus** [comment]
Please reopen this issue. Op seems happy but when using the GH app we are unable to do branch filtering, react differently to PR's, use include/exclude paths for mono-repos etc.

**Comment by gsf** [comment]
I could see a solution to this use case and others by allowing something like [argo's conditionals](https://github.com/argoproj/argo/blob/master/examples/README.md#conditionals).

**Comment by DiederikvandenB** [comment]
Would love to see this resolved soon.

**Comment by bondarewicz** [comment]
Please reopen  :neckbeard:

> Configurable GitHub app triggers are coming

does anyone knows any eta? this appears to be the only? option currently to notify GH about build status but we are missing trigger configuration

> Cloud build can now filter triggers on tags, pr's and file globs"_ 

while we can configure trigger details, unfortunately they still do not notify github about build status...

**Comment by MPV** [comment]
Related to this, how do I specify "all other branches than master"?

**Comment by gsf** [comment]
@MPV You mean other than `[ "$BRANCH_NAME" != "master" ] && ...` in a build script?

**Comment by bondarewicz** [comment]
> Related to this, how do I specify "all other branches than master"?

in bash `[ "$BRANCH_NAME" != "master" ]` as per @gsf would work just fine
in the trigger conf `[^(?!.*master)].*`

![image](https://user-images.githubusercontent.com/435051/49237078-69101980-f3f5-11e8-9f76-5d34a584f4b6.png)

**Comment by zargex** [comment]
@sourcec0de could you give us the link to those docs. Because here https://cloud.google.com/cloud-build/docs/running-builds/automate-builds, they said the build won't be lunch by Pull Request, they are launch by commits pushed to the origin. 

We are using the Google Cloud Build app for Github and I only see we can change the repository. The example here https://cloud.google.com/cloud-build/docs/run-builds-on-github create a new branch and the pull request, but I think the trigger here is still the push to a new branch.

We are interested on running our Cloud Build pipeline only when a PR is created and having branch conditionals (for example, deploy to staging if branch is `develop`). For the branch conditional currently we are using the bash workaround as posted above.

Thanks.

**Comment by ilkkao** [comment]
I think https://github.com/GoogleCloudPlatform/cloud-builders/issues/138#issuecomment-410947114 is still valid. It's error prone and not clean to override entry points for the pre-built cloud builder images.

**Comment by DiederikvandenB** [comment]
It is looking like this issue won't be reopened, while it is still not possible to filter branches when triggering Cloud Build through GitHub. Should we open a new issue to address this?

**Comment by bondarewicz** [comment]
@DiederikvandenB please do, we might get some answers

**Comment by DiederikvandenB** [comment]
Done:
https://github.com/GoogleCloudPlatform/cloud-builders/issues/431

**Comment by tino** [comment]
@sourcec0de, @bendory or @skelterjohn, please reopen this issue. It's the most commented on and followed issue in this repo.

The feature requested by this issue – *to filter build **steps** by branch* – is still a very valuable feature that all comparable build tools have. Yes there are workarounds, but they pretty much destroy the simple and elegant solution that a `branches` filter on a step would be.

(#431 is about the complete filtering in triggers as I read it, not about individual *steps*.)

**Comment by kubaj** [comment]
In addition to entrypoints workarounds, cloud builder have to pull steps' images everytime even if step runs only the bash condition and exits. Because of this, builds take much more time if you use a lot of custom steps which are not cached.

**Comment by msm** [comment]
Completely agree with @tino and @kubaj brings up a good point as well. Please consider re-opening and enabling such a feature.

Personally, I would much rather have the filtering happen in the cloudbuild.yaml file in source control, rather than trying to work around it by configuring the github application (not in source control).

**Comment by ImJasonH** [comment]
This bug has a lot of great insights, and a lot of useful feedback.

However, in an attempt to keep this repo on-topic (the topic being the builder images in the repo itself) and to improve repo communication (#443), we are asking people to file feedback about the GCB service itself as described here: https://cloud.google.com/cloud-build/docs/getting-support

Creating issues in the public issue tracker lets us dedupe them to focus responses and reduce noise, and lets us assign engineers and track progress.

**Comment by gsf** [comment]
I've created https://issuetracker.google.com/issues/124468298.

**Comment by jdamour98** [comment]
FYI, it seems like google has responded to the issue above. They have began working on it

**Comment by max-sixty** [comment]
Does anyone have an idea why this doesn't work:

```yaml
  args: 
  - '-c'
  - |
    [[ "$BRANCH_NAME" == "master" ]] && bash update_deployer.sh test $COMMIT_SHA
```

but this does (i.e. with the extra line):

```yaml
  args: 
  - '-c'
  - |
    [[ "$BRANCH_NAME" == "master" ]] && bash update_deployer.sh test $COMMIT_SHA
    echo "Pushed to test"
```

I also tried a variant with the command on a single line, in single quotes, while failed

Thanks!

**Comment by icereval** [comment]
@max-sixty,
 
The exit code ends up being `1` when the condition is not matched, you should be able to add a return.

e.g.

```
  args: 
  - '-c'
  - |
    [[ "$BRANCH_NAME" == "master" ]] && bash update_deployer.sh test $COMMIT_SHA || return 0
    echo "Pushed to test"
```

**Comment by max-sixty** [comment]
Thank you @icereval !

**Comment by andrewmclagan** [comment]
Since there is little activity, responsiveness or notice on the Google Issue Tracker for this feature. I will comment here and await a response on progress. We need to know as we will either create a workaround or await...

**Comment by Liath** [comment]
Adding `return 0` gave me a ```return: can only `return' from a function or sourced script```
`&& true` is slightly uglier but seems to work:
```yaml
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    [[ "$BRANCH_NAME" == "master" ]] && echo pass || echo fail && true
```

**Comment by Shigawire** [comment]
Don't use `return 0` but `exit 0`

**Comment by andrewmclagan** [comment]
I suggest people checkout https://github.com/drone/drone Its everything Cloud Build wants to be, but cant because its too slow to move. Drone has been around allot longer, is far more mature and feature rich. We migrated our pipelines over to drone and ... honestly best thing we did.
