### ISSUE TITLE
Consider merging aspnetcorebuild image here

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/cloud-builders#14]
Just discovered a build image for 'gcr.io/gcp-runtimes/aspnetcorebuild-1.0:latest' exists. (from [here](https://cloudplatform.googleblog.com/2017/03/ASP-NET-Core-containers-run-great-on-GCP.html)).

Since it's not described in this repo and not listed under gcr.io/cloud-builders I think this introduces a discoverability issue. By not having that image here, we're introducing 2 problems/questions for a user:

- why aspnetcorebuild is not under cloud-builders too?
- what else is under "gcr.io/gcp-runtimes" (google search doesn't return anything)

My recommendation: create this image here under cloud-builders bucket as well and have it just do `FROM ....`.

**Comment by bendory** [comment]
This cloud-builders section is for supported build steps for the Google Cloud Container Builder API (see [main readme](https://github.com/GoogleCloudPlatform/cloud-builders/)) that are supported by the Container Builder team. The aspnetcorebuild image does not meet this definition.
