### ISSUE TITLE
[Request] Containers vulnerability scan with clair-scanner

### ISSUE THREAD

**Issue by iwata** [GoogleCloudPlatform/cloud-builders#143]
I want to use [clair-scanner](https://github.com/arminc/clair-scanner) to check whether there is vulnerability before pushing the image to GCR. 
(I don't know. Is there a simple way to introduce it?)

**Comment by Philmod** [comment]
Hey @iwata, 
You can run anything during a build. So if this tool has a CLI, you could even create a cloud builder to use it. Feel free to share your experience here.
