### ISSUE TITLE
Baffling behavior of args when building go binary

### ISSUE THREAD

**Issue by ernsheong** [GoogleCloudPlatform/cloud-builders#146]
Hi all, 

The following works:

```
steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['build', '-o', 'main', '-v', '-ldflags', '"-d"', '-a', '.']
```

But adding an additional flag to -ldflags does not:

```
steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['build', '-o', 'main', '-v', '-ldflags', '"-d -w"', '-a', '.'] # Added -w flag in flag list
```
 returns `flag provided but not defined: -d -w` But the -w flag is listed...

Is this expected behaviour? What is the alternative?

**Comment by skelterjohn** [comment]
Instead of `'"-d -w"'`, use `'-d -w'`. The quotes you provided are to help the shell figure out that `-d` and `-w` go together, but inside cloud build there is no actual shell - just the yaml parser, so `'-d -w'` is sufficient.

**Comment by ernsheong** [comment]
Interesting. Thank you!
