### ISSUE TITLE
occasional java.io.EOFException during build

### ISSUE THREAD

**Issue by Fabian-K** [GoogleCloudPlatform/cloud-builders#152]
Hi,

i have a build pipeline where (among others) I create a war file using gradle and kotlin. In ~5 out of 20 builds, the builds fails with the following exception.

```
Step #2 - "build-java": java.io.EOFException
Step #2 - "build-java": at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:229)
Step #2 - "build-java": at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:162)
Step #2 - "build-java": at java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:227)
Step #2 - "build-java": at java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:179)
Step #2 - "build-java": at com.sun.proxy.$Proxy77.clearJarCache(Unknown Source)
...
```
I´m not sure if this is an issue with the cloud builder in general or my build pipeline. Do you have suggestions how to investigate this?

Thanks,
Fabian

**Comment by bendory** [comment]
The above log snippet is from the output of the build step itself, not from our code that executes the pipeline -- so I don't think this is an issue with cloud builder.

It is possible that this is a bug in the Gradle build step itself.

My first suggestion is that you see if the problem is reproducible when running the [local builder](github.com/GoogleCloudPlatform/container-builder-local).

**Comment by Fabian-K** [comment]
Thanks, i´ll try to update the gradle version and/or use the official gradle docker image. A java.io.EOFException because of some issue with the network-attached storage is I guess unlikely?

**Comment by bendory** [comment]
This GitHub issue tracker is intended for bugs with the officially supported builder images specifically.
Please report issues and feature requests regarding the GCB service to our public issue tracker at
https://issuetracker.google.com/issues/new?component=190802&template=1162743
