### ISSUE TITLE
Use gcr.io/google-appengine/openjdk instead of dockerhub openjdk?

### ISSUE THREAD

**Issue by ChengyuanZhao** [GoogleCloudPlatform/cloud-builders#164]
Are you guys open to using the openjdk image that the cloud java runtimes team maintains instead of the dockerhub version? (https://github.com/GoogleCloudPlatform/openjdk-runtime)

We use your mvn image, and noticed that if your base openjdk image was switched to the one that Google maintains then we could also monitor the image for security/vulnerabilities (https://github.com/GoogleCloudPlatform/runtime-builder-java/issues/92)

**Comment by ImJasonH** [comment]
Yeah I think we'd prefer to use that openjdk image. Would you like to send a PR?
