### ISSUE TITLE
Docker 17.09+ is required to use --chown flag on ADD/COPY operations in Dockerfile

### ISSUE THREAD

**Issue by ryan-mf** [GoogleCloudPlatform/cloud-builders#188]
We're trying to speed up our builds, and one of the ways to do that is to pull in the lastest image tag and use it as a cache source during the docker build.

However, our Dockerfile uses pip install with a requirements.txt, and we're trying to use the newer --chown flag when our Dockerfile copies in the requirements.txt to solve a CI issue where differing permissions inside CI vs inside GCB results in cache invalidation.

Given that the pip install step is the vast majority of our build time (and completely redundant on every build given our requirements.txt), we're hoping to get GCB up to Docker 17.09 ASAP so we can start using the --chown flag to ignore the source permissions as a means to keep the cache valid.

**Comment by Philmod** [comment]
Hey Ryan,
We are planning to upgrade Docker version in Q1.

**Comment by bendory** [comment]
Rejecting in favor of #194

**Comment by codrienne** [comment]
Docker has been upgraded to 17.12.0-ce.
