### ISSUE TITLE
UX request: Git SHORT_SHA on build history list view

### ISSUE THREAD

**Issue by ofpiyush** [GoogleCloudPlatform/cloud-builders#191]
Not sure if this is the correct place to ask for this.

The git commit on https://console.cloud.google.com/gcr/builds is 6 letters.

That's one short of the $SHORT_SHA. It robs of an amazing opportunity to copy image tags/other tags which are SHORT_SHA.

Our use case:

We push some files to a bucket after the build, these files are in `bucket/$SHORT_SHA` folder. Would be amazing if we could just copy the commit id from the list page.

**Comment by ImJasonH** [comment]
Talked to our UI engineer, this change should be released soon. Thanks for bringing it to our attention!
