### ISSUE TITLE
Add  header "Access-Control-Allow-Origin" to request for Google Cloud Storage

### ISSUE THREAD

**Issue by EliuX** [GoogleCloudPlatform/cloud-builders#200]
The public resources of blackbox are hosted in the Google Cloud Storage folder `gs://blackbox-public` , currently a call to a resource from Javascript code is returning an error related to [CORS].(https://cloud.google.com/storage/docs/cross-origin).

**How to reproduce the error**
Check the query done to show the logged user icon. It would be something like:
>http://storage.googleapis.com/blackbox-public/partners/blackbox/blackbox-smaller.png

And in console it will return something like
>Failed to load http://storage.googleapis.com/blackbox-public/partners/blackbox/blackbox-smaller.png: 
> No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 
>'http://localhost:8000' is therefore not allowed access.

Nonetheless if you open that url it will open successfully in your browser. 

**Suggestions**
This error could be solved adding the header to such requests (requests related to icons that can be loaded from other urls such as avatars) the header `Access-Control-Allow-Origin: *`

**Comment by remotevision** [comment]
Was this resolved? I still get this error and CANNOT figure out a way around it.

**Comment by ImJasonH** [comment]
Information about setting CORS headers for your GCS bucket here: https://cloud.google.com/storage/docs/cross-origin

Note that this is unrelated to GCB or any builder in this repo.

**Comment by remotevision** [comment]
FYI, the problem was actually related to sending to many `x-goog-meta-` headers. I have found that if I send more that two headers, the signature upload url rejects the upload. This seems like a bug to me.
