### ISSUE TITLE
Add support for maven wrapper (mvnw)

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/cloud-builders#202]

**Comment by ImJasonH** [comment]
Is the intention that this will be used by Java Runtimes as a first-class builder, like `mvn` and `gradle` (and their common ancestor `javac`) are today? With all the expectation of first-class support (fixing bugs, rebuilding regularly, etc.) that entails?

If not, this can be added to [the community repo](https://github.com/GoogleCloudPlatform/cloud-builders-community), which has a weaker expectation of first-class support.

**Comment by meltsufin** [comment]
The way the wrapper works is that it downloads the version of the Maven executable that the project declares, and then uses it. We don't have plans to support it in Java Runtimes. It's just something to consider, if there is community interest in it.

**Comment by ImJasonH** [comment]
If there isn't a plan to use this in any officially-supported capacity, it sounds like this belongs in the community repo. Feel free to file a bug or submit a PR for it over there.
