### ISSUE TITLE
Missing image tags

### ISSUE THREAD

**Issue by haf** [GoogleCloudPlatform/cloud-builders#203]
I'd like our builds to be repeatable.

We use the `yarn` tool/container. We had a build breaking due to https://github.com/GoogleCloudPlatform/cloud-builders/commit/2d9d102aeb9d286663d337b1394ce31e1ff04bc3 because of an upgrade of the node version (it's been locked down in our repo and npm crashes with that error, so it's really doing what it's intended to do).

Could you please tag your tools so we can use a specific version, rather than having to depend on `:latest`? Like, tagging `:v1.3.2` in this case.

**Comment by Philmod** [comment]
Hey,

That's a good point. We tag the `npm` builder, but haven't done so with the `yarn` one.

Feel free to submit a PR too :)

**Comment by haf** [comment]
LIke this?
