### ISSUE TITLE
Silent errors when quotes are excluded when 'id' is supplied

### ISSUE THREAD

**Issue by maxim-lian** [GoogleCloudPlatform/cloud-builders#206]
I get errors with no explanation or logs, I think depending on whether a task has an `id` key and whether there are quotes.

Error message:
![image](https://user-images.githubusercontent.com/5635139/35595315-4b0139ce-05e4-11e8-95e9-6b895246c0ed.png)

This doesn't work:
```
- id: 'pull-base'
  name: gcr.io/cloud-builders/docker
  args: [pull, gcr.io/sixty-capital/base:master]
```

but this works:
```
- id: 'pull-base'
  name: gcr.io/cloud-builders/docker
  args: [pull, 'gcr.io/sixty-capital/base:master']
```

as does this:
```
- name: gcr.io/cloud-builders/docker
  args: [pull, 'gcr.io/sixty-capital/base:master']
```

**Comment by Philmod** [comment]
Hey @maxim-lian ,

I believe the problem is the problem is the missing quotes around the image "gcr.io/sixty-capital/base:master" in your arguments.

**Comment by ImJasonH** [comment]
Indeed, `args: [thing:foo]` is not valid YAML. We'd reject this before sending the request if you passed that YAML to `gcloud container builds submit`.

In general, I try to make sure to quote every string field when I write YAML, to avoid confusing behavior like this.

```
steps:
- id: 'pull-base'
  name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/my-project/my-image:some-tag']
```

In your screenshot above, what's the value of the **Status detail** row? We can probably give you a more descriptive error message than we do.

**Comment by maxim-lian** [comment]
Thanks for the fast response.

And actually there was better error reporting than I initially concluded - I raced to look at the logs - but there is a 'detail':

![image](https://user-images.githubusercontent.com/5635139/35598417-43b5716e-05f1-11e8-8930-76e62c7dc2ac.png)
