### ISSUE TITLE
[Go] Builder -- different (but why?) behavior

### ISSUE THREAD

**Issue by DazWilkin** [GoogleCloudPlatform/cloud-builders#208]
Compelled by my colleague to investigate using Container Builder for this project:
https://github.com/GoogleCloudPlatform/cloud-functions-go

I can get the function to work if I build the Go binary locally and deploy that:

```
GOARCH="amd64" \
GOOS="linux" \
go build -tags netgo -tags node main.go
```
and then git push `main` so not building it on Container Builder:

```
steps:
- name: "gcr.io/cloud-builders/npm"
  args: ["install", "--ignore-scripts", "-save", "local_modules/execer"]
- name: "busybox"
  args: ["ls", "-las"]
- name: "gcr.io/cloud-builders/gcloud"
  args: [
    "beta",
    "functions",
    "deploy","helloworld",
    "--entry-point","helloworld",
    "--source","./",
    "--trigger-http",
    "--project","${PROJECT_ID}"
  ]
```
But it doesn't work if I use the Go Builder:
```
steps:
- name: "gcr.io/cloud-builders/go"
  args: ["build", "-tags", "netgo", "-tags", "node", "main.go"]
  env: [
    "GOARCH=amd64",
    "GOOS=linux",
    "GOPATH=."
  ]
- name: "gcr.io/cloud-builders/npm"
  args: ["install", "--ignore-scripts", "-save", "local_modules/execer"]
- name: "busybox"
  args: ["ls", "-las"]
- name: "gcr.io/cloud-builders/gcloud"
  args: [
    "beta",
    "functions",
    "deploy","helloworld",
    "--entry-point","helloworld",
    "--source","./",
    "--trigger-http",
    "--project","${PROJECT_ID}"
  ]
```
I tried repro'ing the process locally:
```
docker run \
--volume=$PWD:/src \
--env=GOPATH=/src \
--env=GOOS=linux \
--env=GOARCH=amd64 \
gcr.io/cloud-builders/go build -tags netgo -tags node -o /src/main /src/main.go
```
The binary is `6430017` bytes from the Builder (I confirmed the size whether building with the Builder locally or running the Builder service) but `8909110` bytes when built locally. While this may be a red-herring, it seems significant. I can't determine why the processes 2 would differ.

```
go version
go version go1.10rc1 linux/amd64
```
and
```
docker run gcr.io/cloud-builders/go version
Documentation at https://github.com/GoogleCloudPlatform/cloud-builders/blob/master/go/README.md
Running: go version
go version go1.9.3 linux/amd64
```

Can anyone help me understand why this would be?

**Comment by DazWilkin** [comment]
The aforementioned colleague helped me identify:

The correct (!?) file `8909110`:

```
ldd main
	linux-vdso.so.1 (0x00007ffda27fb000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fbf3c150000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fbf3bdb1000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fbf3c36d000)
```

The Builder file `6430017`:

```
ldd main
	linux-vdso.so.1 (0x00007ffe8b580000)
	libc.musl-x86_64.so.1 => not found
```

**Comment by DazWilkin** [comment]
I think I may just need to use `go:debian`

**Comment by ImJasonH** [comment]
Yeah that might be the difference. Also worth considering using a `go` builder based on `golang:rc` (which is `1.10rc1`) just to eliminate that variable too.

**Comment by DazWilkin** [comment]
OK. It's working w/ `go:debian` thanks @ImJasonH @salrashid123

Will document but `cloudbuild.yaml`:
```
steps:
- name: "gcr.io/cloud-builders/go:debian"
  args: ["build", "-tags", "netgo", "-tags","node","main.go"]
  env: [
    "GOARCH=amd64",
    "GOOS=linux",
    "GOPATH=."
  ]
- name: "gcr.io/cloud-builders/npm"
  args: ["install", "--ignore-scripts", "-save", "local_modules/execer"]
- name: "gcr.io/cloud-builders/gcloud"
  args: [
    "beta",
    "functions",
    "deploy","helloworld",
    "--entry-point","helloworld",
    "--source","./",
    "--trigger-http",
    "--project","${PROJECT_ID}"
  ]
```

**Comment by ImJasonH** [comment]
Glad that worked!

**Comment by iangudger** [comment]
To clarify, `-tags netgo` is supposed to prevent the use of libpthread and libc. It sounds like you switched from the correct behavior to an incorrect behavior.

**Comment by iangudger** [comment]
Actually, that is wrong. You were getting libc.musl linked in for some reason which is still a libc. That isn't available on GCF. If you managed to build it as a static pure-go binary as I intended I don't think you would be having this issue.

**Comment by DazWilkin** [comment]
@iangudger it's unclear from your comments where I was wrong and what you think I should do.

With the config I summarized above (using the `debian` tagged Builder), it works when deployed to GCF.

**Comment by iangudger** [comment]
Sorry. Basically, `-tags netgo` is supposed to prevent _any_ libc from being used. For some reason that isn't working and is resulting in non-portable binaries.

**Comment by iangudger** [comment]
@DazWilkin Can you try this? https://github.com/GoogleCloudPlatform/cloud-functions-go/pull/28

`ldd` should say `not a dynamic executable`

**Comment by DazWilkin** [comment]
@iangudger you bet... will try it today and report back. Thanks!

**Comment by DazWilkin** [comment]
@iangudger I'm not using the `Makefile` to build the Go binary but I did use the `go build` command from as one of the Container Builder steps.

1. I used the revised `Makefile`, copied the locally-generated binary `6970932` to the repo, removed the `go build` step from the Container Builder and deployed it as-is. That works.
```
ldd main
	not a dynamic executable
```

2. I then moved the `go build` back to the Container Builder using the revised (`CGO_ENABLED=0`) step. The binary is `6430293` (different go version). That works.

```
- name: "gcr.io/cloud-builders/go:debian"
  args: ["build", "-tags","node","main.go"]
  env: [
    "GOARCH=amd64",
    "GOOS=linux",
    "CGO_ENABLED=0",
    "GOPATH=."
  ]
```
and:
```
ldd main
	not a dynamic executable
```

3. Then, just to close out any discrepancy between Go versions, I used the `golang:rc` per @ImJasonH's suggestions in a previous comment. The binary is `6928901`. That works:

```
- name: "golang:rc"
  args: ["go", "build", "-tags","node","main.go"]
  env: [
    "GOARCH=amd64",
    "GOOS=linux",
    "CGO_ENABLED=0",
    "GOPATH=/workspace"
  ]
```
and:
```
ldd main
	not a dynamic executable
```

So, it always works but something is causing variability in the binary size (that does not appear to matter). The only configuration that doesn't work is using the default Container Builder image `go`. `go:debian` works (I assume `go:alpine` won't work`)

Doesn't work:

```
steps:
- name: "gcr.io/cloud-builders/go"
  args: ["build", "-tags", "netgo", "-tags", "node", "main.go"]
  env: [
    "GOARCH=amd64",
    "GOOS=linux",
    "GOPATH=."
  ]
```

I'll try replacing `-tags netgo` with `CGO_ENABLED=0` after breakfast.

**Comment by DazWilkin** [comment]
Replacing `-tags netgo` with `CGO_ENABLED=0` worked too with the Builder. The binary is `6430293`:

```
- name: "gcr.io/cloud-builders/go"
  args: ["build", "-tags","node","main.go"]
  env: [
    "GOARCH=amd64",
    "GOOS=linux",
    "CGO_ENABLED=0",
    "GOPATH=/workspace"
  ]
```
and:
```
ldd main
	not a dynamic executable
```

So, the only (!) config that doesn't work is the one I tried originally with a binary size `6489236`:

```
 name: "gcr.io/cloud-builders/go"
  args: ["build", "-tags", "netgo", "-tags","node","main.go"]
  env: [
    "GOARCH=amd64",
    "GOOS=linux",
    "GOPATH=/workspace"
  ]
```
and:
```
ldd main
	linux-vdso.so.1 (0x00007fff11d55000)
	libc.musl-x86_64.so.1 => not found
```

**Comment by iangudger** [comment]
@DazWilkin linking in different amounts of stuff will cause different binary sizes. It seems that `-tags netgo` was being ignored for some reason.

**Comment by DazWilkin** [comment]
Indeed. Although `go version` and Docker image aside, I should be building the same binary from the same constituents each time
