### ISSUE TITLE
Specifying Docker build arguments in a single line adds unexpected "-" character

### ISSUE THREAD

**Issue by SimonTheLeg** [GoogleCloudPlatform/cloud-builders#210]
Hey guys so I've been playing around with cloud build for a little bit now (https://github.com/SimonTheLeg/github-cloudbuild-example), and have experienced this strange behaviour. So if I specify all of my docker build arguments in a single line (see tag v1.0.0) like this

`args: ['build', '-t', 'gcr.io/${PROJECT_ID}/github-cloudbuild-example:${TAG_NAME}', '.']`

cloud-builder decides to put a "-" character right after the "...example" part, thus failing the build

![screen shot 2018-02-05 at 21 55 04](https://user-images.githubusercontent.com/20774623/35828409-a7b1ccf8-0abf-11e8-84b6-9b58d99f39a1.png)

However if I put the arguments in multiline (see tag v1.1.0) everything is working properly.

**Comment by ImJasonH** [comment]
That is certainly unexpected.

It looks like this could be an artifact of [this change](https://github.com/SimonTheLeg/github-cloudbuild-example/commit/140eb52691d19ccc91713e49e471c540d0fb3bf1#diff-e5fc65747fb9417968a3295dc1ac5111), which would lead to the trailing `-` if the build was triggered on a tag change and not a branch change. In that case, `$BRANCH_NAME` would be `""` and the resulting image would be `gcr.io/redacted/github-cloudbuild-example-:v1.0.0` like you're seeing.

Are you seeing this behavior on your `v1.1.0` tag too, which doesn't have the `$BRANCH_NAME`?

**Comment by SimonTheLeg** [comment]
Oh you are absolutely right, the tag was on the wrong commit. Must've been a little late yesterday 😅. Closing this now, obviously not an issue with the platform.
