### ISSUE TITLE
[urgent] Github authentication fails for GCR triggers

### ISSUE THREAD

**Issue by ofpiyush** [GoogleCloudPlatform/cloud-builders#211]
I don't know where else to open this issue.

While creating a new trigger, when authenticating github , I get a URI mismatch error.

**Comment by bendory** [comment]
Hi @ofpiyush, best way to report this issue and enable us to debug is to send an email to gcr-contact@google.com with full details, including:

- full URL
- screenshot or cut/paste of the exact error (whatever is easy + complete to capture)
- GCP project in question

I'm closing this issue with the assumption that we'll continue a private conversation on that thread.
