### ISSUE TITLE
bazel cloud builder does not tag the bazel version inside it

### ISSUE THREAD

**Issue by Mistobaan** [GoogleCloudPlatform/cloud-builders#212]
I was hoping I could do something like:
```
steps:
# Build the main Docker cmd image
- name: gcr.io/cloud-builders/bazel:0.7
  args: ['run', '//:docker']
```
But seems the cloud build images are not being tagged beside the `latest` tag.

[cloud builder images on google cloud](https://console.cloud.google.com/gcr/images/cloud-builders/GLOBAL/bazel?gcrImageListsize=50&gcrImageListquery=%255B%255D)

![screen shot 2018-02-08 at 3 06 54 pm](https://user-images.githubusercontent.com/112599/36003215-d855eed8-0ce1-11e8-947e-99756a8494c5.png)

Am I missing something ?

**Comment by bendory** [comment]
Tags are defined in the `cloudbuild.yaml` for the particular builder. For instance, the Docker builder defines tags for several versions as can be seen here (scroll to the bottom): https://github.com/GoogleCloudPlatform/cloud-builders/blob/master/docker/cloudbuild.yaml
Also note that if you look in [gcr.io/cloud-builders/docker](http://gcr.io/cloud-builders/docker), you'll also find an older tagged [docker:1.12.6](http://gcr.io/cloud-builders/docker:1.12.6) -- which is no longer supported, but the old image lingers.

If you require a specific version of bazel, you can submit a PR adding it to https://github.com/GoogleCloudPlatform/cloud-builders/blob/master/bazel/cloudbuild.yaml. (If you go this route, please include an explanation of your need for a specific version.)

**Comment by Mistobaan** [comment]
So there is no id for Bazel, and is always assumed to be the latest. Seems to me that the issue is open.
This  is not about a particular bazel id but more about the process of how the bazel cloudbuild images are tagged (or not tagged in this case). 
bazel is quickly evolving and is not back compatible yet. You need __strict__ versioning. I don't have the time to figure out the PR and follow on, I just know that my cloudbuild setup with bazel is suddenly failing and I can't spin up the previous version or tag it, because there are no tags.

**Comment by ImJasonH** [comment]
The latest version of bazel, `0.10.0`, was released Feb 1, 8 days ago.

Looking at the image history, a version of the bazel builder was pushed before that, e.g., `gcr.io/cloud-builders/bazel@sha256:43ef5417084ff06a8c7b55b773728b1eb172799253c96cb09a74f7ab5b3f3031`

```
$ docker run -v /tmp:/workspace gcr.io/cloud-builders/bazel@sha256:43ef5417084ff06a8c7b55b773728b1eb172799253c96cb09a74f7ab5b3f3031 version
Build label: 0.9.0
Build target: bazel-out/k8-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Dec 19 09:31:58 2017 (1513675918)
Build timestamp: 1513675918
Build timestamp as int: 1513675918
```

So you can at least use that image in the meantime until either a.) you can update your build to be compatible with `0.10.0`, or b.) bazel pushes a fix for your issue in some new latest release, or c.) we decide to version all bazel releases.

**Comment by bbarnes52** [comment]
IMHO this should be reopened, this seems like a pretty useful FR!

**Comment by hulkholden** [comment]
Leaving some breadcrumbs here for anyone falling down the same rabbithole as I did.

https://l.gcr.io/google/bazel and http://gcr.io/cloud-marketplace-containers/google/bazel (referenced in a couple of places in the cloud-builders docs) both seem to have stopped receiving updates around 3.5.0 (2020).

gcr.io/bazel-public/bazel appears to be getting actively updated (has 6.2.1) - docs here: https://bazel.build/install/ubuntu#docker-container.

**Comment by imjasonh** [comment]
You might also be interested in using `cgr.dev/chainguard/bazel`, which is about 2/3rds the size, supports amd64 and arm64 (not very interesting for Google Cloud Build, admittedly) and should have many fewer (often near-zero!) known vulnerabilities:

```
$ grype registry:gcr.io/bazel-public/bazel:latest
 ✔ Cataloged packages      [422 packages]
 ✔ Scanning image...       [326 vulnerabilities]
   ├── 0 critical, 8 high, 172 medium, 110 low, 36 negligible
   └── 114 fixed
```

```
$ grype registry:cgr.dev/chainguard/bazel:latest
 ✔ Cataloged packages      [92 packages]
 ✔ Scanning image...       [0 vulnerabilities]
   ├── 0 critical, 0 high, 0 medium, 0 low, 0 negligible
   └── 0 fixed
```

The latest image is also tagged as `:6.2.1`, but this is going to [change in August](https://www.chainguard.dev/unchained/scaling-chainguard-images-with-a-growing-catalog-and-proactive-security-updates) in the free public tier.
