### ISSUE TITLE
New yarn builder doesn't have make

### ISSUE THREAD

**Issue by anuraaga** [GoogleCloudPlatform/cloud-builders#213]
Many NPM dependencies, like `sharp`, 'image-loader', etc, require a native build when initializing, so need `gcc` and `make` available. While these do make the image size larger, for a cloud builder I think it's a reasonable default considering how common it is to need these during builds.

**Comment by bendory** [comment]
#214

**Comment by bendory** [comment]
Strange, I thought I fixed this 2 weeks ago with #214 but obviously I missed something. Thanks for calling it out to us, looking now...

**Comment by bendory** [comment]
I found the problem; we missed a manual step in our internal release process. I am taking care of that now which means that we expect to release change #214 which adds gcc + make into the yarn builder on Monday.

Sorry for the oversight, and thanks for bringing this to our attention!
