### ISSUE TITLE
Golang builder challenged by "-gcflags='-N -l'" (works with "-gcflags=-N -gcflags=-l")

### ISSUE THREAD

**Issue by DazWilkin** [GoogleCloudPlatform/cloud-builders#225]
Using the Golang Builder in combination with Stackdriver Error Reporting, I'm [instructed](https://cloud.google.com/debugger/docs/setup/go#gce) to `go build -gcflags='-N -l'` but the Builder balks at this.

I tried many permutations of the command without success:

```
Step #0: Running: go build -gcflags='-N -l' -a -o main
Step #0: invalid value "'-N -l'" for flag -gcflags: missing =<value> in <pattern>=<value>
```

But discovered a working combination appears to be `go build -gcflags=-N -gcflags=-l`

The command works as written locally so perhaps this is a version discrepancy?

```bash
go build -gcflags='-N -l' -a -o main
go build -gcflags '-N -l' -a -o main
go version
go version go1.10 linux/amd64
```
Recommendation:
-- Resolve the discrepancy; and/or
-- Document the solution to overcome the error

**Comment by bendory** [comment]
closing as obsolete; see https://github.com/GoogleCloudPlatform/cloud-builders/issues/677
