### ISSUE TITLE
gcloud: Usage of cloud-datastore-emulator

### ISSUE THREAD

**Issue by breznik** [GoogleCloudPlatform/cloud-builders#229]
I would like to run the cloud-datastore-emulator during my build for some integration tests. Is there a recommended way to do this? I noticed the gcloud builder does include the emulator, although - if you run it it's missing a JRE so it's not possible to run. Even if the gcloud builder bundled a JRE to fix this, how would you go about using it as part of the build?

**Comment by bendory** [comment]
Hi Baron,

Thanks for the bug report, will add the JRE to our `gcloud` image, hopefully in the coming week. In the meantime, to unblock yourself, you can add it by building your own `cloud-datastore-emulator` builder off our `gcloud` builder and installing the JRE.

**Comment by bendory** [comment]
A new version of the gcloud image will be released either tomorrow (Mar 15) or Monday (Mar 20); in the interim, if you build your own version off the Dockerfile on the master branch, it will have the JRE installed.
