### ISSUE TITLE
Add Terraform cloud builder

### ISSUE THREAD

**Issue by majelbstoat** [GoogleCloudPlatform/cloud-builders#233]
Terraform is a popular system for deploying and managing infrastructure. An official builder image for running terraform commands would be great 🙏.

**Comment by ImJasonH** [comment]
This is a perfect candidate for a community-supported builder, which can be contributed to our [community builder repo](https://github.com/googlecloudplatform/cloud-builders-community).

**Comment by ocervell** [comment]
Sorry for re-opening this, but wouldn't it be nice to host the Terraform builder on this repo, so that it's a publicly usable image (without having to be rebuilt by the user in their own Cloud Build project) ? I think @GoogleCloudPlatform/cft would benefit from this.

**Comment by bendory** [comment]
Please submit this as a PR to the [Community Builders repo](https://github.com/GoogleCloudPlatform/cloud-builders-community/).
