### ISSUE TITLE
git command line args that are prefixed with '-' are expanded improperly.

### ISSUE THREAD

**Issue by wibobm** [GoogleCloudPlatform/cloud-builders#243]
- name: 'gcr.io/cloud-builders/git'
  args: ['clone','-b develop','git@github.com:stuff/stuff.git']

expands to:

git clone "-b develop" git@github.com:stuff/stuff.git

The double quotes around -n develop prevents git from working properly.

**Comment by ImJasonH** [comment]
The fix is to pass each arg separately, since as you've seen, args that contain spaces get quoted into a single arg.

```
steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', '-b', 'develop', 'git@github.com:stuff/stuff.git']
```
