### ISSUE TITLE
Can't run python rules with gcr.io/cloud-builders/bazel

### ISSUE THREAD

**Issue by raliste** [GoogleCloudPlatform/cloud-builders#246]
We get:

```
ERROR: error loading package '': Encountered error while reading extension file 'requirements.bzl': no such package '@wut//': pip_import failed:  (Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/workspace/.bazel/external/io_bazel_rules_python/tools/piptool.par/__main__.py", line 26, in <module>
ImportError: No module named pkg_resources
)
INFO: Elapsed time: 5.142s
FAILED: Build did NOT complete successfully (0 packages loaded)
ERROR: Build failed. Not running target
```

external/requirements.txt includes both setuptools and distribute.

One possible fix is to add build a Docker image on top of  gcr.io/cloud-builders/bazel with the `python-pkg-resources` package, but this is not ideal. Any pointers?

**Comment by ImJasonH** [comment]
It sounds like adding `python-pkg-resources` to the apt packages installed on the bazel image ([here-ish](https://github.com/GoogleCloudPlatform/cloud-builders/blob/master/bazel/Dockerfile#L6)) might solve this issue, is that your understanding as well?

**Comment by raliste** [comment]
Thank you for the incredible timing reviewing this issue @ImJasonH !

That does solve our issue, but is not ideal. Should this be fixed once the python rules are truly hermetic?

**Comment by ImJasonH** [comment]
I'm not familiar enough with Bazel's Python support to know the answer to that. Do you have any more information, a Bazel issue perhaps?

I'm happy to add the package to the builder if it unblocks you, we have added other required packages in the past for similar reasons.

**Comment by raliste** [comment]
Thank you for the PR!. We were actually just testing `bazel run` against a simple python script with setuptools as a dependency. The build was created via an internal API.
