### ISSUE TITLE
Trying the mvn sample: does not work for me.

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/cloud-builders#250]
I clone this repo, and then follow the README:

gcloud container builds submit . --config=cloudbuild.yaml

and get 

ludo-macbookpro1:mvn ludo$ gcloud container builds submit . --config=cloudbuild.yaml
Creating temporary tarball archive of 11 file(s) totalling 6.3 KiB before compression.
Uploading tarball of [.] to [gs://pubrobots_cloudbuild/source/1522794708.46-7e01df35aa4e44eebdb04fcbe4503809.tgz]
Created [https://cloudbuild.googleapis.com/v1/projects/pubrobots/builds/79eda836-2f62-4b67-89d8-6d4f582a1567].
Logs are available at [https://console.cloud.google.com/gcr/builds/79eda836-2f62-4b67-89d8-6d4f582a1567?project=133031313439].
--------------------------------------------------------------------------------------------------- REMOTE BUILD OUTPUT ----------------------------------------------------------------------------------------------------
starting build "79eda836-2f62-4b67-89d8-6d4f582a1567"

FETCHSOURCE
Fetching storage object: gs://pubrobots_cloudbuild/source/1522794708.46-7e01df35aa4e44eebdb04fcbe4503809.tgz#1522794710151746
Copying gs://pubrobots_cloudbuild/source/1522794708.46-7e01df35aa4e44eebdb04fcbe4503809.tgz#1522794710151746...
/ [1 files][  2.6 KiB/  2.6 KiB]                                                
Operation completed over 1 objects/2.6 KiB.                                      
BUILD
Starting Step #0
Starting Step #1
Step #0: Already have image (with digest): gcr.io/cloud-builders/docker
Step #1: Already have image (with digest): gcr.io/cloud-builders/docker
Step #1: Sending build context to Docker daemon  18.43kB
Step #0: Sending build context to Docker daemon  18.43kB
Step #1: Step 1/12 : ARG BASE_IMAGE=gcr.io/cloud-builders/javac:8
Step #1: Step 2/12 : FROM ${BASE_IMAGE}
Step #0: Step 1/12 : ARG BASE_IMAGE=gcr.io/cloud-builders/javac:8
Step #0: Step 2/12 : FROM ${BASE_IMAGE}
Step #0: manifest for gcr.io/pubrobots/javac:8 not found
Step #1: manifest for gcr.io/pubrobots/javac:8 not found
Finished Step #0
Finished Step #1
ERROR
ERROR: build step 0 "gcr.io/cloud-builders/docker" failed: exit status 1
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

ERROR: (gcloud.container.builds.submit) build 79eda836-2f62-4b67-89d8-6d4f582a1567 completed with status "FAILURE"

**Comment by ImJasonH** [comment]
That's an unfortunate bug. You need to build the javac images in your project first. I'll update the docs.

**Comment by ludoch** [comment]
Same for gradle

**Comment by ankushchadha** [comment]
The fix as mentioned is to build https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/javac first i.e. ```git clone https://github.com/GoogleCloudPlatform/cloud-builders && cd cloud-builders/javac && gcloud container builds submit --config=cloudbuild.yaml .```

**Comment by bendory** [comment]
closing as resolved / obsolete
see also: https://github.com/GoogleCloudPlatform/cloud-builders/issues/665
