### ISSUE TITLE
Docker builder does not copy correctly folder symlinks

### ISSUE THREAD

**Issue by jpgriffo** [GoogleCloudPlatform/cloud-builders#251]
When using docker in standalone this issue does not arrise but when using cloudbuilder seems that it does not copy correctly folder thus breaking internal symlinks.

Please run example with docker and cloudbuilder and you will see that the folder _/example/broken/level2/good_ is inconsistent.

[example.tar.gz](https://github.com/GoogleCloudPlatform/cloud-builders/files/1895503/example.tar.gz)

**Comment by vrobert78** [comment]
Hi, I confirm, i have the same issue.

**Comment by bendory** [comment]
Closing as off-topic; questions and issues with the hosted Google Cloud Build service should be raised with Google Cloud Support or filed in the [public issue tracker](https://issuetracker.google.com/issues/new?component=190802&template=1162743).
