### ISSUE TITLE
Add a helm cloud-builder image

### ISSUE THREAD

**Issue by wstrange** [GoogleCloudPlatform/cloud-builders#254]
We can use helm via a wget, but an out of box helm image would be nice.

**Comment by bendory** [comment]
There is a community builder for helm here: https://github.com/GoogleCloudPlatform/cloud-builders-community/tree/master/helm

Once you build that, it ought to work for you out of the box.

**Comment by wstrange** [comment]
Fair nuff - but it would be nice if this was built and available on gcr.io/cloud-builders/gcloud
;-)

**Comment by andrewmclagan** [comment]
Yeah, also has anyone noticed that the built image for this "builder" is 1Gb + 

.....???!!!

**Comment by ImJasonH** [comment]
@andrewmclagan it's based on the gcloud image which is large because it contains all the optional components, but helm only needs kubectl (I think).

It should be possible to shrink the image by instead installing kubectl directly on an OS image.

**Comment by andrewmclagan** [comment]
Yeah, although i guess its easier to auth kubectl with gcp having gcloud present
