### ISSUE TITLE
Docker builder fails to copy folder and contents

### ISSUE THREAD

**Issue by ekoome** [GoogleCloudPlatform/cloud-builders#258]
Expected behaviour:
gcloud container builds submit context.tar.gz --tag="gcr.io/my-project/api:latest"

The context.tar.gz contains the folders to copy from.

Docker COPY command should copy folder and contents to docker image.

Actual behaviour:

Step 2/7 : COPY bin /app/bin
COPY failed: stat /var/lib/docker/tmp/docker-builder232188484/bin: no such file or directory

Information:
Confirmed that the folder is part of context generated (context.tar.gz) but unable to COPY the folder and contents using COPY command.
> gcloud --version                                     
Google Cloud SDK 197.0.0                               
beta 2017.09.15                                        
bq 2.0.31                                              
core 2018.04.06                                        
gsutil 4.30                                            
Operating system: Windows 10

Docker File:

FROM node:8.6.0-alpine

COPY bin /app/bin
COPY build /app/build
COPY package.json npm-shrinkwrap.json /app

WORKDIR /app

RUN npm install

CMD ["npm", "start"]

Steps to reproduce the behavior
1) create basic project with folder
2) copy folder and contents to Cloudbuilder docker context

**Comment by Philmod** [comment]
Hey Eric,

When you do `gcloud container builds submit context.tar.gz --tag="gcr.io/my-project/api:latest"`, you only send the file `context.tar.gz` to the builder, thus there is no directory `bin`. You may want to use `.` instead to include all your local files.

As an unrelated advice, you should copy the `package.json` *before* your code, as the latter will probably change more often, thus forcing an `npm install` even if there is no change in the dependencies.

Best,
Philippe

**Comment by ekoome** [comment]
Thanks Phillips.

Does “COPY .    /app” maintain folder structure in the context.tar.gz?

I have two folders bin & build with files within the context file, hence need to maintain folder structure for the app to run.

**Comment by Philmod** [comment]
I prefer to refer to Docker documentation for this question: https://docs.docker.com/engine/reference/builder/#copy

**Comment by ekoome** [comment]
Figured out the problem is that the context is generated from windows and files are extracted as folder\folder\file. How do I force the context to unix format?

**Comment by Philmod** [comment]
If you use the `gcloud container builds submit .` command, it should do the archive for you.
