### ISSUE TITLE
Image layer is 750MB

### ISSUE THREAD

**Issue by pwittrock** [GoogleCloudPlatform/cloud-builders#259]
> 28c178f40499: Downloading [====>                                              ]  67.91MB/759.7MB

What is in this layer and why is it so large?  The whole image should be relatively small.

**Comment by palmerj3** [comment]
Most of these cloud builders are based off debian or ubuntu so it's likely that

**Comment by Philmod** [comment]
Yes, @palmerj3 is correct.

You should know that all the cloud-builders are cached on the workers.

**Comment by ImJasonH** [comment]
Which layer are you referencing? That seems unusually large even for a base layer.
