### ISSUE TITLE
Update npm to 6.0.0 (untie npm from node version)

### ISSUE THREAD

**Issue by victorandree** [GoogleCloudPlatform/cloud-builders#263]
Thanks for accepting my [PR](https://github.com/GoogleCloudPlatform/cloud-builders/pull/262) to upgrade node to 10.0.0!

My original motivation for submitting it was actually to update npm to 6.0.0, but it seems like 5.6.0 is the version bundled with node@10.0.0 (seems like it was supposed to be 5.8.0 but that change was reverted...). According to the announcement for node 10, "[npm version 6 coming to Node.js 10.x release line](https://medium.com/the-node-js-collection/the-node-js-project-introduces-latest-release-line-node-js-10-x-bf07abfa9076#fae7)". 

Getting npm to at least 5.7.1 would be very nice because it enables `npm ci` which is obviously quite relevant for Google Container Builder. You'll get there eventually, but maybe it would make sense to separate node version from npm version? It *should* be as simple as modifying the Dockerfile along these lines:

1. Add `ARG NPM_VERSION`
2. Add `RUN npm install -g npm@${NPM_VERSION}` after installing node

That said, using whichever `npm` version a particular node version bundles might be more predictable.

**Comment by palmerj3** [comment]
@victorandree I think the primary thing folks are interested in is the node version and if we go with a multivariate system I fear we would have to publish dozens of images in order to have all combinations of npm/node.

What I would recommend, instead, is for folks to use npm to install the version of NPM they require and invoke ./node_modules/.bin/npm in actions that require npm.

**Comment by victorandree** [comment]
@palmerj3 I think that's a swift and fair response :)

**Comment by nakleiderer** [comment]
Sorry to bump an old issue.

@palmerj3 Could you provide or point me to an example of your recommendation? I've posted a question on Stackoverflow so others can find solutions also: https://stackoverflow.com/questions/51639664/custom-or-latest-npm-version-in-google-cloud-builder
