### ISSUE TITLE
Docker version in javac image

### ISSUE THREAD

**Issue by Simon3** [GoogleCloudPlatform/cloud-builders#264]
Hello, 

It would be nice if you could update the Docker version of **gcr.io/cloud-builders/javac**. The one currently used is 17.06.0-ce (2017-06-28), almost one year old, and I've just encountered a bug with .dockerignore that got fixed in the 17.07.0 version. 

Thanks in advance!

**Comment by bendory** [comment]
Thanks for the bug report; we apparently missed this at the time of our last Docker upgrade. Stay tuned here for a PR...

**Comment by bendory** [comment]
@Simon3 I expect this upgrade to rollout as part of our Monday release. In the meantime, if you are blocked by this issue, you can build your own `javac` image using the [master branch](https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/javac) and use that image in your builds.

**Comment by Simon3** [comment]
Sweet, thanks!
