### ISSUE TITLE
Fetch npm package from private github or google repo.

### ISSUE THREAD

**Issue by DocBradfordSoftware** [GoogleCloudPlatform/cloud-builders#27]
npm allows you to fetch node_modules directly from a github private repo.
```
"dependencies": {
    "express": "4.14.0",
    "privatepackage": "git+https://github.com/myaccount/privatepackage.git"
  }
```
Is there a way in builder to access either github or if I mirror the repo at google.
```
    "privatepackage": "https://source.developers.google.com/p/$PROJECT_ID/r/privatepackage"
```

How would I pass credentials?

**Comment by bendory** [comment]
The easiest and most secure way to do this at this time is to set up a [Google Cloud Source Repository](https://cloud.google.com/source-repositories/), which allows you to [connect your existing GitHub repository](https://cloud.google.com/source-repositories/docs/connecting-hosted-repositories)  for mirroring.

You can then pull from your Cloud Source Repository for your builds.

Also note that we support [Build Triggers](https://cloud.google.com/container-builder/docs/creating-build-triggers) which allow you to enable an automatic build that triggers on changes to the Git repo.

**Comment by DocBradfordSoftware** [comment]
I have a "hack" not what I would call a "solution" to this problem.  It involves,
   1. Make a copy of package.json
   2. Download private repo, using either gcloud builder or git buider.
   3. remove private repo from package.json
   4. run npm install.
   5. copy private repo to node_modules.
   6. run npm rebuild.
   7. build image.

It's not elegant.

**Comment by Philmod** [comment]
Hey!

We don’t have an integrated solution as of today, but here are a few solutions coming from users: 
1. Create a [Github token with “repo” scope](https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/), then use this syntax in the `package.json`:

```"my-private-module": "git+https://<github_token>:x-oauth-basic@github.com/<user>/<repo>.git"```

2. Use a Deploy or User Key that you could store in GCS for example, and pull it as a previous build step.

I hope this helps.

**Comment by DocBradfordSoftware** [comment]
Thanks, @Philmod, the only problem with that approach, is that if you don't commit the url including the github token to GitHub, you will have to do some kind of "sed" like replacement in package.json.  You would have to do it both on the developer side and the builder side, or .gitignore package.json and copy package.json.builder to package.json, all of which is messy.  I think i'll need to do the same thing that i did with kubectl bring the git auth in from GCS and configure git.  Like it is on my dev box.

**Comment by bendory** [comment]
This newly-published doc on [Using Encrypted Files](https://cloud.google.com/container-builder/docs/tutorials/using-encrypted-files) in your build should be helpful.

**Comment by DocBradfordSoftware** [comment]
Wow, thanks @bendory, that is simple and effective.  Way better than storing the account.json file in gs//.

**Comment by bendory** [comment]
Great! So glad you like it!
Shall we close this issue?

**Comment by bendory** [comment]
I'm closing this issue with the assumption that our doc on [Using Encrypted Files](https://cloud.google.com/container-builder/docs/tutorials/using-encrypted-files) resolves this issue. Please re-open if that does not provide you with what you need.
