### ISSUE TITLE
Creating trigger for github repo in different org

### ISSUE THREAD

**Issue by magiconair** [GoogleCloudPlatform/cloud-builders#272]
Hi,

I am trying to create a trigger for a github project that is in a different github org where I am owner but the UI won't list the repositories. For example, I'm logged in as magiconair and see all magiconair/* repos but not the fabiolb/* repos of which I'm also the owner. 

What am I missing?

**Comment by pdeslaur** [comment]
Could you verify if the Google Cloud Platform OAuth app in GitHub has organization access to fabiolb/* ?

You should be able to verify the configuration here: https://github.com/settings/connections/applications/70087bd6f8a55ecca2a1

**Comment by magiconair** [comment]
Yes, that fixed it. Thanks a lot.
