### ISSUE TITLE
Create Trigger never completes

### ISSUE THREAD

**Issue by magiconair** [GoogleCloudPlatform/cloud-builders#273]
I am trying to create a trigger to a private github repo but that operation never completes. If I restart the process I get

```
Your repository is connected and is being mirrored. You will be redirected to the trigger settings when the operation is complete.
```

and a `Restart triggering` button. When I click it the operation fails after some time with

```
Error
The server failed to process your request because of a conflicting operation. Please try again.

Tracking Number: 237654312441451591
```

The github repo has a deploy key and a webhook and removing both before retrying the operation does not help. 

Any idea what is going on?

**Comment by pdeslaur** [comment]
An internal Google service was having an issue yesterday - I think you were affected. Are you still having problems today?

**Comment by magiconair** [comment]
No, it worked today.
