### ISSUE TITLE
dotnet builder image is ~4GB

### ISSUE THREAD

**Issue by ImJasonH** [GoogleCloudPlatform/cloud-builders#274]
```
$ docker images gcr.io/cloud-builders/dotnet
REPOSITORY                     TAG                 IMAGE ID            CREATED             SIZE
gcr.io/cloud-builders/dotnet   latest              bf60661b4ca6        5 hours ago         3.56GB
```

It looks like most of this bulk comes from the topmost two layers, created by [these directives](https://github.com/GoogleCloudPlatform/cloud-builders/blob/2b3b8f0c9406803f1c23d649c0af0f17c505da8c/dotnet/Dockerfile#L31):

```
# Make sure that the caches are expanded.
ADD ./configs /configs
RUN cd /configs/config-1.0.0/ && dotnet new && \
    cd /configs/config-1.1.7/ && dotnet new && \
    cd /configs/config-2.1.4/ && dotnet new && \
    rm -rf /configs
```

I'd like to learn more about why this step is necessary, and whether we can reduce the size of this image. Since we cache it on each worker VM, that's effectively taking up disk space that would otherwise be useable by users' builds. We can increase workers' disk size, but that increases cost to run.

Some questions about this image:

* Does every version of the `dotnet` builder need all of those SDKs installed?
* Would the image work (if slower) if we did not "expand" the caches?
* The `ADD ./configs configs` followed by `rm -rf /configs` effectively adds ~300 MB to the _compressed_ image size, since the `rm -rf` only whites out the `/configs` directory; that data is still present in the final image layers -- can we optimize this to remove unnecessary bloat?
* Is usage of the `dotnet` builder significant enough that removing it from the cache would harm a significant share of users?

/cc @ivannaranjo

**Comment by ILMTitan** [comment]
1. If we want to support building projects that target older .NET Core runtimes (1.0.0-preview and 1.x) , we do need all three SDKs.
2. Yes, the image would need to initialize the cache on each first run of the newly deployed image, but they would work.
3. Each of the 3 **/configs/*** directories has a single file of under 100 bytes. How does that add 300MB!?
4. It might be reasonable to only expand the cache of the latest SDK.

**Comment by cbuchacher** [comment]
The image also contains 1.5G worth of packages in `/root/.nuget/packages`.

```
$ docker run --entrypoint bash --rm -it gcr.io/cloud-builders/dotnet
root@5394d5f5acf3:/# du -chs /root/.nuget/packages
1.5G    /root/.nuget/packages
1.5G    total
```

By default cloud builds will not use those since the HOME directory for the cloud builder is `/builder/home`:

```
Step #0: + echo HOME: /builder/home
Step #0: HOME: /builder/home
Step #0: + ls -a /builder/home
Step #0: .
Step #0: ..
Step #0: .docker
Step #0: + ls -a /builder/home/.nuget/packages
Step #0: ls: cannot access '/builder/home/.nuget/packages': No such file or directory
```

Cloud build script:

```
#!/bin/sh
set -x
echo "HOME: $HOME"
ls -a $HOME
ls -a $HOME/.nuget/packages
```

**Comment by bendory** [comment]
closing as obsolete https://github.com/GoogleCloudPlatform/cloud-builders/issues/663
