### ISSUE TITLE
Add official golang/dep cloud builder

### ISSUE THREAD

**Issue by christian-roggia** [GoogleCloudPlatform/cloud-builders#275]
As discussed during KubeCon there is a strong necessity of adding a [golang/dep](https://github.com/golang/dep) cloud builder to your suite of builders. Checking dependencies status is vital to the CI/CD process and it should be fully supported by your platform.

The golang/dep tool is ready for production use and it is the official experiment and package manager for Golang applications (see [README](https://github.com/golang/dep/blob/master/README.md) for more information):
> dep is safe for production use.
> dep is the official experiment, but not yet the official tool. 

Waiting for this tool to be merged inside the official Golang toolchain is in my opinion not an option as it could take one more year or even more.

The previous request #62 for support of this package manager was rejected with the following reason:
> I'm somewhat -1 on providing official support for this tool while it's not officially supported by the Go team, and is likely to change in breaking ways in the future.

but since then it has become stable and has been adopted by many major players of the Golang ecosystem.

We are using Google Container Cloud Builder for almost the entire CI/CD process of the Golang Stack inside our company and we are currently using a custom dep image for the pipeline, we would **REALLY** appreciate to finally see an official (and probably better structured than mine) cloud builder.

**Comment by christian-roggia** [comment]
cc @Philmod

**Comment by Philmod** [comment]
Hey @skelterjohn , what do you think about it?

**Comment by ImJasonH** [comment]
This should be a community builder alongside the glide builder.

**Comment by ImJasonH** [comment]
Closing in favor of https://github.com/GoogleCloudPlatform/cloud-builders-community/issues/60
