### ISSUE TITLE
Add support for dotnet core 2.1 build

### ISSUE THREAD

**Issue by Andrioden** [GoogleCloudPlatform/cloud-builders#288]
[ASP.Net Core 2.1 was just officialy released](https://blogs.msdn.microsoft.com/dotnet/2018/05/30/announcing-net-core-2-1/). After i upgraded my ASP.Net project to 2.1, i am not longer able to use your cloud-build tool dotnet to automatically run my tests. It seems to be confirmed by [your documentation](https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/dotnet) that it is not yet supported.

`gcr.io/cloud-builders/dotnet test [my-dotnetcore2.1-project]`

gives

/usr/share/dotnet/sdk/2.1.4/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.TargetFrameworkInference.targets(135,5): error : The current .NET SDK does not support targeting .NET Core 2.1.  Either target .NET Core 2.0 or lower, or use a version of the .NET SDK that supports .NET Core 2.1. [/workspace/[MyProject].Tests/[MyProject].Tests.csproj]

**Comment by bendory** [comment]
@ivannaranjo PTAL
