### ISSUE TITLE
local container build runs and remote fails

### ISSUE THREAD

**Issue by sebgoa** [GoogleCloudPlatform/cloud-builders#293]
Hi,

I am playing with CB and quickly I got into a problem where:

```
$ container-builder-local --dryrun=false .
2018/06/18 15:07:36 Warning: The server docker version installed (18.05.0-ce) is different from the one used in GCB (17.12.0-ce)
2018/06/18 15:07:36 Warning: The client docker version installed (18.05.0-ce) is different from the one used in GCB (17.12.0-ce)
Using default tag: latest
...
```

Does build my image locally just fine,

but the remote build job setup as a "build trigger" fails with some application specific error.

The `cloudbuild.yaml` looks like:

```
# Build new image of frontend
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/.../app', '--no-cache', '.']
```

Any suggestion ?

**Comment by Philmod** [comment]
Hey @sebgoa ,

I would need more information to be able to help you.

A few questions: 
1. Did you try to use the same docker version locally (by downgrading to 17.12.0-ce)?
2. Did you try cleaning your local cache (mostly `docker images`)?
3. What is the error?

You could join the "cloudbuild" Slack channel if you want to chat directly with us. https://gcp-slack.appspot.com/

Cheers,
Philmod

**Comment by sebgoa** [comment]
ok, I joined slack.

I deleted all my images :( and build again locally => success.

Downgrading to 17.12.0-ce is a bit of a pain.

**Comment by sebgoa** [comment]
Figured it out.

turns out Mac file system is case insensitive. I had a problem in my git repo structure where a some files got into a directory with a lower case instead of a caps.

locally on Mac, they all appeared in the same directory but remotely during the GCB build they wherein different directories and the build failed complaining it was missing files.

see: https://stackoverflow.com/questions/18000138/duplicated-file-with-different-case-in-git-origin-bitbucket

**Comment by bendory** [comment]
Possibly related to https://github.com/GoogleCloudPlatform/cloud-builders/issues/142#issuecomment-398047905 ?
