### ISSUE TITLE
Cache m2 repo when building with maven image

### ISSUE THREAD

**Issue by hemikak** [GoogleCloudPlatform/cloud-builders#301]
Hi All,

I am using the maven image to build my maven artifacts. Is there a way to persist to m2 repository of maven once the build is complete. Each time I run the build it downloads all the dependency jars from maven central which takes a long time.

Regards,
Hemika

**Comment by bendory** [comment]
https://github.com/GoogleCloudPlatform/cloud-builders/issues/665
