### ISSUE TITLE
gcr.io/cloud-builders/git with `git push` fails

### ISSUE THREAD

**Issue by limscoder** [GoogleCloudPlatform/cloud-builders#310]
I'm extending the gcr.io/cloud-builders/git image and trying to push with the following command:

`git push origin HEAD:master`

The command fails with the following error:

`fatal: could not read Username for 'https://github.com': No such device or address`

**Comment by ImJasonH** [comment]
This error message indicates that you don't have any authentication set up to push to GitHub.

See https://cloud.google.com/cloud-build/docs/access-private-github-repos for more information about authorizing with GitHub using an encrypted secret.

**Comment by limscoder** [comment]
So I need a different auth config than what CloudBuilder uses to pull changes?

**Comment by ImJasonH** [comment]
When you set up builds from GitHub, GCB actually mirrors your code from GitHub to a location that your project's [builder service account](https://cloud.google.com/cloud-build/docs/securing-builds/set-service-account-permissions) (named like `PROJECT_NUM@cloudbuild.gserviceaccount.com`) can access it, which is where it pulls from when it runs the build. The builder service account doesn't have direct access to your GitHub repo by default, and needs an encrypted secret to be able to push changes to your GitHub repo.

**Comment by limscoder** [comment]
Ok, seems like the docs need some work to explain how to setup that up.
