### ISSUE TITLE
Are windows based containers supported in Google Cloud Build?

### ISSUE THREAD

**Issue by artisticcheese** [GoogleCloudPlatform/cloud-builders#314]
I was unable to find an answer and I suspect answers i no but checking anyway.

**Comment by bendory** [comment]
Windows containers are not natively supported at this time. We do have a supported [dotnet builder](https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/dotnet) and a community-contributed [fsharp builder](https://github.com/GoogleCloudPlatform/cloud-builders-community/tree/master/fsharp), but we do not execute native Windows workloads.

Some users are using a [remote builder](https://github.com/GoogleCloudPlatform/cloud-builders-community/tree/master/remote-builder) to execute on a Windows VM at build-time.
