### ISSUE TITLE
mvn builder does not work in local mode

### ISSUE THREAD

**Issue by yonimoses** [GoogleCloudPlatform/cloud-builders#316]
Trying to run cloud-builder mvn locally doesn't seem to work cause of some network issues.
Running the same code on the cloud does work.
Any suggestions ?
    
    
    `Starting Step #0 - "server-package"
    Step #0 - "server-package": Already have image (with digest): gcr.io/cloud-builders/mvn
    Step #0 - "server-package": [INFO] Scanning for projects...
    Step #0 - "server-package": [INFO] Downloading: https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-starter-parent/2.0.4.RELEASE/spring-boot-starter-parent-2.0.4.RELEASE.pom
    Step #0 - "server-package": [ERROR] [ERROR] Some problems were encountered while processing the POMs:
    Step #0 - "server-package": [FATAL] Non-resolvable parent POM for com.cvfox:server:1.0.1: Could not transfer artifact org.springframework.boot:spring-boot-s
    Step #0 - "server-package": tarter-parent:pom:2.0.4.RELEASE from/to central (https://repo.maven.apache.org/maven2): repo.maven.apache.org: Temporary failure in name resolution and 'parent.relativePath' points at no local POM @ line 5, column 13
    Step #0 - "server-package":  @ 
    Step #0 - "server-package": [ERROR] The build could not read 1 project -> [Help 1]
    Step #0 - "server-package": [ERROR]   
    Step #0 - "server-package": [ERROR]   The project com.cvfox:server:1.0.1 (/workspace/server/pom.xml) has 1 error
    Step #0 - "server-package": [ERROR]     Non-resolvable parent POM for com.cvfox:server:1.0.1: Could not transfer artifact org.springframework.boot:spring-bo
    Step #0 - "server-package": ot-starter-parent:pom:2.0.4.RELEASE from/to central (https://repo.maven.apache.org/maven2): repo.maven.apache.org: Temporary fai
    Step #0 - "server-package": lure in name resolution and 'parent.relativePath' points at no local POM @ line 5, column 13: Unknown host repo.maven.apache.org
    Step #0 - "server-package": : Temporary failure in name resolution -> [Help 2]`

**Comment by meltsufin** [comment]
`Unknown host repo.maven.apache.org` might be the clue. Can you try `ping repo.maven.apache.org` on your local machine?

**Comment by yonimoses** [comment]
Ping works on my machine, that's why I find it strange.. I've also changed the repositories to repo.spring and some other repo, all came back with the same issue.

**Comment by meltsufin** [comment]
Can you give all the steps for reproducing the issue?

**Comment by yonimoses** [comment]
Just tried it again, and it's working now!
I've tried running it with another docker mvn image, it didn't work there on the same issue, which led me to believe it's not a gcp-build-mvn issue.
I've also deleted all the dockers from my machine in the past few days, and I've re-downloaded them all again now , so maybe that's related..

**Comment by bendory** [comment]
obsolete / resolved; closing
