### ISSUE TITLE
Lookahead regex not supported, not reflected in UI

### ISSUE THREAD

**Issue by ksiemens-va** [GoogleCloudPlatform/cloud-builders#330]
When creating a build trigger, filtering by regex does not support lookahead operations. This is not reflected in the UI, where they appear as though they should work.

For example, if we make a build trigger for every branch except for `master` using the regex `^(?!master$).*` it will accept the regex and appear to filter out the master branch, however we can not trigger a build with this because the negative lookahead operation is not supported by Golang and a `Invalid regex ^(?!master$).*: error parsing regexp: invalid or unsupported Perl syntax: '(?!\'` is shown.

Lookaheads and other unsupported regex operations not supported by golang should prompt the user that this regex is invalid before trying to use it.

![image](https://user-images.githubusercontent.com/30698254/43861187-4bebafbc-9b13-11e8-9f1d-a44e831e7976.png)
![image](https://user-images.githubusercontent.com/30698254/43861079-fa744838-9b12-11e8-8814-b23d4b8875b9.png)

**Comment by Philmod** [comment]
The golang regexp is used, and doesn't support lookahead. https://golang.org/pkg/regexp/

**Comment by ksiemens-va** [comment]
Thanks. I'm aware that it doesn't support lookahead, but this is not conveyed to the user before attempting to use it.

**Comment by Philmod** [comment]
I opened an internal bug, that's for the report!

**Comment by MPV** [comment]
Related to this, how do I specify "all other branches than master"?

**Comment by ksiemens-va** [comment]
@MPV We've been using the regex `[^master]` which works just as long as you make sure branches contain characters other than those in `matser` (i.e if you name your branch `smartass` it won't pass). 
Our branch naming convention is such that we're basically guaranteed to have other characters than just those, so this solution (while not _ideal_) does work for us.
