### ISSUE TITLE
gcr.io/cloud-builders/go: Go 1.11

### ISSUE THREAD

**Issue by mbana** [GoogleCloudPlatform/cloud-builders#332]
Hi, are there any plans to support Go 1.11 beta? From what I understand this is due for release in August 31, 2018.

**Comment by ImJasonH** [comment]
The go builder is `FROM golang` so as soon as that image is updated to install 1.11 the builder will use that version too.

**Comment by abhigenie92** [comment]
How do you specify the version, it is different from golang.
For golang, this works.
`docker run golang:1.12.6`
But it doesn't work for `docker run  gcr.io/cloud-builders/go:1.12.6`
