### ISSUE TITLE
Support Docker CMD instruction

### ISSUE THREAD

**Issue by sabrehagen** [GoogleCloudPlatform/cloud-builders#333]
Currently the [cloudbuild format](https://cloud.google.com/cloud-build/docs/build-config#structure_of_a_build_config_file) only supports the `ENTRYPOINT` instruction, but not `CMD`.

It is common to set an `ENTRYPOINT` in a Dockerfile to execute an initialization script, then use `CMD` to execute the desired command.

From the [Docker docs](https://docs.docker.com/engine/reference/builder/#understand-how-cmd-and-entrypoint-interact):

> CMD should be used as a way of defining default arguments for an ENTRYPOINT command or **for executing an ad-hoc command in a container**.

Can `CMD` be supported in the cloudbuild spec so that this workflow can be achieved?

**Comment by bendory** [comment]
closing as off-topic; questions and issues with the hosted Google Cloud Build service should be raised with Google Cloud Support or filed in the [public issue tracker](https://issuetracker.google.com/issues/new?component=190802&template=1162743).
