### ISSUE TITLE
email notifications on CI builds for PR authors

### ISSUE THREAD

**Issue by nhooyr** [GoogleCloudPlatform/cloud-builders#338]
Would be really cool to open up a PR and then get a notification if my build failed/passed.

**Comment by bendory** [comment]
This GitHub issue tracker is intended for bugs with the officially supported builder images specifically.
Please report issues and feature requests regarding the GCB service to our public issue tracker at
https://issuetracker.google.com/issues/new?component=190802&template=1162743
