### ISSUE TITLE
Docker builder fails to access GCP Cloud Source Repos

### ISSUE THREAD

**Issue by YaguraStation** [GoogleCloudPlatform/cloud-builders#343]
The [Docker builder](https://github.com/GoogleCloudPlatform/cloud-builders/blob/master/docker/README.md) uses the [Cloud Build Service Account](https://cloud.google.com/cloud-build/docs/permissions) which in turn should have sufficient rights to _[fetch code from your project's Cloud Source Repository](https://cloud.google.com/cloud-build/docs/securing-builds/set-service-account-permissions)_. 

But when specifying `RUN pip install git+https://source.developers.go...` in Dockerfile the resulting `git clone -q ...` fails in the logs with error code 128 and previously claiming the following: 

_fatal: could not read Username for 'https://source.developers.google.com': No such device or address_

Using GitHub with token instead of GCP Cloud Source Repositories works successful in this way. A self-maintained repo within GCP as well.

**Comment by ImJasonH** [comment]
Try adding `--network=cloudbuild` to your `docker build` step args. That should pipe the builder service account creds into the Docker build environment.

**Comment by YaguraStation** [comment]
Thanks for the quick answer. I just tested it now and checked in the console's Build History log that `--network=cloudbuild` was picked up as argument. Which it did, but it errored out in the same fashion

```
Collecting git+https://source.developers.google.com/p/labs-honigwachs-de/r/co
Cloning https://source.developers.google.com/p/labs-honigwachs-de/r/co to /tmp/pip-req-build-QyyVeD
fatal: could not read Username for 'https://source.developers.google.com': No such device or address
Command "git clone -q https://source.developers.google.com/p/labs-honigwachs-de/r/co /tmp/pip-req-build-QyyVeD" failed with error code 128 in None
The command '/bin/sh -c pip install git+https://source.developers.google.com/p/labs-honigwachs-de/r/co' returned a non-zero code: 1
ERROR
ERROR: build step 0 "gcr.io/cloud-builders/docker" failed: exit status 1
```

**Comment by ImJasonH** [comment]
The docker builder doesn't install the Git credential helper, which is installed through gcloud. It sounds like you're building an image `FROM gcr.io/cloud-builders/docker` that also installs `pip` and `git`, since neither are installed in the docker image by default. You should probably install and setup the credential helper too, like we do [in the `git` builder](https://github.com/GoogleCloudPlatform/cloud-builders/blob/master/git/Dockerfile#L5).

**Comment by YaguraStation** [comment]
From the tests, **both** things seem to be necessary: (1) setting up the credential helper, and (2) using `--network=cloudbuild` as an argument. We can now interact with the GCP Cloud Source Repo. 

Thanks for your help! And it might be useful to have this info in one the articles linked in my initial filing.

**Comment by jankrynauw** [comment]
Building the dockerfile locally gave me the following error:
<img width="960" alt="screen shot 2018-08-24 at 22 52 48" src="https://user-images.githubusercontent.com/18016598/44607553-1cfb7a80-a7f1-11e8-8d67-c5b288ffb904.png">

In Cloud Build, is the gcloud automatically initiated, i.e. credentials are already obtained?

**Comment by YaguraStation** [comment]
So, from my earlier research only when using `--network=cloudbuild` in _cloudbuild.yaml_ as an build argument, the credentials of the Cloud Build Service Account within the project. In turn and only then that service account is already by inheritance of its role allowed to read the GCP project Cloud Source Repositories. 

In short I believe the your error will vanish when using `--network=cloudbuild`.

**Comment by jankrynauw** [comment]
Unless I'm not understanding, cloudbuild.yaml does't play a role in local testing environment.  Therefore not sure how --network=cloudbuild will assist with local testing.

I guess one way is to, if running locally, to pass the local credentials manually:
`docker run --rm -it -v ~/.config/gcloud:/.config/gcloud google/cloud-sdk`
Its just not a super elegant way to test locally.

**Comment by YaguraStation** [comment]
`--network=cloudbuild` is a build argument for building the Docker image with `docker build` in Cloud Build. Docker image builds triggered within Cloud Build (or with `gcloud builds`) respect the additional arguments in _cloudbuild.yaml_. In general, outside of GCP, `docker build --network` sets the networking mode for the RUN instructions during build. 

The _Dockerfile_ includes instructions for the build process itself, including the `pip install git+ ...`. In Cloud Build, when using the above mentioned argument in the following manner, the service account is used as expected [and documented](https://cloud.google.com/cloud-build/docs/securing-builds/set-service-account-permissions). Without, auth has to be configured. 
```
steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '--network=cloudbuild', ...
```
So once Cloud Build has built the Docker image including the Python package from Cloud Repositories and stored the image in Google Container Registry (gcr.io), then one can use `docker run` to run a container based on that image... in GCP or locally. 

To have the local Docker installation interact with GCR for testing purposes, you'd need to `gcloud auth configure-docker` first. After that, specifying images from gcr.io with `docker pull` and `docker run` should work.

**Comment by jankrynauw** [comment]
excellent, thank you this makes sense

**Comment by Aravinviju** [comment]
> From the tests, **both** things seem to be necessary: (1) setting up the credential helper, and (2) using `--network=cloudbuild` as an argument. We can now interact with the GCP Cloud Source Repo.
> 
> Thanks for your help! And it might be useful to have this info in one the articles linked in my initial filing.

Hi, I'm trying to build the image in the cloud, the same way @YaguraStation you did, and for me the '--network=cloudbuild' is already in place.

But I'm not sure how to install and setup the credential helper part, in the git builder - how @imjasonh said.

I tried adding the commands in the Dockerfile as ,


FROM gcr.io/cloud-builders/gcloudCOPY notice.sh /usr/binENTRYPOINT ["/usr/bin/notice.sh"]

but I get the below error,
![image](https://user-images.githubusercontent.com/33582877/118490685-1ede9800-b716-11eb-8289-93dff980e283.png)

can anyone show an example of how this is to be done?

Thanks
Aravind

**Comment by Aravinviju** [comment]
> > From the tests, **both** things seem to be necessary: (1) setting up the credential helper, and (2) using `--network=cloudbuild` as an argument. We can now interact with the GCP Cloud Source Repo.
> > Thanks for your help! And it might be useful to have this info in one the articles linked in my initial filing.
> 
> Hi, I'm trying to build the image in the cloud, the same way @YaguraStation you did, and for me the '--network=cloudbuild' is already in place.
> 
> But I'm not sure how to install and setup the credential helper part, in the git builder - how @imjasonh said.
> 
> I tried adding the commands in the Dockerfile as ,
> 
> ![image](https://user-images.githubusercontent.com/33582877/118491023-7da41180-b716-11eb-9730-b365faccb926.png)
> 
> but I get the below error,
> ![image](https://user-images.githubusercontent.com/33582877/118490685-1ede9800-b716-11eb-8289-93dff980e283.png)
> 
> can anyone show an example of how this is to be done?
> 
> Thanks
> Aravind

Hi

Just for an update,
this build worked fine for me after adding,

FROM gcr.io/cloud-builders/gcloud
RUN git config --system credential.helper gcloud.sh

This initially gave an python version incompatible error as the first command gets python 2.7 and I needed python 3.6.

then I installed gcloud from scratch using the folloing command and the used the credential.helper command, this worked:

RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg  add - && apt-get update -y && apt-get install google-cloud-sdk -y

RUN git config --system credential.helper gcloud.sh


I also gave additional permissions to my cloud build SA:
1. Cloud Source Repositories Service Agent
2. Custom Source Repository Writer

Not sure, if that could ve made some changes too which made the build to work. I would suggest experimenting this if the above doesn't work.

Thnaks
Arav
