### ISSUE TITLE
Caching Bazel workspaces

### ISSUE THREAD

**Issue by ewhauser** [GoogleCloudPlatform/cloud-builders#350]
Is there documentation for how to cache your workspace between builds with Bazel? I found a [Stackoverflow question](https://stackoverflow.com/questions/46457170/how-to-speed-up-bazel-builds-on-google-cloud-platform) that discusses this, but it would be good to add this in the examples directory as a canonical way to setup your Bazel builds.

If you are using Bazel's remote caching, this will drastically speed up your speeds by not rebuilding artifacts every time but a significant portion of your build will be spent setting up the workspace.

**Comment by justinsb** [comment]
Related: https://github.com/GoogleCloudPlatform/cloud-builders/issues/276#issuecomment-396745464

**Comment by bendory** [comment]
closing as obsolete, reference https://github.com/GoogleCloudPlatform/cloud-builders/issues/667
