### ISSUE TITLE
Cannot use more than one project

### ISSUE THREAD

**Issue by Znax** [GoogleCloudPlatform/cloud-builders#355]
Hi,

If I use kubectl to perform actions on my cluster, it works fine as long as I use 1 project.
If I have 2 steps affecting different projects, it's not taking the second one.
I set up the CLOUDSDK_CORE_PROJECT variable (for both), but it sticks to the first one :(

**Comment by bendory** [comment]
This GitHub issue tracker is intended for bugs with the officially supported builder images specifically.
Please report issues and feature requests regarding the GCB service to our public issue tracker at
https://issuetracker.google.com/issues/new?component=190802&template=1162743
