### ISSUE TITLE
cloud-builders/npm/examples/hello_world example broken

### ISSUE THREAD

**Issue by alexamies** [GoogleCloudPlatform/cloud-builders#361]
I think that there is a problem with the npm example [cloudbuild.yaml](https://github.com/GoogleCloudPlatform/cloud-builders/blob/master/npm/examples/hello_world/cloudbuild.yaml). There is no README.md for the example, but I guess that the way to run it is 

gcloud builds submit --config cloudbuild.yaml .

When I try that I get errors like this

Starting Step #0
Step #0: Pulling image: gcr.io/{**My Project**}/npm
Step #0: Using default tag: latest
Step #0: Error response from daemon: manifest for gcr.io/{**My Project**}/npm:latest not found

Since I do not have a GCR image in my project  called npm. I think that cloudbuild.yaml should look like:

steps:
\- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
\- name: 'gcr.io/cloud-builders/npm'
  args: ['test']
\- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/hello_npm', '.']
images: ['gcr.io/$PROJECT_ID/hello_npm']

That would make more sense from a point of view of the example illustrating the npm builder, and it succeeds with the command above. I would be happy to submit a pull request with the change if it make sense to the project owners.

**Comment by bendory** [comment]
Thanks for catching this, and PRs are most certainly welcome!

**Comment by alexamies** [comment]
Created https://github.com/GoogleCloudPlatform/cloud-builders/pull/362
