### ISSUE TITLE
Build stuck at downloading Jacoco

### ISSUE THREAD

**Issue by Smedzlatko** [GoogleCloudPlatform/cloud-builders#365]
I have a cloudbuild yaml configuration file in several of my projects and it usually works very well. However in my latest project, I always exceed the build timeout because the build gets stuck at downloading certain dependency:

```
(Step #0 - "java-build": Download https://repo.maven.apache.org/maven2/org/jacoco/org.jacoco.agent/0.8.0/org.jacoco.agent-0.8.0.jar
Step #0 - "java-build": Download https://repo.maven.apache.org/maven2/org/jacoco/org.jacoco.build/0.8.0/org.jacoco.build-0.8.0.pom
Step #0 - "java-build": Download https://repo.maven.apache.org/maven2/org/jacoco/org.jacoco.agent/0.8.0/org.jacoco.agent-0.8.0.pom)
```

It is a docker image with Spring Boot application which contains `jacoco` plugin. For some reason, this build step always freezes at downloading this particular dependency. However, I can build the app locally and download this dependency manually so I doubt there is anything wrong with the repository.

Could someone help me out and suggest what shall I debug to find out the root cause of this issue?

This is my `Dockerfile`:

```
FROM gcr.io/distroless/java
VOLUME /tmp
ADD build/libs/*.jar app.jar
ENV JAVA_OPTS=""
ENTRYPOINT ["java","-jar","app.jar"]
```

and `cloudbuild.yml`:

```
steps:
- name: 'gcr.io/cloud-builders/java/gradle'
  id: 'java-build'
  args: ['build']
- name: 'gcr.io/cloud-builders/docker'
  id: 'docker-build'
  args: ['build', 
         '-t', 'eu.gcr.io/$PROJECT_ID/api-core:$COMMIT_SHA',
         '-t', 'eu.gcr.io/$PROJECT_ID/api-core:latest',
         '-f', 'Dockerfile', '.']
  waitFor: ['java-build']
- name: 'gcr.io/cloud-builders/docker'
  id: 'docker-push'
  args: ['push', 'eu.gcr.io/$PROJECT_ID/api-core:latest']
  waitFor: ['docker-build']
- name: 'gcr.io/cloud-builders/docker'
  id: 'docker-push-sha'
  args: ['push', 'eu.gcr.io/$PROJECT_ID/api-core:$COMMIT_SHA']
  waitFor: ['docker-build']

images:
- 'eu.gcr.io/$PROJECT_ID/api-core:$COMMIT_SHA'
- 'eu.gcr.io/$PROJECT_ID/api-core:latest'
```

**Comment by Smedzlatko** [comment]
I tried using `cloudbuild-local` and the build passes without any problem so it seems there is something wrong with the one in GCP.

**Comment by ImJasonH** [comment]
I don't know anything about Jacoco, but AFAIK we have no problem downloading Maven dependencies from https://repo.maven.apache.org. When you run locally, are you sure the package is being downloaded, and not pulled from a local cache? Maybe there's some problem reaching Jacoco in the remote repo?

**Comment by Smedzlatko** [comment]
Hi. I build locally without any cache and although it hangs for couple of seconds, this dependency is downloaded successfully. The download link from the log is valid. I am not sure whether this is the issue or whether there is something else going on behind the scenes. Is there a way how to run cloudbuild with some more detailed logs?

Or is there some significant difference between `cloudbuild` and `cloudbuild-local`?

**Comment by ImJasonH** [comment]
The relevant code is the same between the hosted service and the local runner, GCB runs your command in a container on the worker VM, with unimpeded network access out to the internet.

If you could attach a minimal build config that relies on jacoco and exhibits this behavior in GCB, that might help us debug it. You've provided your Dockerfile, but it looks like the error is happening before your `docker build` step, in running `gradle build`.

/cc @meltsufin in case he has any ideas about how to debug this.

**Comment by meltsufin** [comment]
I've also seen Maven builds get stuck on downloading deps on Travis. It's usually an intermittent network problem with Maven Central. Does Google have a mirror of Maven Central? That might work better if it exists.

**Comment by ImJasonH** [comment]
I believe Google does maintain a Maven Central mirror, I found docs here: https://storage-download.googleapis.com/maven-central/index.html

**Comment by Smedzlatko** [comment]
It seems that there is a problem with connection. If I remove Jacoco, it simply gets stuck on the following dependency. It's difficult to say why since there is nothing in the logs and everything works fine locally.

**Comment by bendory** [comment]
This GitHub issue tracker is intended for bugs with the officially supported builder images specifically.
Please report issues and feature requests regarding the GCB service to our public issue tracker at
https://issuetracker.google.com/issues/new?component=190802&template=1162743
