### ISSUE TITLE
docker: enable experimental commands

### ISSUE THREAD

**Issue by listx** [GoogleCloudPlatform/cloud-builders#367]
The motivation behind this is from a Kubernetes project (https://github.com/kubernetes/dns/commit/50149718d9859722aa1db4af2f4137ab74fa82d1) that would like to use the experimental `docker manifest` command. Currently we use version 17.12.0-ce of docker, which does not support this. According to https://docs.docker.com/release-notes/docker-ce/, the support for `docker manifest` was added in the 18.02 release.

The logic in https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/docker looks pretty straightforward for building the 3 different 17.x versions we have today, so I'll try creating a patch there.

**Comment by prameshj** [comment]
We need docker 18.06+ in order to build the images correctly - https://github.com/kubernetes/kubernetes/pull/68430#issuecomment-422991629

**Comment by listx** [comment]
As @prameshj said, we should support 18.06+ of docker CLI in order to build "fat" manifests (with the experimental `docker manifest` command) correctly.

There still remains a question though in how users of a hypothetical 18.06+ image would use it to run experimental commands.

Option 1: Experimental commands are disabled by default, and users have to write the config at runtime like this:
```
root@65a4552dc80f:~# mkdir .docker
root@65a4552dc80f:~# echo '{"experimental":"enabled"}' > ~/.docker/config.json
```
in order to call `docker manifest`.

Option 2: We have the above setting injected already when we build the 18.06+ image, so that experimental commands are always enabled. I would vote for having it enabled by default because, ultimately it's still up to the user if they want to use experimental subcommands. So, there's no "hidden action from a distance" magic happening here.

**Comment by codrienne** [comment]
I've noted your request to support Docker 18.06+ and enable experimental commands by default, though I'm not sure we should since they are [not ready for production](https://github.com/docker/docker-ce/tree/master/components/cli/experimental). At the very least, it would be helpful to document how to enable it.

**Comment by listx** [comment]
Going with Option 1 is fine too. Ultimately the difference between Option 1 vs 2 will go away on its own when docker manifests become first-class citizens (a year from now? 2 years?).

**Comment by listx** [comment]
Hmm actually to clarify, I suppose there will always be experimental Docker commands as other new ones pop up in the future.

In this case I think going with Option 1 is much saner. Where would we document the enabling of the experimental flag @codrienne ?

**Comment by prameshj** [comment]
Just to clarify, if we are going with option 1, would we be running an older docker version than 18.06? Then we still run into the incorrect manifest build problem right?
https://github.com/kubernetes/kubernetes/pull/68430#issuecomment-422991629

**Comment by bendory** [comment]
We are aware of that issue and plan to upgrade to 18.06+ when we upgrade.

**Comment by prameshj** [comment]
ok, thanks.

**Comment by leeonlee** [comment]
The upgrade to 18.06.1 has been completed.
