### ISSUE TITLE
Docker: support volume during build

### ISSUE THREAD

**Issue by matthewvalimaki** [GoogleCloudPlatform/cloud-builders#37]
`docker run -v` is supported but officially `docker build -v` is not. However RedHat seems to provide a version of `docker` which contains support for `-v` in build, see comment at https://github.com/docker/docker/issues/14080#issuecomment-290964327. Could that feature be ported over as Docker seems to fight against it?

I have a use case where I am building an image with a binary.
I have an image that I am building on top of another image I am also building both as part of cloudbuild.yaml setup. Both images depend on a private library of mine and right now I have to put the library into the 1st image in order for it to be available on the 2nd. I would much rather do `-v` with both to avoid creating large images.

**Comment by Philmod** [comment]
Hey Matthew,

All the build steps happens in the [`/worskpace` directory](https://cloud.google.com/container-builder/docs/api/build-steps#build_process).

Have you tried importing your private library as a build step?

steps: 
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'your-first-image', '.']
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'your-private-library']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'your-second-image', '.']

Best,
Philmod

**Comment by matthewvalimaki** [comment]
@Philmod I should've provided more details, apologies. I have almost what your example has.

Simplified version of what I have:
```
steps: 
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'source', 
    'repos', 
    'clone', 
    'library', 
    'root/and/path/to/GOPATH', 
    '--project=$PROJECT_ID',
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'your-first-image', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'your-second-image', '.']
```
`your-first-image` Dockerfile does `ADD root /` (including cloned `library`). In this image I do all the prep work for either testing, running locally or whatever.
Then in `your-second-image` I do `go build` and clean up by removing all that I do not need.

Back to your point of `/workspace`. Like `--volume` I do not see `--workdir` be available for `docker build` so I do not see how it could help me avoid putting the library into the built `your-first-image`.

**Comment by jameswthorne** [comment]
I'm running into the same issue.

How does the __gcr.io/cloud-builders/docker__ cloudbuilder image read files/directories stored in __/workspace__? I do not see __/workspace__ mounted anywhere within __gcr.io/cloud-builders/docker__ while it is running and building my Dockerfile.

**Comment by bendory** [comment]
Our Build Steps documentation describes your your build steps are run -- see the subheading [Build Process](https://cloud.google.com/container-builder/docs/concepts/build-steps#build_process).

Does that help clarify what is happening?

**Comment by jameswthorne** [comment]
I was having similar issues, but I figured out what I was doing wrong.

In my Dockerfile being built by the `- name: 'gcr.io/cloud-builders/docker'` build step (which is the last build step in my __cloudbuild.yaml__), I was attempting to copy data from __/workspace/repo/dir__ when I should have been copying data from __repo/dir__.

**Comment by bendory** [comment]
I'm closing this issue; please feel free to re-open if our [Build Process](https://cloud.google.com/container-builder/docs/concepts/build-steps#build_process) documentation is not sufficient.
