### ISSUE TITLE
Google Cloud Build - Github App test reporter?

### ISSUE THREAD

**Issue by bondarewicz** [GoogleCloudPlatform/cloud-builders#387]
Hi there, is there any way of configuring the [app](https://github.com/marketplace/google-cloud-build) to report on test results and code coverage on any of the github's:

<img width="850" alt="image" src="https://user-images.githubusercontent.com/435051/47080633-73d56d00-d200-11e8-930d-0187909b8408.png">

and/or google interfaces?

<img width="799" alt="image" src="https://user-images.githubusercontent.com/435051/47080661-864fa680-d200-11e8-9d49-fcbf1e9b0bad.png">

**Comment by bendory** [comment]
At this time, you can only post "success / failure".
