### ISSUE TITLE
app works fin in local GAE dev server, when deployed remote...nothing

### ISSUE THREAD

**Issue by iatomic** [GoogleCloudPlatform/cloud-builders#398]
we have an app for GAE standard that runs fine with

1. mvn appengine:devserver

Options 2 or 3 execute OK yet no app is deployed or reachable....

2. gcloud app deploy src/main/webapp/WEB-INF/appengine-web.xml

OR

3. mvn appengine:update
execute OK yet the app does not even show up, all is see is

Error: Not Found

We cannot fine ANY meaningful logs of startup either....

**Comment by bendory** [comment]
I don't think this is the right forum for seeking help with your issue. Please use one of the App Engine forums: https://cloud.google.com/appengine/community
