### ISSUE TITLE
Excessive Bitbucket permissions request when creating a trigger

### ISSUE THREAD

**Issue by moleman** [GoogleCloudPlatform/cloud-builders#399]
I'm wondering why Google Cloud Build needs to have this extreme (in my opinion) access to my Bitbucket account when I'm creating a Bitbucket trigger?
<img width="610" alt="screen shot 2018-10-31 at 08 15 58" src="https://user-images.githubusercontent.com/139056/47772729-f160a900-dce7-11e8-802b-d036cae39ce4.png">

**Comment by prabenzom** [comment]
Hello, 

We need those permissions if you are trying to mirror your BitBucket repository to GCP. If you only wish to create a build trigger, you can follow the steps at this page - https://cloud.google.com/cloud-build/docs/running-builds/automate-builds - which require less permissions.

**Comment by moleman** [comment]
Hmm, ok. When I follow the steps according to the documentation:

1. Open the build triggers page
2. Add trigger
3. Select "Bitbucket"
4. Click continue

I get the "Google Connected Repository is requesting access to the following: " (same as the screenshot) access request. I would not expect it to try to mirror my Bitbucket repository to GCP when I just want to add a trigger or am I missing something?

**Comment by moleman** [comment]
Found this note:

> Note: For external repositories, such as GitHub and Bitbucket, you must have owner-level permissions for the Cloud Platform project with which you're working. When you set up a build trigger with an external repository for the first time, you'll need to set up authorization with that repository.

> After you've set up your external repository, Cloud Source Repository creates a mirror of your repository.

So, it needs to mirror the repository to be able to add the trigger which means that I need to give GCP all the requested access?

**Comment by prabenzom** [comment]
Yes, you'll need to GCP the requested access in order to add the trigger. When I went through the flow via the add triggers page, the set of permissions I was asked for was slightly different, however. Is this what you saw? 
<img width="657" alt="screen shot 2018-10-31 at 10 52 03 am" src="https://user-images.githubusercontent.com/37380271/47796588-098df380-dcfb-11e8-9209-233cbdd0fb7d.png">

**Comment by moleman** [comment]
Nope. This is what I see:
<img width="614" alt="screen shot 2018-11-01 at 07 58 29" src="https://user-images.githubusercontent.com/139056/47837337-f424d200-ddab-11e8-971c-8876cec0132d.png">

If I select Github I get this:
<img width="520" alt="screen shot 2018-11-01 at 07 59 13" src="https://user-images.githubusercontent.com/139056/47837365-0f8fdd00-ddac-11e8-9d8d-2ef1fa276926.png">

which feels like a more reasonable permission request even though I wish there was a possibility to explicitly give access to a single repository and not to all my repositories.

There's no way to manually enable a trigger, i.e. to add a webhook in Bitbucket to Google Cloud Builder and to setup explicit permissions?

**Comment by bendory** [comment]
This GitHub issue tracker is intended for bugs with the officially supported builder images specifically.
Please report issues and feature requests regarding the GCB service to our public issue tracker at
https://issuetracker.google.com/issues/new?component=190802&template=1162743
