### ISSUE TITLE
go & golang-project is confusing

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/cloud-builders#4]
I spent quite some time to understand how these two images are different and which one I should be using. This looks like a fairly confusing point and I don't have an answer yet.

Is there a way to clarify this like:

> **NOTE:** If you looking for $X, go use $IMAGE.

**Comment by skelterjohn** [comment]
Thanks, this is good feedback. I'll add something to the READMEs.

In general, you use the 'go' builder if you want to run the 'go' tool on your source directly (to create binaries, run tests, fetch deps, etc).

The 'golang-project' builder starts with a source tree and produces a container image, and is designed to work out of the box with most "normal" go projects.

**Comment by ahmetb** [comment]
Haha call me dumb but I still don't understand the difference. So in the first one you run the go commands yourself and in the latter it runs them for you (like library/golang:*-onbuild image)?

**Comment by dlsniper** [comment]
I've just made https://github.com/gopheracademy/gopher build with this, maybe it helps?
The project used circleci and the build logic is contained in ` container-make.sh ` but now that was changed and it's in ` cloudbuild.yaml `.
