### ISSUE TITLE
gcr.io/cloud-builders/bazel installs bazel 0.18.1 and not 0.19.0

### ISSUE THREAD

**Issue by or-shachar** [GoogleCloudPlatform/cloud-builders#402]
Since the release of bazel **0.18.1** that strangely happened after **0.19.0** - **`gcr.io/cloud-builders/bazel`** installs **0.18.1** and is missing several features and code fixes. 

This breaks the build of those who already relied on those new features and bug fixes.

How can we avoid this from happening in the future?

**Comment by ImJasonH** [comment]
Is there a corresponding bug filed against https://github.com/bazelbuild/bazel to figure out why `apt-get install bazel` gets 0.18.1 instead of 0.19.0? Pinning to 0.19.0 fixes the issue for now, but it doesn't address future instances of this bug.

**Comment by or-shachar** [comment]
I've opened an issue here: https://github.com/bazelbuild/bazel/issues/6588
But in general - we need a solution for these days, because we just downgraded our worker bazel version. When bazel would make their next release - we can revert this change
