### ISSUE TITLE
Gsutil: BQ update expiration date broken in 225.0.0

### ISSUE THREAD

**Issue by amohabir** [GoogleCloudPlatform/cloud-builders#407]
I'm using the following command to update the expiration date of a table.
```bash
bq update --expiration 0 test-project:test-set.test-table
```
Using `google/cloud-sdk:224.0.0-alpine` this seems to be going fine. This also went fine for older versions of `gcr.io/cloud-builders/gsutil`:
```bash
Table 'test-project:test-set.test-table' successfully updated.
```
Using either `gcr.io/cloud-builders/gsutil:latest` or `google/cloud-sdk:225.0.0-alpine` I'm getting the following exception:
```bash
UpdateTable() got an unexpected keyword argument 'range_partitioning'
```

**Comment by bendory** [comment]
closing as obsolete; reference https://github.com/GoogleCloudPlatform/cloud-builders/issues/638
