### ISSUE TITLE
Abstract builder?

### ISSUE THREAD

**Issue by MaximilianR** [GoogleCloudPlatform/cloud-builders#41]
Is there a reason we can't have a builder where we can supply the entrypoint at runtime? 

For example, we need to use `pip`. I think making a image that did this would be fairly trivial (I might be wrong though) - namely taking an existing image and adding `ENTRYPOINT ["pip"]` to the Dockerfile. 

But then why not allow this as an argument in the `cloudbuild.yaml`, rather than having a specific list of builders with a full image for each?

**Comment by skelterjohn** [comment]
You can specify "entrypoint" for a build step, for this very reason.

https://cloud.google.com/container-builder/docs/api/reference/rest/v1/projects.builds#Build.BuildStep

**Comment by MaximilianR** [comment]
Thanks
