### ISSUE TITLE
New builders for Maven and Java 11

### ISSUE THREAD

**Issue by Alos** [GoogleCloudPlatform/cloud-builders#412]
It would be nice if we had new versions of gcr.io/cloud-builders/javac and gcr.io/cloud-builders/mvn with support for OpenJDK 11.

**Comment by akauppi** [comment]
Connected to this, I wonder if they could be named other than `javac`.

- the current image also contains Docker (attributing to its huge 980 MB size for a JDK 8 image).
- other builders (like mine, for sbt+Scala) only need it for the JDK.

I only realized Docker was included when digging why the size of the image is so big. Having this info in the name would be helpful.

I'll likely name my derived builder `sbt-scala-docker` for this reason, to make the existence of Docker explicit. And make another `sbt-scala` without Docker, though... in my use cases it'll always be needed so maybe I don't bother.

btw. do the other GCR builder images also contain Docker, implicitly?

**Comment by bendory** [comment]
https://github.com/GoogleCloudPlatform/cloud-builders/issues/665
