### ISSUE TITLE
bazel can't run webtests

### ISSUE THREAD

**Issue by ribrdb** [GoogleCloudPlatform/cloud-builders#419]
The bazel image is missing some of the shared libraries needed to run chrome:
Step #8: 17 12 2018 16:50:54.916:ERROR [launcher]: ChromeHeadless stderr: external/org_chromium_chromium_linux/chrome: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory
S

from ldd it looks like these are also missing:
Step #8: libatk-bridge-2.0.so.0 => not found
Step #8: libgtk-3.so.0 => not found
Step #8: libgdk-3.so.0 => not found

**Comment by bendory** [comment]
closing as obsolete; reference https://github.com/GoogleCloudPlatform/cloud-builders/issues/667
