### ISSUE TITLE
go: errors with more than one directory in GOPATH

### ISSUE THREAD

**Issue by wmark** [GoogleCloudPlatform/cloud-builders#420]
Format of `GOPATH` is a *pathspec*: It can contain more than one directory.  
https://golang.org/cmd/go/#hdr-GOPATH_environment_variable

That has not been considered in scripts, such as here: https://github.com/GoogleCloudPlatform/cloud-builders/blob/4dd1eba559c556744d03cb3d9f16dc8f8333f2dc/go/go.bash#L21-L22

Which, with for example a `GOPATH="/var/spool/go:/go:/usr/share/gocode"`  
… will set `binpath` to something that is no directory (influenced by `${PWD}`).

**Comment by bendory** [comment]
closing as obsolete; see https://github.com/GoogleCloudPlatform/cloud-builders/issues/677
