### ISSUE TITLE
bazel builder writes empty IDs to $BUILDER_OUTPUT

### ISSUE THREAD

**Issue by michaeledgar** [GoogleCloudPlatform/cloud-builders#421]
Not all Bazel commands produce an invocation ID. Commands that do produce an ID may fail on startup and never upload results.

In both of these cases, thje bazel builder currently writes the following to `$BUILDER_OUTPUT`:

    {"bazel.build/invocation_id": ""}

This is misleading to machine consumers and easily avoided by the wrapper script. When we have no invocation ID, we should simply not write to `$BUILDER_OUTPUT`.

**Comment by bendory** [comment]
Closing as obsolete; reference https://github.com/GoogleCloudPlatform/cloud-builders/issues/667
