### ISSUE TITLE
Add a firebase cloud-builder

### ISSUE THREAD

**Issue by leighmcculloch** [GoogleCloudPlatform/cloud-builders#423]
It'd be really helpful if there was an official `firebase` cloud-builder image. It's extraordinarily helpful that there is a `gcloud` image that we can run to deploy to App Engine, etc, and deploying to Firebase is much more inconvenient because every project needs a Dockerfile that builds the same image that's outlined [here](https://cloud.google.com/cloud-build/docs/configuring-builds/build-test-deploy-artifacts#deploying_artifacts).

**Comment by bendory** [comment]
Note that there is currently a [Firebase Community Builder](https://github.com/GoogleCloudPlatform/cloud-builders-community/tree/master/firebase) -- does it meet your needs? If not, can you open an issue there detailing where it falls short?

**Comment by leighmcculloch** [comment]
The community builder needs to be built for every project which seems redundant and odd given `firebase` is an official Google tool like `gcloud`.

**Comment by leighmcculloch** [comment]
@bendory Does the fact the tool is a Google CLI used with Google Cloud make it eligible for being an official builder? It's extraordinarily useful to be able to reference the similar `gcloud` build in projects without needing to build it manually.

**Comment by RuneStone0** [comment]
@leighmcculloch , +1 on this feature request

**Comment by bendory** [comment]
Closing this Issue which has been accepted by the Firebase team as a feature request; please watch [here](https://issuetracker.google.com/issues/157638155) for updates.
