### ISSUE TITLE
[FEAT] Add Cypress support on NPM image

### ISSUE THREAD

**Issue by fgruchala** [GoogleCloudPlatform/cloud-builders#425]
Hello,

If I want to use Cypress (https://www.cypress.io/), I must have these [dependencies](https://docs.cypress.io/guides/guides/continuous-integration.html#Dependencies) :

- xvfb 
- libgtk2.0-0 
- libnotify-dev 
- libgconf-2-4 
- libnss3 
- libxss1 
- libasound2

So I made these image :

```
FROM gcr.io/cloud-builders/npm:node-10.10.0

# install required dependencies for Cypress
# https://docs.cypress.io/guides/guides/continuous-integration.html#Dependencies
RUN apt-get update && apt-get install -y \
    xvfb \
    libgtk2.0-0 \
    libnotify-dev \
    libgconf-2-4 \
    libnss3 \
    libxss1 \
    libasound2

ENTRYPOINT ["/usr/local/bin/npm"]
```

What about integrate these dependencies on the official NPM image ? Or made a new one ?

**Comment by bendory** [comment]
Cypress sounds like a great candidate for a [Community Builder](https://github.com/GoogleCloudPlatform/cloud-builders-community). Would you like to submit a PR over there for a Cypress builder?

**Comment by fgruchala** [comment]
Yes, great idea :) 
I would like to but I don't have enough right to make a PR on that repo.

How can I make this ?

**Comment by rafikk** [comment]
Looks like Cypress has an official Docker image: https://docs.cypress.io/guides/guides/continuous-integration.html#Docker

You can use `cypress/base` from Docker Hub directly as build step or base your own Dockerfile build on it.

**Comment by fgruchala** [comment]
Yessss, I began in this way :)
But, there is always a "but", my project is in VueJS with @vue/cli so, in my package.json :

```
$ npm run test:e2e
```
forward to
```
$ vue-cli-service test:e2e
```

I prefer to keep NPM as my entrypoint for my build steps.
If you have better, I take :)

**Comment by rnkimani** [comment]
Actually cypress now supports a bunch of [docker images](https://hub.docker.com/u/cypress) that can be used in build steps. 
```
 - name: 'cypress/base'
    entrypoint: 'bash'
    args: ['-c', '$(npm bin)/cypress run --env branch=$BRANCH_NAME --record --key ${_CYPRESS_RECORD_KEY_}']
```

**Comment by bendory** [comment]
closing as obsolete, reference https://github.com/GoogleCloudPlatform/cloud-builders/issues/322
