### ISSUE TITLE
More documentation on "Google Cloud Build for Github"

### ISSUE THREAD

**Issue by williamli** [GoogleCloudPlatform/cloud-builders#433]
I am new to Google Cloud Build and I found the following very confusing.

1. There is Google Cloud Build for Github
2. There is Build Triggers

Google Cloud Build for Github seems to be Github's entry point to get users to use Cloud Build from Github's interface.

All the documentation in Google Cloud Build points to Build Triggers with no mention of "Google Cloud Build for Github".

I first noticed "Google Cloud Build" when I was toying around with Travis in Github. Installed "Google Cloud Build for Github" in Github. Googled it a bit and read up on it in Google docs and set up the triggers... only to find 2 builds are triggered for every commit XD.

To add to the confusion, the way branches are handled is different between triggers and Github integration. Triggers seems to be more flexible in that it is clean to setup different substitutes and cloudbuild.yaml files for different branches but *it does not commit any build results back to Github*... whereas the Github integration requires more scripting to get different build steps for different branches (https://github.com/GoogleCloudPlatform/cloud-builders/issues/431 and https://github.com/GoogleCloudPlatform/cloud-builders/issues/138 and https://stackoverflow.com/questions/51861870/github-cloud-build-integration-with-multiple-cloudbuild-yamls-in-monorepo) but has a better integration that pushes build results back to Github... and it support PR (?).

**Comment by williamli** [comment]
Found a page in over at https://cloud.google.com/cloud-build/docs/run-builds-on-github _Google Cloud Build GitHub app_.

**Comment by dinvlad** [comment]
(sorry - originally posted this in #431, but it seems more appropriate here)
There should be a clear way to specify different configuration (substitutions etc.) for different branches (dev/prod/..). Otherwise, this integration is mostly useful only for continuous deployment on a single branch.
