### ISSUE TITLE
Can build triggers push build results back to Github?

### ISSUE THREAD

**Issue by williamli** [GoogleCloudPlatform/cloud-builders#434]
Is it possible for build triggers to push build results back to Github (similar to Google Cloud Build for Github)?

<img width="911" alt="screenshot 2019-01-19 at 02 02 08" src="https://user-images.githubusercontent.com/179761/51404409-53fe6e00-1b8e-11e9-9641-7af101c8d783.png">
<img width="600" alt="screenshot 2019-01-19 at 02 02 20" src="https://user-images.githubusercontent.com/179761/51404415-56f95e80-1b8e-11e9-90e7-236f8aaba9a5.png">

**Comment by bendory** [comment]
This GitHub issue tracker is intended for bugs with the officially supported builder images specifically.
Please report issues and feature requests regarding the GCB service to our public issue tracker at
https://issuetracker.google.com/issues/new?component=190802&template=1162743
