### ISSUE TITLE
Allow configuration of Github Integration builds

### ISSUE THREAD

**Issue by eddiemonge** [GoogleCloudPlatform/cloud-builders#439]
Right now it is possible to set variables for manually created triggers but not for the builds triggered by the Github integration. This makes it pretty near useless to use for running tests that require any customization unless you also check in those configurations, which goes against oh so many development practices.

**Comment by bendory** [comment]
This GitHub issue tracker is intended for bugs with the officially supported builder images specifically.
Please report issues and feature requests regarding the GCB service to our public issue tracker at
https://issuetracker.google.com/issues/new?component=190802&template=1162743
