### ISSUE TITLE
DEADLINE_EXCEEDED no log return

### ISSUE THREAD

**Issue by Sermanes** [GoogleCloudPlatform/cloud-builders#457]
Hi! I'm having a problem with my gcloud builder.

When I try to run my cloud build, I have a problem and it doesn't give me anything back. The code and the logs are uploaded well to the bucket, but it doesn't give me back any record and at the end it gives a Time Out.

CLoudBuild.yaml:
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile-nginx', '--tag=gcr.io/$PROJECT_ID/nginx-qa:$BRANCH_NAME', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/nginx-qa:$BRANCH_NAME']

State: The waiting time for the creation has been exhausted

ERROR: (gcloud.builds.submit) build a77bf930-c801-40fd-bbbe-b1d4068de016 completed with status "TIMEOUT"

script returned exit code 1

Thank you!

**Comment by ImJasonH** [comment]
This sounds like a bug report for the GCB service itself, and is unrelated to a specific builder image developed in this repo.

Please see https://cloud.google.com/cloud-build/docs/getting-support for information about how best to file this bug.
