### ISSUE TITLE
Add Cloud Native Buildpack

### ISSUE THREAD

**Issue by saturnism** [GoogleCloudPlatform/cloud-builders#463]
Add Cloud Native Buildpack - https://buildpacks.io/

**Comment by bendory** [comment]
Can you please clarify what your reported issue is? Any containerized buildpack should be usable as is as a `cloud-builder`; it isn't clear to me what you are asking to add?

**Comment by ImJasonH** [comment]
Users can use https://github.com/GoogleCloudPlatform/buildpacks (or alternatives) with GCB, so we don't need a cloud-builders image for this.

**Comment by bendory** [comment]
@saturnism I'm closing this issue; please re-open with an explanation of your ask if you believe there is a feature request here that I'm not understanding.
