### ISSUE TITLE
Tag mvn:x.y.z-jdk-11

### ISSUE THREAD

**Issue by saturnism** [GoogleCloudPlatform/cloud-builders#464]
## Affected builder image
`gcr.io/cloud-builders/mvn:latest`

## Expected Behavior
This latest version is bumped from Java 8 to Java 11. It should be tagged w/ -jdk-11 suffix.

## Actual Behavior
This version has only the latest tag.

## Steps to Reproduce the Problem

1. `docker pull gcr.io/cloud-builders/mvn:latest`
2. `docker run -ti --entrypoint=java gcr.io/cloud-builders/mvn:latest -version`
3. `openjdk version "11.0.2" 2019-01-15...`

/cc @davidstanke

**Comment by bendory** [comment]
closing as obsolete
https://github.com/GoogleCloudPlatform/cloud-builders/issues/665
