### ISSUE TITLE
kubectl no longer honors credentials from `gcloud container clusters get-credentials`

### ISSUE THREAD

**Issue by farrellit** [GoogleCloudPlatform/cloud-builders#465]
# Affected builder image

gcr.io/cloud-builders/kubectl

## Expected Behavior

Previous step running `gcloud container clusters get-credentials` used to expose credentials in such a way that they'd be picked up by a subsequent `kubectl` step

## Actual Behavior

Recently (not exactly sure when) the `kubectl` invocation started erroring out with:

`No cluster is set. To set the cluster (and the zone where it is found), set the environment variables`

## Steps to Reproduce the Problem

1. have an existing kubernetes gke cluster
2. run the `glcoud container clusters get-credentials` from a first cloudbuild step for that cluster
3. run the 'kubectl' builder and you'll get the error

## Additional Info

This seems like a regression, but maybe I've just been doing it wrong and it happened to work, IDK.  Kubectl builder should imho be agnostic as to how it gets its credentials.  Setup of credentials should be optional.  Not sure why this stopped working.

**Comment by farrellit** [comment]
I think this is where the behavior change was added:
https://github.com/GoogleCloudPlatform/cloud-builders/pull/456/files

**Comment by mercuriete** [comment]
can't deploy to differents clusters.
kubectl doesn't honor to variables.

Please reopen this bug: https://github.com/GoogleCloudPlatform/cloud-builders/issues/290

**Comment by ImJasonH** [comment]
Confirming this is a reproducible bug (https://github.com/GoogleCloudPlatform/cloud-builders/issues/290#issuecomment-514226856). The previous fix for it caused a regression for regional clusters, so we rolled it back, but never rolled it forward with a fix. I'll have a PR to fix this today, which we'll hopefully be able to release soon.

**Comment by mercuriete** [comment]
@ImJasonH Thanks for the quick response.
👍

**Comment by mercuriete** [comment]
@ImJasonH Thanks for your amazing work!

**Comment by ImJasonH** [comment]
@mercuriete No problem, sorry it took so long to address the issue.

Unfortunately, even though it's merged in this repo we still need to release the image, and I can't guarantee when our next release will be. I'll update this bug when the fix is out, but for the time being you're still going to get the current behavior. Sorry for that inconveience.

**Comment by mercuriete** [comment]
@ImJasonH Don't worry, I am using the workaround with: KUBECONFIG env variable.

Thanks for your work 👍
