### ISSUE TITLE
kubectl no longer honors the KUBECONFIG environment variable

### ISSUE THREAD

**Issue by daanemanz** [GoogleCloudPlatform/cloud-builders#466]
## Affected builder image

`gcr.io/cloud-builders/kubectl`

## Expected Behavior

`kubectl` honors the `KUBECONFIG` environment variable

## Actual Behavior

`kubectl` does not honor the `KUBECONFIG` environment variable and errors out when there's no context set.

## Steps to Reproduce the Problem

1. Set `KUBECONFIG` environment variable pointing to an actual kubeconfig file
2. Run `kubectl` builder

## Additional Info

Previously, this builder would honor a kube config set with the `KUBECONFIG` environment variable. Since https://github.com/GoogleCloudPlatform/cloud-builders/pull/456 was merged this is no longer the case as there's no check for a current config any longer. Can https://github.com/GoogleCloudPlatform/cloud-builders/pull/456 be reverted?

**Comment by bendory** [comment]
closing as obsolete; context: https://github.com/GoogleCloudPlatform/cloud-builders/issues/638
