### ISSUE TITLE
`--set-env-vars` is not passed correctly the the gcloud builder

### ISSUE THREAD

**Issue by martinffx** [GoogleCloudPlatform/cloud-builders#469]
## Affected builder image

`gcr.io/cloud-builders/gcloud`

## Expected Behavior

The following build file to deploy my cloud function and set the `DATABASE_URL` env variable.
```
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: deploy_schedule_index
  args: [
    'functions', 'deploy', 'marketdata_schedule_index_$BRANCH_NAME', '--region=europe-west1',
    '--memory=128MB', '--retry', '--runtime=python37', '--entry-point=schedule_index',
    '--service-account=$SERVICE_ACCOUNT',
    '--source=https://source.developers.google.com/projects/$PROJECT_ID/repos/$REPO_NAME/moveable-aliases/$BRANCH_NAME',
    '--set-env-vars DATABASE_URL=postgres://test:password@/postgres?host=/cloudsql/my_db_instance',
    '--trigger-topic=hourly_schedule'
  ]
```

## Actual Behavior

The build fails with: `unrecognized arguments: --set-env-vars ...`

If I look at the generated arguments:

```
 functions deploy marketdata_schedule_index_master --region=europe-west1 --memory=128MB --retry --runtime=python37 --entry-point=schedule_index --service-account=market-meta-data@eulersformula.iam.gserviceaccount.com --source=https://source.developers.google.com/projects/eulersformula/repos/github_martinffx_marketdata/moveable-aliases/master "--set-env-vars DATABASE_URL=postgres://test:password@/postgres?host=/cloudsql/my_db_instance" --trigger-topic=hourly_schedule
```
For some reason the `--set-env-vars` is surrounded by misc. `"`, when I copy that, remove the `"` and run it locally everything completes successfully.

## Steps to Reproduce the Problem

1. Deploy a cloud function using the `gcloud` builder (see config above for example), setting an environment variable for the cloud function.

## Additional Info

This fails with a significantly simpler environment variable `--set-env-vars FOO=BAR`

**Comment by rafikk** [comment]
I think this is failing because you're passing the flag name and value as a single argument. I.e. you need to pass this:

    '--set-env-vars', 'DATABASE_URL=postgres://test:password@/postgres?host=/cloudsql/my_db_instance',


instead of this:

    '--set-env-vars DATABASE_URL=postgres://test:password@/postgres?host=/cloudsql/my_db_instance',

The alternative, of course, is to include an explicit `=` between the flag name and value (as you've done for the other arguments). I'm guessing you didn't include the `=` because the value for `--set-env-vars` includes a `=`. I'm not sure how the parser would handle `--set-env-vars=FOO=BAR` but you could try.

[Closing. Please re-open if that's not the issue]

**Comment by martinffx** [comment]
OMG, thank you! I was loosing my mind trying to solve this, was about to write a bash script.

Is it possible to contribute back to the documentation, some slightly more complex examples would be great!
