### ISSUE TITLE
Cloud builds for App engine Flex/ Java/ Spring Boot/ Gradle / Github

### ISSUE THREAD

**Issue by baole** [GoogleCloudPlatform/cloud-builders#476]
Hi, 

I would like to configure Cloud builds for our project. Here is our techstack:
- App Engine Flexible
- Java/Spring boot
- Gradle
- Github

Is there a template/guide for configure Cloud Build for such project?

**Comment by bendory** [comment]
To report issues with or ask questions about the Google Cloud Build service, please use our public issue tracker at https://issuetracker.google.com/issues/new?component=190802&template=1162743

This GitHub issue tracker is intended for bugs with the officially supported builder images specifically.
