### ISSUE TITLE
kubectl builder does not work with regional clusters

### ISSUE THREAD

**Issue by edruela** [GoogleCloudPlatform/cloud-builders#478]
I'm working in a CI/CD pipeline using Cloud Build and Cloud Run.
Because of a current limitation on the Cloud Run, I need to create the namespace in order to deploy the application. 

I was trying to run a step to execute a kubectl create namespace, but got an issue while trying to do it. My K8S cluster is regional and builder is failing when I don't provide a value for CLOUDSDK_COMPUTE_ZONE. 

But if I don't provide the value the build fail with the next message:

No cluster is set. To set the cluster (and the zone where it is found), set the environment variables
CLOUDSDK_COMPUTE_ZONE=<cluster zone>
CLOUDSDK_CONTAINER_CLUSTER=<cluster name>

ENV variables set by the yaml file:
Env. Vars	
CLOUDSDK_COMPUTE_REGION=us-central1 CLOUDSDK_CONTAINER_CLUSTER=my-cluster

**Comment by codrienne** [comment]
I believe this is Working As Intended, but maybe we to make the builder more flexible to permit other workflows. In the meantime, I would suggest building your own kubectl buildstep that is based on our official gcr.io/cloud-builders/kubectl. Our official builders are cached, so it will be very fast in pulling the layers.

Example: https://github.com/codrienne/kubectl-buildstep

**Comment by edruela** [comment]
@codrienne,

I will fork the repository and create my own builder, but what I'm reporting is that the official builder don't work with Regional Cluster.

You can easily validate that, implementing a test providing only the CLOUDSDK_COMPUTE_REGION and CLOUDSDK_CONTAINER_CLUSTER as described in the documentation and you will see the builder will return an error.

Thanks,
@edruela

**Comment by codrienne** [comment]
Gotcha, I've renamed the Github issue.

**Comment by ptinsley** [comment]
+1 on this, I had to write my own step to work around this and was coming here to file an issue.

**Comment by icco** [comment]
@codrienne we added support to the builder here in github, but it doesn't seem to exist in the versions that are in GCR. https://github.com/GoogleCloudPlatform/cloud-builders/blob/master/kubectl/kubectl.bash has the code to make regional clusters work...

**Comment by bendory** [comment]
closing as obsolete; context https://github.com/GoogleCloudPlatform/cloud-builders/issues/638
