### ISSUE TITLE
Deploy applications on self hosted kubernetes cluster using cloud build

### ISSUE THREAD

**Issue by ronakpandya7** [GoogleCloudPlatform/cloud-builders#480]
Hello,

We are planning to use google cloud build in future for building and deploying our application.
Right now we are deploying our applications on our self hosted kubernetes cluster.

So we check `cloud build` feature of google cloud platform for checking its building functionality and we found it useful, but we want to deploy or google cloud build image into our self hosted kubernertes cluster.

We found that there is a way to deploy application in `google kubernetes cluster` from this [kubectl](https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/kubectl).
But it is only saying that we can deploy on Google cloud kubernetes cluster.

So is there any way to deploy the application on self hosted kubernetes cluster using cloud build.

Thanks in advance,
Ronak Pandya

**Comment by ImJasonH** [comment]
This doesn't appear to be a bug report or feature request for the builder images developed in this repo.

Please see https://cloud.google.com/cloud-build/docs/getting-support for information about getting support for GCB.
