### ISSUE TITLE
/env/bin/python3.7: No module named pip

### ISSUE THREAD

**Issue by starmandeluxe** [GoogleCloudPlatform/cloud-builders#485]
I tried deploying to AppEngine (Python 3.7) using the following build rule:

```
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: '/bin/bash'
  args: ['-c', 'myscript.sh arg1 arg2']
```

The script contains the gcloud deploy command inside.

While the build status shows as successful (green check) and the script seems to have been run, the final log shows a concerning error:

> Step #5: ERROR: (gcloud.beta.app.deploy) Error Response: [9] Cloud build status: FAILURE.
Step #5: Error ID: B212CE0B.
Step #5: Error type: InternalError.
Step #5: Error message: `pip_install_from_wheels` had stderr output:
Step #5: /env/bin/python3.7: No module named pip
Step #5: 
Step #5: error: `pip_install_from_wheels` returned code: 1.

I'm not sure of the cause of the error, but is there some way to resolve this?

**Comment by aungwinthant** [comment]
In my case, I changed pip version to 19.0.1 in requirement.txt. Some says 18.1 also works for them.

**Comment by saqshamagrawal** [comment]
During 16-17 June, even 19.0.1 gave me similar error, changing to 19.0.3 (as recommended by [this page](https://safecontrols.blog/2019/01/)) solved it for me. I do feel this will recur in a few days time.

**Comment by bendory** [comment]
closing as obsolete, reference https://github.com/GoogleCloudPlatform/cloud-builders/issues/638
