### ISSUE TITLE
"--squash" is only supported on a Docker daemon with experimental features enabled

### ISSUE THREAD

**Issue by wxdao** [GoogleCloudPlatform/cloud-builders#486]
## Affected builder image

`gcr.io/cloud-builders/docker`

## Actual Behavior

```
"--squash" is only supported on a Docker daemon with experimental features enabled
```

## Steps to Reproduce the Problem

Write a simple build config like this:
```
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/squash-test', '.' ]
images:
- 'gcr.io/$PROJECT_ID/squash-test'
```
Run:
```
gcloud builds submit --config cloudbuild.yaml .
```

**Comment by ImJasonH** [comment]
I'm not sure whether we should enable experimental features for all users, since it might destabilize normal usage.

Do we have any idea when `--squash` will no longer require an experimental flag?

**Comment by wxdao** [comment]
I think the tracking issue is moby/moby#38657

**Comment by bendory** [comment]
If you are reporting an issue with the Google Cloud Build service,
please report it to our public issue tracker at
https://issuetracker.google.com/issues/new?component=190802&template=1162743

This GitHub issue tracker is intended for bugs with the officially
supported builder images specifically.
