### ISSUE TITLE
"mvn release:prepare" fails in Cloud Build

### ISSUE THREAD

**Issue by rigoford** [GoogleCloudPlatform/cloud-builders#491]
## Affected builder image
`gcr.io/cloud-builders/mvn`

## Expected Behavior
When running a cloud build with a step that uses the `gcr.io/cloud-builders/mvn` image to perform a `mvn release:prepare`, the "[maven-release-plugin] prepare release" and "[maven-release-plugin] prepare for next development iteration" commits made by the maven release plugin should be pushed to the cloud source repository being built.

## Actual Behavior
Build fails with message:
```
[ERROR] git: 'credential-gcloud.sh' is not a git command. See 'git --help'.
[ERROR] fatal: could not read Username for 'https://source.developers.google.com': No such device or address
```

## Steps to Reproduce the Problem
1. Create cloudbuild.yaml for a maven project containing the step:
```
- id: 'Prepare maven release'
  name: 'gcr.io/cloud-builders/mvn'
  args: ['--no-transfer-progress', '--batch-mode', 'release:prepare']
```
2. Commit and push the change.
3. Watch that step of the build fail with above error.

## Additional Info
Related to #317
The `gcr.io/cloud-builders/mvn` image is just based off the official Maven docker image and so doesn't contain the gcloud sdk.
Obviously, if you use the maven release plugin to automatically release a new version of the project, the git pushes back to the source repo are going to trigger another build, etc. So it would be good to be able to further limit/restrict the events that trigger a build...

**Comment by bendory** [comment]
This GitHub issue tracker is intended for bugs with the officially supported builder images specifically.
Please report issues and feature requests regarding the GCB service to our public issue tracker at
https://issuetracker.google.com/issues/new?component=190802&template=1162743

**Comment by davidgf** [comment]
Hi @rigoford, have you managed to work around this?
