### ISSUE TITLE
Github app: expose current issue (pull request) id

### ISSUE THREAD

**Issue by hazcod** [GoogleCloudPlatform/cloud-builders#499]
## Affected builder image
`gcr.io/cloud-builders/*

## Expected Behavior
Access the current issue (pull request, ...) id whenever it is triggered by a pull request.

## Actual Behavior
No way to know the issue id.

## Additional Info
I'd like to submit.a comment on the pull request in my cloudbuild, but I still miss the issue id.
Github API exposes this to the app: https://developer.github.com/v3/activity/events/types/#checkrunevent

**Comment by bendory** [comment]
This GitHub issue tracker is intended for bugs with the officially supported builder images specifically.
Please report issues and feature requests regarding the GCB service to our public issue tracker at
https://issuetracker.google.com/issues/new?component=190802&template=1162743
