### ISSUE TITLE
go: how to pull alpine-based image?

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/cloud-builders#5]
I see a Dockerfile.alpine for `go` however I can't see the image name documented anywhere so I cannot pull it. Is it available?

(I discovered that it's tagged at :alpine but let's ignore that for the moment)

**Comment by skelterjohn** [comment]
We should make this clear in the documentation, I agree.

**Comment by skelterjohn** [comment]
fixed in eef405f3b77f6e67fb28ce1d995f3e2f915a2138

**Comment by ahmetb** [comment]
Thanks @skelterjohn.
