### ISSUE TITLE
Github app: cancel running build job on Pull Request change

### ISSUE THREAD

**Issue by hazcod** [GoogleCloudPlatform/cloud-builders#501]
Currently the Github app does not cancel a running job whenever a new one is triggered.
This happens in a couple of occasions, e.g.: updated branch, closed pull request, ...

**Comment by bendory** [comment]
This GitHub issue tracker is intended for bugs with the officially supported builder images specifically.
Please report issues and feature requests regarding the GCB service to our public issue tracker at
https://issuetracker.google.com/issues/new?component=190802&template=1162743

**Comment by jthegedus** [comment]
Noteworthy: https://github.com/GoogleCloudPlatform/cloud-builders-community/pull/271
