### ISSUE TITLE
$BRANCH_NAME not accessible with Github checks

### ISSUE THREAD

**Issue by znat** [GoogleCloudPlatform/cloud-builders#534]
Not sure if it is a bug report or a feature request, but having the branch name at the github check level would be very handy.

**Comment by bendory** [comment]
To report an issue with the Google Cloud Build service, please report it to our public issue tracker at
https://issuetracker.google.com/issues/new?component=190802&template=1162743

This GitHub issue tracker is intended for bugs with the officially
supported builder images specifically.
