### ISSUE TITLE
Can I configure "Default GitHub Checks" trigger?

### ISSUE THREAD

**Issue by liiri** [GoogleCloudPlatform/cloud-builders#541]
After integrating my GH repository to Cloud Build, I'm getting a default trigger for any commit on any branch. The trigger name is `Default GitHub Checks`.

This is great that we have a default trigger, but I couldn't find where I can configure it - i.e point it to a different cloudbuild.yaml, disable it for certain branches by regex, etc.

For now there is a simple workaround to not have a cloudbuild.yaml in repository root, then define my own triggers. But its too risky to have such an implicit feature turned on if anyone ever does add such a yaml to repo root.

**Comment by ImJasonH** [comment]
This seems like a feature request for the GCB service, and not an issue directly related to the builder images in this repo. 

Please file this feedback at our issue tracker: https://issuetracker.google.com/issues/new?component=190802&template=1162743

**Comment by otherpirate** [comment]
Direct link to issue https://issuetracker.google.com/issues/138896013
