### ISSUE TITLE
Add Google Cloud SDK to bazel image to support dependencies in Google Cloud Source Repositories

### ISSUE THREAD

**Issue by roman-yepishev** [GoogleCloudPlatform/cloud-builders#547]
At the moment gcr.io/cloud-builders/bazel cannot use dependencies stored in Google Cloud Source Repositories because there is no git credentials helper for `https://source.developers.google.com`:

```
# WORKSPACE:
...
git_repository(
  name = "reponame",
  remote = "https://source.developers.google.com/p/some-project/r/some-repo",
  commit = "db389e3",
)
```
```
# BUILD
genrule(
  name = "empty",
  srcs = ["@reponame//:hello"],
  outs = ["hello.txt"],
  cmd = "cp $< $@",
)
```

## Affected builder image

gcr.io/cloud-builders/bazel

## Expected Behavior

git_repository with https://source.developers.google.com can be imported

## Actual Behavior
```
error running 'git fetch --all' while working with @reponame
fatal: could not read Username for 'https://source.developers.google.com': No such device or address
error: Could not fetch origin
```
## Steps to Reproduce the Problem

1. Declare git_repository in WORKSPACE pointing to a remote hosted by Google Cloud Source Repositories. 
2. Use gcr.io/cloud-builders/bazel in GCB session to build the project.

**Comment by bendory** [comment]
Closing as obsolete, reference:
- https://github.com/GoogleCloudPlatform/cloud-builders/issues/667
- https://github.com/GoogleCloudPlatform/cloud-builders/issues/638
