### ISSUE TITLE
Go Timezone Issue in Bazel Image

### ISSUE THREAD

**Issue by victoriajyang** [GoogleCloudPlatform/cloud-builders#548]
## Affected builder image
gcr.io/cloud-builders/bazel

## Expected Behavior
When running bazel tests in Go through GCB, tests that use LoadLocation for timestamps should work as they do locally.

## Actual Behavior
Tests are failing when I try to use LoadLocation for timestamps because they don't recognize or can't find the time zone database (perhaps an issue with a path?). 

## Steps to Reproduce the Problem
Here is a link to a test-repo that reproduces the problem with a minimum test case: https://github.com/victoriajyang/test-repo
Affected builder image:
I'm expecting the test to fail, however, when I run it through go with the cloudbuild.yaml 

 - name: 'gcr.io/cloud-builders/go'
      args: ['install', '.']
      env: ['PROJECT_ROOT=hello']
    - name: 'gcr.io/cloud-builders/go'
      args: ['test', 'hello']
      env: ['PROJECT_ROOT=hello']

it yields

Running: go test hello
Step #1: --- FAIL: TestHello (0.02s)
Step #1: hello_test.go:15: Got '2019-08-08 02:41:30.821541523 +1000 AEST', expected '2019-08-07 16:51:30.821542378 +0010 +0010'
Step #1: FAIL
Step #1: FAIL   hello   0.018s

which is expected.

When I run it with bazel using cloudbuild.yaml with

 - name: 'gcr.io/cloud-builders/bazel'
   args: ['test', '--test_output=all', '...']

it yields

==================== Test output for //:go_default_test:
2019/07/11 20:06:38 unknown time zone Australia/Sydney
--- FAIL: TestHello (0.00s)
panic: unknown time zone Australia/Sydney [recovered]
panic: unknown time zone Australia/Sydney

**Comment by JimLarson** [comment]
Friendly ping.  Is there anything else you need to reproduce the issue?

**Comment by bendory** [comment]
closing as obsolete; context https://github.com/GoogleCloudPlatform/cloud-builders/issues/667
