### ISSUE TITLE
Using C++in GCB

### ISSUE THREAD

**Issue by victoriajyang** [GoogleCloudPlatform/cloud-builders#549]
Are there plans to introduce an image for C++ or are there current images that people have successfully used with C++ code?

**Comment by ImJasonH** [comment]
There are no plans to provide a builder image for C++. The general trend has been toward recommending using an image built by the team providing the tools instead (npm, yarn, docker).

There's an official `gcc` image at https://hub.docker.com/_/gcc which might fit your needs. Feel free to follow up with questions but I don't know anything about C++ or its available tooling.
