### ISSUE TITLE
[Feature] - Build trigger incoming webhook

### ISSUE THREAD

**Issue by bijenkorf-james-wakefield** [GoogleCloudPlatform/cloud-builders#553]
It would be great if Cloud Build would support incoming webhooks, which could be used to trigger builds. In other words a build triggered by an incoming webhook. Other services like [Netlify](https://www.netlify.com/docs/webhooks/) offer this feature and it is convenient when you want to trigger a build by a change other than that in a code repository. For example from a CMS like [Contentful](https://www.contentful.com/developers/docs/concepts/webhooks/) where a user has updated an entry and wants to publish it.

**Comment by ImJasonH** [comment]
This GitHub repo issue tracker is meant to track bugs/features of builder images in this repo. Please file future requests like this at our public issue tracker: https://issuetracker.google.com/issues/new?component=190802&template=1162743

It should be fairly simple to create a Google Cloud Function that handles incoming webhook requests, and reacts by starting a build. You can write Functions in NodeJS, Python or Go, and there are client libraries for interacting with Cloud Build in all of those languages.

**Comment by bijenkorf-james-wakefield** [comment]
@ImJasonH: thanks for the advice. I will try the cloud function approach.
