### ISSUE TITLE
gnu make not found on bazel builder

### ISSUE THREAD

**Issue by mancini0** [GoogleCloudPlatform/cloud-builders#555]
## Affected builder image
gcr.io/cloud-builders/bazel

## Expected Behavior
make should be found on the path

## Actual Behavior
From the logs below, you can see that the GNU toolchain is found, but the make command is not found.

> INFO: From BootstrapCMake external/rules_foreign_cc/tools/build_defs/native_tools/cmake [for host]:
> /bin/bash: line 6: make: command not found
> cp: cannot stat './install': No such file or directory
> ---------------------------------------------
> CMake 3.12.1, Copyright 2000-2018 Kitware, Inc. and Contributors
> Found GNU toolchain
> C compiler on this system is: gcc 
> C++ compiler on this system is: g++ -std=gnu++17 
> ---------------------------------------------
> Error when bootstrapping CMake:
> Cannot find appropriate Makefile processor on this system.
> Please specify one using environment variable MAKE.
> ---------------------------------------------

## Steps to Reproduce the Problem

1. run a bazel cloud build that uses a rules_foreign_cc  "cmake_external" rule. For example, I created a repo that builds librdkafka here: https://github.com/mancini0/reproduce-bazel-cloud-build-nomake

2. You should be able to build the example repo locally, but it will fail if you attempt to build it on cloud build.

**Comment by bendory** [comment]
Closing as obsolete; reference https://github.com/GoogleCloudPlatform/cloud-builders/issues/667
