### ISSUE TITLE
gcloud builds doesn't stream the logs when logsBucket is used

### ISSUE THREAD

**Issue by bfarayev** [GoogleCloudPlatform/cloud-builders#562]
When `logsBucket` is used in cloudbuild.yaml logs are not being streamed to CLI but it works fine when no `logsBucket` is specified.

Maybe I need to specify additional options but couldn't find an easy solution other than using  default bucket.

**Comment by bendory** [comment]
To report an issue with the Google Cloud Build service, please report it to our public issue tracker at
https://issuetracker.google.com/issues/new?component=190802&template=1162743

This GitHub issue tracker is intended for bugs with the officially
supported builder images specifically.
