### ISSUE TITLE
go get fails when pulling from gcr.io

### ISSUE THREAD

**Issue by ichaelm** [GoogleCloudPlatform/cloud-builders#568]
Affected builder image: `gcr.io/cloud-builders/go`

I have a build that tries to do a `go get` from gcr.io:

- name: 'gcr.io/cloud-builders/go'
  args: ['get', '-t', './...']
  env: ['PROJECT_ROOT=poy-chat-bots.appspot.com/chat-bots','GO111MODULE=on']

Note: `poy-chat-bots.appspot.com/chat-bots` is a vanity URL that points to gcr.io.

I get the following error:

Step #0: go: poy-chat-bots.appspot.com/webhooks@v0.0.0-20181210220053-eeb713fe427e: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /workspace/gopath/pkg/mod/cache/vcs/4aa9460092905ef9d90318540001b256f315d616d5cb73043c08bb6f5f3b9962: exit status 128:
Step #0:        fatal: could not read Username for 'https://source.developers.google.com': terminal prompts disabled

The `fatal: could not read Username` seems to imply that the git config does not have a credential helper. For example on my local machine I have:

[credential "https://source.developers.google.com"]
        helper = gcloud.sh

If I remove this, I get the same error.

**Comment by ichaelm** [comment]
My understanding is that the gcloud credential helper should be installed on the go image to fix this.

**Comment by bendory** [comment]
closing as obsolete; reference https://github.com/GoogleCloudPlatform/cloud-builders/pull/678
