### ISSUE TITLE
gke-deploy should replace tags for init containers

### ISSUE THREAD

**Issue by purplexa** [GoogleCloudPlatform/cloud-builders#573]
## Affected builder image

`gcr.io/cloud-builders/gke-deploy`)

## Expected Behavior

When deploying a Kubernetes Deployment config that includes init containers, the images in the `initContainers` section of the config matching the image passed on the command line will have their versions updated to the version specified, same as what happens with the images in the `containers` section of the config.

## Actual Behavior

Only the containers in the `containers` section of the config are updated to the specified version.

## Steps to Reproduce the Problem

**cloudbuild.yaml**
~~~yaml
steps:
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args: [
      'run',
      '--filename', 'deployment.yaml',
      '--image', 'node:12.3.0',
      '--location', '$_LOCATION',
      '--cluster', '$_CLUSTER',
      '--namespace', '$_NAMESPACE',
    ]
substitutions:
  _CLUSTER:
  _LOCATION:
  _NAMESPACE:
~~~

**deployment.yaml**
~~~yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    app: demo
spec:
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      initContainers:
        - name: init
          image: node:10
          command: ['bash', '-c', 'test $(node --version) == "v12.3.0"']
      containers:
        - name: run
          image: redis
~~~

**Comment by LanceSandino** [comment]
This has nothing to do with the wrapper itself, it’s more so related to the `kube apply‘ command.  
https://stackoverflow.com/questions/49409176/using-kubectl-set-image-to-update-image-of-initcontainer/49414688

You’d have to add your own code to the gke wrapper of `kubectl apply`

**Comment by gustavovalverde** [comment]
A workaround for this (if you're trying to keep the latest image from Container Registry on each new deployment, is to use `imagePullPolicy: Always` on the initContainer

**Comment by ChrisGe4** [comment]
We are not prioritizing enhancements to gke-deploy at this time, but please feel free to submit your own PRs

**Comment by bendory** [comment]
Closing this as stale / obsolete.
