### ISSUE TITLE
cloud-builders/kubectl fails without KUBECTL_VERSION

### ISSUE THREAD

**Issue by camh-anz** [GoogleCloudPlatform/cloud-builders#581]
## Affected builder image

gcr.io/cloud-builders/kubectl

## Expected Behavior

Container image should work without setting the `KUBECTL_VERSION` environment variable.

## Actual Behavior

Cloud build logs:
```
Fetching cluster endpoint and auth data.
kubeconfig entry generated for [cluster name elided].
Running: kubectl. apply -f deployment/k8s
/builder/kubectl.bash: line 40: exec: kubectl.: not found
```

## Steps to Reproduce the Problem

1. Run your existing cloud build deployments with the new image (the `:latest` tag.)

## Additional Info
https://github.com/GoogleCloudPlatform/cloud-builders/pull/574 added the option to use the `KUBECTL_VERSION` environment variable to select the version of `kubectl` to use. However it incorrectly selects the executable name when `KUBECTL_VERSION` is unset.

This makes the change backwards incompatible and breaks all existing deployments using this cloud-builder image.

**Comment by jakebiesinger** [comment]
Oy, what a pain. Sorry for the breakage here. PR for the fix is up.
