### ISSUE TITLE
Building uber-jar with maven on quarkus project

### ISSUE THREAD

**Issue by jtama-op** [GoogleCloudPlatform/cloud-builders#583]
## Affected builder image

`gcr.io/cloud-builders/mvn`

## Expected Behavior

We should be able to run `mvn clean verify` with mvn builder and quarkus 1.0.0.CR1.

## Actual Behavior

The `gcr.io/cloud-builders/mvn` doesn't provide images for jdk1.8 mvn 3.5.3+ wich is required by quarkus : https://quarkus.io/guides/config

## Steps to Reproduce the Problem

Any build using mvn builder with project using quarkus.

**Comment by bendory** [comment]
Per https://github.com/GoogleCloudPlatform/cloud-builders/issues/665, please use the appropriately versioned official maven builder from  https://hub.docker.com/_/maven.
