### ISSUE TITLE
Connect to CloudSql Instance on Private IP from CloudBuilder

### ISSUE THREAD

**Issue by jgill-compucloud** [GoogleCloudPlatform/cloud-builders#603]
Is there a cloud builder that will allow a user to connect to a CloudSQL Postgres Instance with a private ip from a CloudBuilder? The use case, which is a common one is to run liquibase scripts from the build job which then make updates to the database schema.

**Comment by LanceSandino** [comment]
I was recently looking into this as well and my first idea was to just create a pod job in my kubernetes cluster to do this and delete upon completion, but I also thought about using cloudsql proxy. Haven’t implemented either yet. 

I found this link, it might help: https://stackoverflow.com/questions/52352103/run-node-js-database-migrations-on-google-cloud-sql-during-google-cloud-build/52366671#52366671

I don’t think anyone has made a builder for it, but honestly with the binary I don’t think you would need one.

**Comment by natefanaro** [comment]
I think adding `cloudsql-proxy` would be a great. I'm currently building my own image that rolls it in to `cloud-builders/gcloud` to handle database migrations.

Actually after some digging it looks like this does exist. https://github.com/GoogleCloudPlatform/cloudsql-proxy

Found an old thread where it was decided to keep the builder in its current repo.
https://github.com/GoogleCloudPlatform/cloud-builders/issues/92

**Comment by bendory** [comment]
For assistance with the hosted GCB service or other GCP products and services, please contact your Google support representative.
