### ISSUE TITLE
A builder with "go" command callable within bash?

### ISSUE THREAD

**Issue by wenovus** [GoogleCloudPlatform/cloud-builders#604]
I'm trying to execute a `go` command where part of the command resides in a file calculated at build time. I'm trying to do this using a bash command, i.e. `$(<filename.txt)`, and I can't seem to figure out a way.

Just using `gcr.io/cloud-builders/go:debian` doesn't work because the `args` can't evaluate any bash commands. Using `entrypoint` as `bash` also doesn't work because `go: command not found`. Is there any way to do this?

**Comment by ImJasonH** [comment]
This should work with `entrypoint: bash` and `args: ['-c', 'go version']`, with our `go:debian` image or just the official `golang` image on Dockerhub.

If it doesn't please let me know what the error message is, and I'll help debug.

**Comment by wenovus** [comment]
Thanks Jason! Works now. Though it is odd to me that I hit `go: command not found` when I didn't use `-c`, but instead executed a bash script containing the `go` command `args: ['script.sh']`.
