### ISSUE TITLE
kubectl (and likely others) should use stderr

### ISSUE THREAD

**Issue by poy** [GoogleCloudPlatform/cloud-builders#605]
## Affected builder image

(e.g., `gcr.io/cloud-builders/docker`)

gcr.io/cloud-builders/kubectl

## Expected Behavior

The only output to stdout is from kubectl.

## Actual Behavior

I get my command echoed back to me along with the kubectl output.

## Steps to Reproduce the Problem

1. Create a build step that does something like `kubectl get pods --output=json`
2.
3.

## Additional Info

I believe the correct way to display this helpful information is via stderr. That way the stdout can be piped to other things while stderr will still be available for debugging purposes.

**Comment by LanceSandino** [comment]
I second this, right now for pipes or variables I just `grep -v` it out. (Alternatively could replace the file with your changes too or make my own builder) but it was faster to use grep.

**Comment by bendory** [comment]
closing as obsolete, reference https://github.com/GoogleCloudPlatform/cloud-builders/issues/638
