### ISSUE TITLE
Enable running gcloud command through npm script.

### ISSUE THREAD

**Issue by irvifa** [GoogleCloudPlatform/cloud-builders#609]
## Affected builder image

gcr.io/cloud-builders/yarn
gcr.io/cloud-builders/npm

## Expected Behavior

Be nice if we can call gcloud command through the npm script. For example:
- Deploying cloud functions:

```
gcloud functions deploy $npm_package_name --project ${PROJECT_ID} --region=${REGION} --runtime=nodejs8 --trigger-http
```

## Actual Behavior

I thought this image is supporting gcloud command as well, but it's not.

**Comment by LanceSandino** [comment]
Why not just add another step using the gcloud builder to do this?

**Comment by bendory** [comment]
Closing as obsolete, reference https://github.com/GoogleCloudPlatform/cloud-builders/issues/638 and https://github.com/GoogleCloudPlatform/cloud-builders/issues/322
