### ISSUE TITLE
Add support for golang/dep

### ISSUE THREAD

**Issue by drgomesp** [GoogleCloudPlatform/cloud-builders#62]
It would be nice to have support for https://github.com/golang/dep, since it's getting a lot of traction lately as an alternative to Glide.

**Comment by ImJasonH** [comment]
I'm somewhat -1 on providing official support for this tool while it's not officially supported by the Go team, and is likely to change in breaking ways in the future.

However, I've got no problem with some user making this available as third-party builder, and I'd be happy to help anybody get that set up. One of the nice things about Container Builder is that any user can provide a builder just by publishing a container image.

**Comment by zombiezen** [comment]
I agree with @ImJasonH.  dep is still in alpha stage, so having an official image would be a bit premature. 
 I hacked together a build pipeline to create a dep image a little while ago, and it was quite simple (use at your own risk): https://gist.github.com/zombiezen/f5babb45ce7d330965f256e587bacb8c

**Comment by bendory** [comment]
Closing this issue; feel free to re-open when dep is more mature.

**Comment by brosner** [comment]
I can't speak to the maturity of dep. However, glide's [0.13.0 release](https://github.com/Masterminds/glide/releases/tag/v0.13.0) is recommending using dep over glide. This drove me to try dep and then immediately checked here to see if dep was supported.

I don't mind making a custom builder, but wanted to bring this to attention again.

**Comment by ofpiyush** [comment]
Is dep mature yet?

**Comment by ImJasonH** [comment]
Whether or not dep is mature, if there were to be a builder for it, we should put it in the [community repo](https://github.com/GoogleCloudPlatform/cloud-builders-community) and not in this repo. Anybody who's interested in such a builder should feel free to contribute it over there.

**Comment by jgrahn** [comment]
Not sure what measure of maturity you're going for here, but just wanted to add that dep's README file explicitly states that "dep is safe for production use" under "Current status" (see https://github.com/golang/dep).

They do say that "dep is the official experiment, but not yet the official tool". On the other hand, neither is glide.
