### ISSUE TITLE
gke-deploy fails when repeating a successful deployment

### ISSUE THREAD

**Issue by mrdevnull** [GoogleCloudPlatform/cloud-builders#639]
## Affected builder image

gcr.io/cloud-builders/gke-deploy

## Expected Behavior

Repeating a successful deployment should not fail.

## Actual Behavior

Repeating a successful deployment fails.

## Steps to Reproduce the Problem

Running the following command

`gcloud --verbosity=debug builds submit --config ./gke-deploy.yml`

where the config file contains (obfuscations with xxx)

```
steps:
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=gs://xxx/application.yml
  - --location=australia-southeast1-a
  - --cluster=cluster
  - --image=asia.gcr.io/xxx/go-docker-optimized:4.0
```

Works without issue on first run.  

```
--------------------------------------------- REMOTE BUILD OUTPUT ----------------------------------------------
starting build "d497ceae-6124-4a00-8a17-badfc31a6bf0"

FETCHSOURCE
Fetching storage object: gs://xxx_cloudbuild/source/1584862567.664254-2f8090b170844a81b9b2c1b26fe523d0.tgz#1584862568873799
Copying gs://xxx_cloudbuild/source/1584862567.664254-2f8090b170844a81b9b2c1b26fe523d0.tgz#1584862568873799...
/ [1 files][  558.0 B/  558.0 B]
Operation completed over 1 objects/558.0 B.
BUILD
Already have image (with digest): gcr.io/cloud-builders/gke-deploy
Preparing deployment.
2020/03/22 07:36:18 Downloading file(s) gs://xxx/application.yml from /tmp/gke_deploy_temp_152222843.
Configuration files to be used: [{kind: Deployment, name: hello-world}]
Updating container of resource: {kind: Deployment, name: hello-world}
Saving suggested configuration files to "output/suggested"

Expanding configuration files.
Got digest for image: asia.gcr.io/xxx/go-docker-optimized:3.0 --> asia.gcr.io/xxx/go-docker-optimized@sha256:2b2cbd97be4a9e6423c0ccaaff05c587eaa2eb1453f87d3612122f0b24652bfd
.
.
.
```

However second and subsequent runs (even with hours between) fail with an error reporting the file does not exist.

```
--------------------------------------------- REMOTE BUILD OUTPUT ----------------------------------------------
starting build "b73ed398-1f59-4a08-8a2c-8a04fcd371de"

FETCHSOURCE
Fetching storage object: gs://xxx_cloudbuild/source/1584862865.843985-e45f494c3d044a0e889d48f6fa34fd2steps:
9.tgz#1584862867151562
DEBUG: Reading GCS logfile: 206 (read 552 bytes)
Error: Exec command 761bbbc8c2ba1cae6c65ee19c3267fc4f9c4d0db34b09291d0455aeef1c71dff is already running
BUILD
Already have image (with digest): gcr.io/cloud-builders/gke-deploy
Preparing deployment.
Error: failed to prepare deployment: failed to parse configuration files "gs://xxx/application.yml": failed to get file info for "gs://xxx/application.yml": stat gs://xxx/application.yml: no such file or directory
ERROR
ERROR: build step 0 "gcr.io/cloud-builders/gke-deploy" failed: step exited with non-zero status: 1
DEBUG: Reading GCS logfile: 416 (no new content; keep polling)
----------------------------------------------------------------------------------------------------------------
```

The prior error regarding the exec command is perhaps the cause?  This doesn't appear on a successful run.

## Additional Info

If a local file is referenced with exactly the same content (rather than google storage based) the command works flawlessly.

For example 

```
steps:
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=application.yml
  - --location=australia-southeast1-a
  - --cluster=cluster
  - --image=asia.gcr.io/xxx/go-docker-optimized:4.0
```

**Comment by ChrisGe4** [comment]
Hi @mrdevnull,  I wasn't able to reproduce the issue. Are you still seeing that error?

**Comment by mrdevnull** [comment]
Hi @ChrisGe4, many thanks for responding!

I'm not seeing the error at the moment, but I have moved to a private cluster since.

Now all deployments fail with a timeout 

`error: unable to recognize "STDIN": Get https://10.1.0.2/api?timeout=32s: dial tcp 10.1.0.2:443: i/o timeout`

even when applying a timeout argument

`--timeout=10m`

(which appears to be ignored from the 32s setting in the error)

I can only assume it looks like there's still no support for the cloud build service on a private k8s cluster - as described [here](https://stackoverflow.com/questions/51944817/google-cloud-build-deploy-to-gke-private-cluster).

**Comment by bendory** [comment]
For assistance with the hosted GCB service or other GCP products and services, please contact your Google support representative.
