### ISSUE TITLE
 NPM build failed with npm cloudbuilder

### ISSUE THREAD

**Issue by muralivishnu** [GoogleCloudPlatform/cloud-builders#642]
## Affected builder image

gcr.io/cloud-builders/npm

## Actual Behavior

Step #4 - "NGL_UI_BUILD": Already have image (with digest): gcr.io/cloud-builders/npm:node-10.10.0
Step #4 - "NGL_UI_BUILD": 
Step #4 - "NGL_UI_BUILD": > nextjs-with-typescript@4.0.0 build /workspace
Step #4 - "NGL_UI_BUILD": > cross-env NODE_ENV=production next build
Step #4 - "NGL_UI_BUILD": 
Step #4 - "NGL_UI_BUILD": Creating an optimized production build...
Step #4 - "NGL_UI_BUILD": Attention: Next.js now collects completely anonymous telemetry regarding usage.
Step #4 - "NGL_UI_BUILD": This information is used to shape Next.js' roadmap and prioritize features.
Step #4 - "NGL_UI_BUILD": You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
Step #4 - "NGL_UI_BUILD": https://nextjs.org/telemetry
Step #4 - "NGL_UI_BUILD": 
Step #4 - "NGL_UI_BUILD": 
Step #4 - "NGL_UI_BUILD": > Build error occurred
Step #4 - "NGL_UI_BUILD": { [Error: EEXIST: file already exists, mkdir '/workspace/.next']
Step #4 - "NGL_UI_BUILD":   errno: -17,
Step #4 - "NGL_UI_BUILD":   code: 'EEXIST',
Step #4 - "NGL_UI_BUILD":   syscall: 'mkdir',
Step #4 - "NGL_UI_BUILD":   path: '/workspace/.next' }
Step #4 - "NGL_UI_BUILD": npm ERR! code ELIFECYCLE
Step #4 - "NGL_UI_BUILD": npm ERR! errno 1
Step #4 - "NGL_UI_BUILD": npm ERR! nextjs-with-typescript@4.0.0 build: `cross-env NODE_ENV=production next build`
Step #4 - "NGL_UI_BUILD": npm ERR! Exit status 1
Step #4 - "NGL_UI_BUILD": npm ERR! 
Step #4 - "NGL_UI_BUILD": npm ERR! Failed at the nextjs-with-typescript@4.0.0 build script.
Step #4 - "NGL_UI_BUILD": npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Step #4 - "NGL_UI_BUILD": 

## Steps to Reproduce the Problem

1. npm config set
2. npm install
3. nom run build

**Comment by bendory** [comment]
Closing as obsolete; please migrate to the Docker Community supported node images.
Reference https://github.com/GoogleCloudPlatform/cloud-builders/issues/322
