### ISSUE TITLE
Cloud Builder-java11_20200223_11_0_RC00 failing for project id with domain name

### ISSUE THREAD

**Issue by kirjay** [GoogleCloudPlatform/cloud-builders#646]
Hi,

I'm trying to deploy a Java 11 Maven project in App Engine, using **mvn appengine:deploy** command.
It was **successful** until last week.
This week after Google cloud sdk got updated to 288.0.0 the deployment is failing with below error.
i tried reverting Cloud SDK version but still the issue persists.
Project Id is of format- **google.com:abc-xyz**

Cloud Build Log Snippet below:
....
Finished Step #2 - "detector"
Starting Step #3 - "analyzer"
Step #3 - "analyzer": Already have image (with digest): us.gcr.io/gae-runtimes/buildpacks/java11/builder:java11_20200223_11_0_RC00
Step #3 - "analyzer": ERROR: failed to access previous image: could not parse reference: us.gcr.io/**google.com:abc-xyz**/app-engine-tmp/ttl-7d/default/buildpack-app:latest
Finished Step #3 - "analyzer"
ERROR
ERROR: build step 3 "us.gcr.io/gae-runtimes/buildpacks/java11/builder:java11_20200223_11_0_RC00" failed: step exited with non-zero status: 1

-Thanks

**Comment by bendory** [comment]
Closing.

A domain-scoped project like "google.com:<project>" is Google-internal-only. If this issue is still relevant, please file an internal bug, as the details are not relevant to the public.
