### ISSUE TITLE
gcloud builders should set CLOUDSDK_CORE_DISABLE_PROMPTS=1 ?

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/cloud-builders#647]
Most CI/CD tutorials out there using gcloud use `CLOUDSDK_CORE_DISABLE_PROMPTS=1`. Perhaps the `gcloud` builder should set it, too? 

I can't imagine a case where users would not want this set in a build environment.

This saves users from typing -q/--quiet to every command.

**Comment by ahmetb** [comment]
`gcloud config set core/disable_prompts true` is an alternative.

**Comment by bendory** [comment]
Closing as obsolete, reference https://github.com/GoogleCloudPlatform/cloud-builders/issues/638
