### ISSUE TITLE
Docker volume rights are messed up if USER instruction is specified in docker image 

### ISSUE THREAD

**Issue by maxarndt** [GoogleCloudPlatform/cloud-builders#648]
## Affected builder image

`gcr.io/cloud-builders/docker`

## Expected Behavior

If I use a docker image which uses the [`USER` instruction](https://docs.docker.com/engine/reference/builder/#user) the files of a bound volume belong to the configured user and are not longer owned by `root`. Therefore I pushed the minimal docker image [`maxys/minimal-user-test`](https://hub.docker.com/r/maxys/minimal-user-test) to docker hub. 

```
$ docker run --rm -v /some/dir/build:/workspace maxys/minimal-user-test:latest -c "whoami && ls -la /workspace"
pptruser
total 2436
drwxr-xr-x 30 pptruser pptruser     960 Apr 14 13:26 .
drwxr-xr-x  1 root     root        4096 Apr 14 14:28 ..
-rw-r--r--  1 pptruser pptruser   12954 Apr  9 06:36 0dc0950a.b15d63c8.js
-rw-r--r--  1 pptruser pptruser   85560 Apr  9 06:36 11.a09b91c1.js
-rw-r--r--  1 pptruser pptruser    4916 Apr  9 06:36 17896441.849d6f89.js
-rw-r--r--  1 pptruser pptruser   10034 Apr  9 06:36 1a25ec0b.9b60e0d3.js
-rw-r--r--  1 pptruser pptruser   16324 Apr  9 06:36 2.2e0a5749.js
-rw-r--r--  1 pptruser pptruser    1348 Apr  9 06:36 3d9c95a4.dd0cea4c.js
```

## Actual Behavior

Doing the same with `gcr.io/cloud-builders/docker` on Cloud Build leads to loss of write access because files are owned by `root`:
```
$ cat test.yaml
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', '--rm', '-v', '/workspace/build:/workspace', 'maxys/minimal-user-test:latest', '-c', 'whoami && ls -la /workspace']
$ gcloud builds submit --config test.yaml .
...
Status: Downloaded newer image for maxys/minimal-user-test:latest
pptruser
total 2464
drwxr-xr-x 8 root root    4096 Apr 14 14:31 .
drwxr-xr-x 1 root root    4096 Apr 14 14:31 ..
-rw-r--r-- 1 root root   12954 Apr  9 06:36 0dc0950a.b15d63c8.js
-rw-r--r-- 1 root root   85560 Apr  9 06:36 11.a09b91c1.js
-rw-r--r-- 1 root root    4916 Apr  9 06:36 17896441.849d6f89.js
-rw-r--r-- 1 root root   10034 Apr  9 06:36 1a25ec0b.9b60e0d3.js
-rw-r--r-- 1 root root   16324 Apr  9 06:36 2.2e0a5749.js
-rw-r--r-- 1 root root    1348 Apr  9 06:36 3d9c95a4.dd0cea4c.js
PUSH
DONE
...
```

## Steps to Reproduce the Problem

1. Create some test data

        mkdir build && touch build/my_test_file
1. Run the following locally

        docker run --rm -v /some/dir/build:/workspace maxys/minimal-user-test:latest -c "whoami && ls -la /workspace"
2. Create a simple Cloud Build config (`test.yaml`)

        steps:
        - name: 'gcr.io/cloud-builders/docker'
          args: ['run', '--rm', '-v', '/workspace/build:/workspace', 'maxys/minimal-user-test', '-c', 'whoami && ls -la /workspace']
3. Run on Cloud Build

        gcloud builds submit --config test.yaml .

## Additional Info

- Mounting the directory to `/data` or `/app` does not make any difference.
- A comparison with `docker inspect` does not show a difference in the `Mounts` property

        "Mounts": [
            {
                "Type": "bind",
                "Source": "/some/dir/build",  // this one is "/workspace/build" on GCP
                "Destination": "/workspace",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],

Why does Docker behave differently on GCP than locally? I'm using docker `19.03.8` on MacOS. 

Because of this issue you do not have any longer write access to your volume. How can this be fixed?

**Comment by bendory** [comment]
Closing as obsolete; reference https://github.com/GoogleCloudPlatform/cloud-builders/issues/670

Please note that if you are having issues with the hosted Google Cloud Build service, these should be reported to Google Cloud Support.
