### ISSUE TITLE
Gradle JDK 11-13

### ISSUE THREAD

**Issue by rshibley** [GoogleCloudPlatform/cloud-builders#649]
Need to have Gradle support with JDK 11 or 13 to compile spring boot project. Currently the available on is JDK-8. Please Advise

**Comment by irvifa** [comment]
I believe you can use available images in https://hub.docker.com/_/gradle, since the content of Gradle image in there is also just the same as the one available in the official images.

**Comment by bendory** [comment]
closing as obsolete; see also https://github.com/GoogleCloudPlatform/cloud-builders/issues/665
