### ISSUE TITLE
Reduce the number of pods in the deployement

### ISSUE THREAD

**Issue by andresetevejob** [GoogleCloudPlatform/cloud-builders#653]
## Affected builder image

`gcr.io/cloud-builders/docker`

## Expected Behavior
I want to have 1 pod in my deployment, when i use gke-deploy

## Actual Behavior
Now i have 5 pods by default
## Steps to Reproduce the Problem

this my cloudbuild yaml file

steps:
    - name: gcr.io/cloud-builders/docker
      args: ["build", "-t", "gcr.io/$PROJECT_ID/kojitapp:$REVISION_ID", "."]
    - name: "gcr.io/cloud-builders/docker"
      args: ["push", "gcr.io/$PROJECT_ID/kojitapp:$REVISION_ID"]  
    - name: 'gcr.io/cloud-builders/gke-deploy:stable'
      args:
      - 'run'
      - '--image=gcr.io/$PROJECT_ID/kojitapp:$REVISION_ID'
      - '--location=us-west1-a'
      - '--cluster=hello-cluster'
      - '--expose=80'
images: ["gcr.io/$PROJECT_ID/kojitapp:$REVISION_ID"]

## Additional Info
how to do, to reduce number of pod to 1

**Comment by bendory** [comment]
For help in using the hosted GCB service, please contact your Google support team or file an issue in the public issue tracker:
https://issuetracker.google.com/issues/new?component=190802&template=1162743
