### ISSUE TITLE
kustomize

### ISSUE THREAD

**Issue by feloy** [GoogleCloudPlatform/cloud-builders#660]
Hi,

I'l trying to build an operator developed with kubebuilder (https://github.com/kubernetes-sigs/kubebuilder) using Cloud Build.

The build chain makes use of the kustomize command, especially the "kustomize edit" operation.

Is there some image in the cloud-builders repository containing this command? I cannot find it in the kubectl nor gke-deploy image.

**Comment by bendory** [comment]
`kustomize` exists as a [community builder](https://github.com/GoogleCloudPlatform/cloud-builders-community/tree/master/kustomize).
