### ISSUE TITLE
Promote `gcr.io/cloud-marketplace-containers/google/bazel` for `bazel` users

### ISSUE THREAD

**Issue by bendory** [GoogleCloudPlatform/cloud-builders#667]

**Comment by ImJasonH** [comment]
You might be able to just merge https://github.com/GoogleCloudPlatform/cloud-builders/pull/504, if nobody is still using the special-case logic.

**Comment by bendory** [comment]
> You might be able to just merge #504, if nobody is still using the special-case logic.

Not an unreasonable approach, but rather than try to chase that down I'm going to follow the same approach I'm using in other deprecations:

- Add a deprecation notice pointing users to an official replacement
- Stop building the image / stop making updates
- Leave the existing built image in place so that current users are not broken if they choose not to move

**Comment by kyessenov** [comment]
Can we install tzdata into bazel image please? `/usr/share/zoneinfo` is missing in the xenial image.

**Comment by wallrj** [comment]
In the cert-manager release tooling we'd like to use `gcr.io/cloud-marketplace-containers/google/bazel` but  we wanted a Bazel 4.2.1 image and couldn't find one, so we switched to `gcr.io/cloud-builders/bazel`.
Unfortunately, that Docker image doesn't have any tags, only digests:
 * https://github.com/cert-manager/release/pull/47

**Comment by haroonc** [comment]
It seems `gcr.io/cloud-marketplace-containers/google/bazel` is not updated. Therefore it does not seem appropriate to deprecate this builder image in favour of marketplace image.
