### ISSUE TITLE
Ubuntu Dockerfile out of date

### ISSUE THREAD

**Issue by haf** [GoogleCloudPlatform/cloud-builders#67]
Compare https://docs.docker.com/engine/installation/linux/ubuntu/#install-using-the-repository with the Dockerfile https://github.com/GoogleCloudPlatform/cloud-builders/blob/master/docker/Dockerfile

 - DIfferent source
 - Different way of fetching the keys
 - Renamed package
 - Could move from trusty to xenial.

Mention me with at-haf if it's urgent I follow this thread.

**Comment by bendory** [comment]
Thank you, we will address this at the time of our next Docker version upgrade.
