### ISSUE TITLE
Promote https://hub.docker.com/_/docker images for `docker` users

### ISSUE THREAD

**Issue by bendory** [GoogleCloudPlatform/cloud-builders#670]

**Comment by killthekitten** [comment]
@bendory is there a press release or any note regarding #680? Is it still a deprecation? 

The language has changed from deprecation to promoting official images, but it's not clear what consequences does it have for the end user.

**Comment by bendory** [comment]
There is no deprecation. We have an internal plan to offer better versions of the `cloud-builders` that will offer better support, and we also plan to continue to notify users of the community-supported images as alternative choices.

Once we have full agreement + all the appropriate internal approvers, the main README will be updated to clarify the plans.

**Comment by killthekitten** [comment]
Makes sense, thanks for the clarification!

**Comment by bendory** [comment]
Of course -- and thank you for keeping us honest by asking! You'll note that I updated the main README with a "[Future Direction](https://github.com/GoogleCloudPlatform/cloud-builders/#future-direction)" section.

**Comment by killthekitten** [comment]
Yes, noted 👍 I'm excited to move to official repos, thanks for the great work!
