### ISSUE TITLE
Publish builders to eu.gcr.io

### ISSUE THREAD

**Issue by haf** [GoogleCloudPlatform/cloud-builders#68]
It would feel better if the builders are available in the European Union as well;

 - legally
 - bandwidth-wise

So this is a suggestion to publish the images on `eu.gcr.io` as well as `gcr.io`.

Please at-haf me if it's urgent I reply to this issue.

**Comment by bendory** [comment]
Hi @haf, thanks for the suggestion. Can you please help us understand the use case that makes you think this is important? Have you experienced build latencies that make you think that there are issues with registry proximity?

**Comment by bendory** [comment]
Since you haven't replied, and since we don't know of a use case where explicitly hosting the builders in the EU is helpful, I'm closing this issue. Please re-open and reply to my questions above if you still think this is an important issue.

**Comment by haf** [comment]
Having operations in other countries than the european union causes problems/has implications for us when we need to follow GDPR.

**Comment by bendory** [comment]
On May 3, 2017, a blog post described [our commitment to GDPR on GCP](https://blog.google/topics/google-cloud/google-cloud-our-commitment-general-data-protection-regulation-gdpr/).

My understanding is that our choices regarding where we host our supported build steps does not impact our customers' ability to adhere to GDPR. (Supported build steps are Google's data, not customer data.)

Disclaimer: I'm a software engineer, not an attorney, so nothing I say should be taken as legal advice.
