### ISSUE TITLE
docker build error Unknown flag: --cache-from

### ISSUE THREAD

**Issue by mswank923** [GoogleCloudPlatform/cloud-builders#681]
## Affected builder image
`gcr.io/cloud-builders/docker`

## Expected Behavior
Docker builder should build my container image using the given base image.

## Actual Behavior
Builder errors out when encountering "unknown" flag --cache-from
This flag is on the official docker docs, under the docker build reference.

## Steps to Reproduce the Problem

1. Add step to your cloudbuild config YAML to pull an image to use as cache:
```
# Pull base image to prevent exceeding build timeout
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'pull'
  - '$_IMAGE:base'
```
2. Add step to use the docker cloud-builder with "build" as the command and "--cache-from" as a flag. Provide the image that has been pulled:
```
# build container image
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--file=./django/docker/Dockerfile-va-from-base'
  - '--cache-from $_IMAGE:base'
  - '-t $_IMAGE:$_TAG-cloudbuild'
  - '.'
```
3. Submit the build. This is what I used:
`gcloud builds submit --config=gcloud-build-config.yaml ../../../`

## Additional Info
Here is the error I received:
```
unknown flag: --cache-from gcr.io/hytrust-vitals/vitals_app:base
```

**Comment by bendory** [comment]
I think that the issue is your `cloudbuild.yaml` formatting. You have:

```
# build container image
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--file=./django/docker/Dockerfile-va-from-base'
  - '--cache-from $_IMAGE:base'
  - '-t $_IMAGE:$_TAG-cloudbuild'
  - '.'
```

but I think you mean:

```
# build container image
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--file=./django/docker/Dockerfile-va-from-base'
  - '--cache-from=$_IMAGE:base'
  - '-t $_IMAGE:$_TAG-cloudbuild'
  - '.'
```

Note that I added an `=` sign in your `--cache-from` arg.

The hint was in the error message, which said:
`unknown flag: --cache-from gcr.io/hytrust-vitals/vitals_app:base`
because indeed the string "cache-from gcr.io/hytrust-vitals/vitals_app:base" is not a legitimate flag!
