### ISSUE TITLE
gke-deploy: possible to support kubectl create?

### ISSUE THREAD

**Issue by compressed** [GoogleCloudPlatform/cloud-builders#688]
## Affected builder image

`gcr.io/cloud-builders/gke-deploy`

## Expected Behavior

I was trying to use `gke-deploy` for job creation, but it seems that the image only supports `kubectl apply`. My use case needs `kubectl create` because I want to make a job using `generateName` parameter which means `kubectl apply` won't work (see: https://github.com/kubernetes/kubernetes/issues/44501). It would be great to get all the benefits of `gke-deploy` if it can support `create`.

**Comment by ChrisGe4** [comment]
We are not prioritizing enhancements to gke-deploy at this time, but please feel free to submit your own PRs

**Comment by bendory** [comment]
Closing as `wontfix` after 5+ months of inactivity. As previously noted, feel free to send a PR for consideration.
