### ISSUE TITLE
run triggers CLI broke at 9:15 am or so this morning

### ISSUE THREAD

**Issue by deanorderly** [GoogleCloudPlatform/cloud-builders#699]
These two steps were working all morning until a few minutes ago.  I have not touched the trigger and you can see the list command is working and showing the trigger still.  Either something is wrong or the message back to the customer needs better messaging on what we did wrong...  

```
Deans-MacBook-Pro:googleBuild dean$ gcloud alpha builds triggers list
---
createTime: '2020-06-17T20:47:13.580770675Z'
description: Push to any branch
filename: java/googleBuild/cloudbuild.yaml
github:
  name: orderly
  owner: OrderlyHealth
  push:
    tag: neverRunByTag.*
id: 48d9a864-65db-478a-82a9-25b554d0492f
name: default-push-trigger-1
tags:
- github-default-push-trigger
Deans-MacBook-Pro:googleBuild dean$ gcloud beta builds triggers run default-push-trigger-1 --branch master
ERROR: (gcloud.beta.builds.triggers.run) NOT_FOUND: Requested entity was not found.
Deans-MacBook-Pro:googleBuild dean$
```

**Comment by bendory** [comment]
To report an issue with the hosted Google Cloud Build service, please report it to your Google Cloud Support team or use the public issue tracker at
https://issuetracker.google.com/issues/new?component=190802&template=1162743.

I've gone ahead and filed this issue for you: https://issuetracker.google.com/issues/159329218

I'm closing this Github issue as off-topic.
