### ISSUE TITLE
Don't print messages to stdout in kubectl.bash

### ISSUE THREAD

**Issue by kehao95** [GoogleCloudPlatform/cloud-builders#706]
## Affected builder image
gcr.io/cloud-builders/kubectl

## Expected Behavior
expecting `kubectl get .... > res.yaml` working

## Actual Behavior
`res.yaml` will be messed up with stdout from `kubectl.bash`
```
Running: gcloud container clusters get-credentials --project="***" --zone="us-central1" "***"

   <ACTUAL  res.yaml BODY HERE>

                   ***** NOTICE *****

Official `cloud-sdk` images, including multiple tagged versions across multiple
platforms, can be found at
https://github.com/GoogleCloudPlatform/cloud-sdk-docker.

Suggested alternative images include

    gcr.io/google.com/cloudsdktool/cloud-sdk

Please note that the `kubectl` entrypoint must be specified when using this
image or a version-tagged variant.

                ***** END OF NOTICE *****

```

## Additional Info
`kubectl` provides only stdout export and we need to use `> file.yaml` for persistent. The default output from kubectl.bash is breaking it. 
Need to remove anything from `stdout` and show necessary ones in `stderr` only.

**Comment by bendory** [comment]
closed by #707
