### ISSUE TITLE
Maven dependencies to private Github Repo

### ISSUE THREAD

**Issue by williamwxz** [GoogleCloudPlatform/cloud-builders#710]
I followed the [Instruction to add github dependencies](https://docs.github.com/en/github/visualizing-repository-data-with-graphs/exploring-the-dependencies-of-a-repository), I can build the package successfully because of the ~/.m2/settings.xml setup. However, in cloud build, how can it build maven package with private repo access? 

## Affected builder image

- 'gcr.io/cloud-builders/mvn'
- 'gcr.io/cloud-builders/gcloud'

(e.g., `gcr.io/cloud-builders/docker`)

## Steps to Reproduce the Problem

1. gcloud app deploy
2.
3.

**Comment by bendory** [comment]
To request help with the hosted Google Cloud Build service, please report your issue to your Google Cloud Support team or use the public issue tracker at
https://issuetracker.google.com/issues/new?component=190802&template=1162743.

I'm closing this issue as off-topic.

**Comment by bendory** [comment]
Note: these guides from the public documentation for the hosted Google Cloud Build Service may be helpful:
- https://cloud.google.com/cloud-build/docs/access-private-github-repos
- https://cloud.google.com/cloud-build/docs/securing-builds/use-encrypted-secrets-credentials
