### ISSUE TITLE
create trigger with gcloud cli.. but dockerfile-image value cannot changed

### ISSUE THREAD

**Issue by ziippy** [GoogleCloudPlatform/cloud-builders#716]
I want to create the trigger using cli

so, I try
**gcloud beta builds triggers create cloud-source-repositories \
    --repo=my-repo \
    --branch-pattern=^master$ \
    --dockerfile=Dockerfile \
    --dockerfile-dir=my-optional-kubernetes-engine \
    --dockerfile-image=gcr.io/$PROJECT_ID/aaabbbccc:$COMMIT_SHA \
    --name=mytrigger**

in cloudshell, I got a success message

But, in the console
The image name is not changed
![image](https://user-images.githubusercontent.com/19854237/91927034-91881e80-ed13-11ea-8f5c-fc282e56b321.png)

I expected the image name is to "gcr.io/ziippy-project5/**aaabbbccc**:$COMMIT_SHA"
not "gcr.io/ziippy-project5/**my-repo**:$COMMIT_SHA"

How can I change the image name?

is the gloud beta cli bug?

**Comment by bendory** [comment]
To report an issue with the hosted Google Cloud Build service, please report it to your Google Cloud Support team or use the public issue tracker at
https://issuetracker.google.com/issues/new?component=190802&template=1162743.
