### ISSUE TITLE
Adding Power support for image gcr.io/cloud-builders/mvn

### ISSUE THREAD

**Issue by snehlatamohite** [GoogleCloudPlatform/cloud-builders#717]
Hi All,

We have a requirement for using the  image gcr.io/cloud-builders/mvn image on Power(ppc64le) architecture for tektoncd/pipeline tasks execution on P.

However, the images available here - https://console.cloud.google.com/gcr/images/cloud-builders/GLOBAL/mvn?gcrImageListsize=30 have support for "amd64" only as seen below
docker image inspect gcr.io/cloud-builders/mvn | grep Arch
"Architecture": "amd64",

I was able to build this image locally on a using "3.6-jdk-8-openj9" base image on Power machine and validate it successfully and was looking for help in making the image @ gcr.io, multi-arch

Thank you!!

**Comment by bendory** [comment]
Hi @snehlatamohite, thanks for your question.

First, a clarification: `docker image inspect gcr.io/cloud-builders/mvn | grep Arch` will indeed tell you the architecture supported by your _local_ image, but it doesn't tell you about what is in the actual repository. When you `docker pull` an image, it first pulls the manifest which lists all available architectures. Then it selects the architecture (based on the machine where it is running), and pulls that actual image. So `docker image inspect` will tell you the architecture of the image you pulled, unless you happened to build the image locally.

That said, this repo is focused on providing the build steps used with the hosted Google Cloud Build service, and we do not provide support for multi-architecture images at this time. I would suggest using an appropriate [community-supported Maven image from Dockerhub](https://hub.docker.com/_/maven).
