### ISSUE TITLE
[FR] Add compiled crcmod to gcr.io/cloud-builders/gsutil

### ISSUE THREAD

**Issue by junoatscroll** [GoogleCloudPlatform/cloud-builders#727]
## Detailed Feature Information

**Which builder is relevant to this request?**
gcr.io/cloud-builders/gsutil

**Is your feature request related to a problem? Please describe.**
When running `gcr.io/cloud-builders/gsutil cp` to download a large file, the following warning appears:
```
==> NOTE: You are downloading one or more large file(s), which would
run significantly faster if you enabled sliced object downloads. This
feature is enabled by default but requires that compiled crcmod be
installed (see "gsutil help crcmod").
```

Sure enough, `docker run gcr.io/cloud-builders/gsutil version -l` shows `compiled crcmod: False`

**Describe the solution you'd like**
Add compiled crcmod to the gcr.io/cloud-builders/gsutil image. There are instructions in `gsutil help crcmod`

**Describe alternatives you've considered**
A workaround would require building my own image with gsutil inside. It seems like it should come in the official cloud-builder image.

**Additional context**
N/a

**Comment by bendory** [comment]
Thank you for reporting this issue. It looks like we missed installing crcmod as part of the python3 migration. The attached PR should resolve the issue.
