### ISSUE TITLE
Curl request for running container returning connection refused

### ISSUE THREAD

**Issue by nehakapila94** [GoogleCloudPlatform/cloud-builders#736]
I am creating cloudbuild.yaml to run the docker image. Then I try to curl the localhost for verification.
But everytime curl gives me connection refused.
I have tried multiple options. Please suggest

`- name: 'gcr.io/cloud_builders/docker'
  id: RUN-DOCKER-IMAGE
  entrypoint: bash
  args:
  - '-c'
  - |
    docker run -d -p 5000:5000 --network cloudbuild gcr.io/${PROJECT_ID}/${_IMAGE_NAME} && sleep 45 && curl -v localhost:5000/predict
`

**Comment by bendory** [comment]
To report an issue with the hosted Google Cloud Build service, please report it to your Google Cloud Support team or use the public issue tracker at
https://issuetracker.google.com/issues/new?component=190802&template=1162743.
