### ISSUE TITLE
Pass environment --dev in angular ng build command dockerfile

### ISSUE THREAD

**Issue by MariumHashmiBM** [GoogleCloudPlatform/cloud-builders#740]
Need guidance on how to pass environment --dev in angular ng build command dockerfile
the dockerfile has following line
## Build the angular app in production mode and store the artifacts in dist folder
RUN npm run ng build -- --prod --output-path=dist

how can we pass --prod as a variable in this docker file which can be picked up by cloud build?

**Comment by bendory** [comment]
For questions or issues with the hosted Google Cloud Build service, please contact your Google Cloud Support representative or report your issue using [Google's public issue tracker](https://issuetracker.google.com/issues/new?component=190802&template=1162743).

This GitHub issue tracker is intended for bugs with the officially supported builder images __only__.

Closing this issue as "Off-Topic".
