### ISSUE TITLE
[BUG] Bazel image notice breaks bazel query

### ISSUE THREAD

**Issue by mkbehr** [GoogleCloudPlatform/cloud-builders#743]
## Affected builder image

gcr.io/cloud-builders/bazel

## Expected Behavior

`bazel query` from a bash entrypoint prints only the query results to stdout, so that other tools can parse the output.

## Actual Behavior

`bazel query` sometimes also prints a notice about an alternative supported bazel image to stdout, alongside the query results. (Looks like this happens randomly.)

## Steps to Reproduce the Problem

1. Create a build step that uses the gcr.io/cloud-builders/bazel image and a bash entrypoint, with arguments that tell bash to call bazel query and consume its results, e.g. -c "bazel query [...] | xargs bazel build"
2. Run the build until the alternative image notice randomly triggers in the bazel query invocation.

## Additional Info

Printing the message to stderr instead should fix this.

**Comment by bendory** [comment]
Sorry about this; we removed the notices for other builders when Docker changed their [free tier](https://www.docker.com/pricing) to limit pulls on public images. Obviously I forgot to remove this notice. PR coming shortly.

**Comment by mkbehr** [comment]
Thanks for the quick fix!
