### ISSUE TITLE
How to pass parameters to docker run

### ISSUE THREAD

**Issue by GabrielLasso** [GoogleCloudPlatform/cloud-builders#747]
Idk if here is the best place to ask this, but I am trying to run a cypress pipeline using GCB, but it crashes when rinning inside docker.

The fix for this issue, as described [here](https://github.com/cypress-io/cypress/issues/350), is to run the docker with `--ipc=host`.

But looking in the documentation, I couldn't find how I pass parameters to docker run in GCB.

Can anyone help me?

**Comment by bendory** [comment]
For questions or issues with the hosted Google Cloud Build service, please contact your Google Cloud Support representative or report your issue using [Google's public issue tracker](https://issuetracker.google.com/issues/new?component=190802&template=1162743).

This GitHub issue tracker is intended for bugs with the officially supported builder images __only__.

Closing this issue as "Off-Topic".
