### ISSUE TITLE
[BUG] Running Dockerfile in Cloud Build does not have GCP credentials in environment.

### ISSUE THREAD

**Issue by ssm951** [GoogleCloudPlatform/cloud-builders#750]
## Notice

**If you are reporting an issue with the hosted Google Cloud Build service, please contact your Google Cloud Support representative or report your issue using [Google's public issue tracker](https://issuetracker.google.com/issues/new?component=190802&template=1162743).**

This GitHub issue tracker is intended for bugs with the officially supported builder images __only__. This issue tracker is __not__ the right place to report issues with triggers or notifications.

If you're not sure where to report your issue, use [Google's public issue tracker](https://issuetracker.google.com/issues/new?component=190802&template=1162743).

## Affected builder image

`gcr.io/cloud-builders/docker`
`gcr.io/cloud-builders/mvn:appengine`

## Expected Behavior

I am trying to test my Spring Boot project in an environment similar to App Engine before deployment. I have created a GitHub build trigger that would build and run `mvn verify` on my project through this Dockerfile:

```
FROM gcr.io/cloud-builders/mvn:appengine

ENV SPRING_PROFILES_ACTIVE=prod
COPY ./src /tmp/src
COPY pom.xml /tmp/

RUN cd /tmp; mvn --no-transfer-progress verify package;
```

When running a cloud build trigger on a Dockerfile, the Docker instance should have the GOOGLE_APPLICATION_CREDENTIALS environment variable set and service account credentials accessible according to the [README here](https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/docker#gcr-credentials).

## Actual Behavior
Instead of getting the credentials when running my Spring Boot tests in the docker container, I get the following exception, causing my build to fail:

```
Caused by: java.io.IOException: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
	at com.google.auth.oauth2.DefaultCredentialsProvider.getDefaultCredentials(DefaultCredentialsProvider.java:134) ~[google-auth-library-oauth2-http-0.22.0.jar:na]
	at com.google.auth.oauth2.GoogleCredentials.getApplicationDefault(GoogleCredentials.java:119) ~[google-auth-library-oauth2-http-0.22.0.jar:na]
	at com.google.auth.oauth2.GoogleCredentials.getApplicationDefault(GoogleCredentials.java:91) ~[google-auth-library-oauth2-http-0.22.0.jar:na]
	at com.google.api.gax.core.GoogleCredentialsProvider.getCredentials(GoogleCredentialsProvider.java:67) ~[gax-1.60.0.jar:1.60.0]
	at org.springframework.cloud.gcp.core.DefaultCredentialsProvider.getCredentials(DefaultCredentialsProvider.java:67) ~[spring-cloud-gcp-core-1.2.7.RELEASE.jar:1.2.7.RELEASE]
	at com.google.cloud.firestore.FirestoreOptions$Builder.build(FirestoreOptions.java:210) ~[google-cloud-firestore-2.1.0.jar:2.1.0]
	... 137 common frames omitted
```

## Steps to Reproduce the Problem

1. Create a Cloud Build trigger to run the Dockerfile above from a repo.
2. The repo has Spring Cloud dependencies and the project requires GCP credentials.
2. Have the trigger run.
3. Check the logs to see that the build failed due to the lack of the credentials in the environment.

## Additional Info

I have found a solution to my problem before posting this, but it doesn't negate the issue:

I chose to directly reference `mvn:appengine` in a `cloudbuild.yaml` file to be run in Cloud Build instead and run mvn commands that way. My tests passed, being able to get the credentials from the environment automatically. It shows that the issue is that Docker wasn't getting the credentials when it is being called the way I was doing above. If this isn't a bug, please help clarify this in the documentation. It seems to conflict with the [README here](https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/docker#gcr-credentials). I am willing to help with that if needed.

Here was the cloudbuild.yaml file I made for it:
```
steps:
  - name: 'gcr.io/cloud-builders/mvn:appengine'
    args:
      - '--no-transfer-progress'
      - '-Ptest'
      - verify
      - package
    entrypoint: mvn
    env:
      - 'SPRING_PROFILES_ACTIVE=prod'
```

**Comment by bendory** [comment]
@loosebazooka Can you offer any guidance on this? Not clear to me if this is an issue with the builder itself or with the user's setup.

**Comment by silanpa** [comment]
Maybe you need to pass GOOGLE_APPLICATION_CREDENTIALS like environment variable to the inside of the container.
```

FROM gcr.io/cloud-builders/mvn:appengine
ARG GOOGLE_APPLICATION_CREDENTIALS

ENV SPRING_PROFILES_ACTIVE=prod
COPY ./src /tmp/src
COPY pom.xml /tmp/

RUN cd /tmp; mvn --no-transfer-progress verify package;
```

That occurs because when the container run is isolated to the environment in the platform.

**Comment by dantheperson** [comment]
Passing GOOGLE_APPLICATION_CREDENTIALS doesn't fix it for me unfortuantly.

In my case i am doing a docker run, so i tried
 `docker run --env TAG_NAME=${TAG_NAME} --env GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}`

however it didn't work.  A `printenv` reveals there is no variable to pass
        

> Step #4 - "deploy": Already have image (with digest): gcr.io/cloud-builders/docker
>         Step #4 - "deploy": ------------------
>         Step #4 - "deploy": HOSTNAME=d06f22596938
>         Step #4 - "deploy": COMMIT_SHA=a40f3870cb49a9c84406451ab257a7f1b29912dc
>         Step #4 - "deploy": BRANCH_NAME=develop
>         Step #4 - "deploy": PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
>         Step #4 - "deploy": PWD=/workspace
>         Step #4 - "deploy": PROJECT_ID=xm-cloudbuild
>         Step #4 - "deploy": DEPLOY_ENV=
>         Step #4 - "deploy": BUILD_ID=c589ea46-5d80-4b03-a3dc-33eb947fb4a9
>         Step #4 - "deploy": SHLVL=1
>         Step #4 - "deploy": HOME=/builder/home
>         Step #4 - "deploy": DEBIAN_FRONTEND=noninteractive
>         Step #4 - "deploy": BUILDER_OUTPUT=/builder/outputs
>         Step #4 - "deploy": TAG_NAME=
>         Step #4 - "deploy": _=/usr/bin/printenv
>         Step #4 - "deploy": ------------------

**Comment by loosebazooka** [comment]
with cloud run already designed to run on containers, what value are you trying to get from running this inside docker?

**Comment by dantheperson** [comment]
Found the solution on a closed ticket. Pass the cloudbuild network
`docker run --network=cloudbuild`
https://cloud.google.com/build/docs/build-config-file-schema#network

I think it would be a great help if this was mentioned at https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/docker#gcr-credentials

**Comment by dantheperson** [comment]
> with cloud build already designed to run on containers, what value are you trying to get from running this inside docker?

There is a script that runs first and works out which version of a container to run.  Couldbuild.yaml format is quite limiting on it's own.
