### ISSUE TITLE
[FR] Use ubuntu 20.04 as base image for Docker

### ISSUE THREAD

**Issue by samos123** [GoogleCloudPlatform/cloud-builders#765]
EOL of Ubuntu 16.04 will April 2021

**Comment by bendory** [comment]
Thanks for the request. We don't have plans to change the base image at this time but I'll leave this issue open.

Two interim suggestions:

1. You can of course build your own `docker` image off any base image that you choose.
2. Dockerhub's [`docker` image](https://hub.docker.com/_/docker) may be an appropriate community-supported image.

**Comment by akauppi** [comment]
Based on [this](https://github.com/GoogleCloudPlatform/cloud-builders/blob/master/docker/Dockerfile-base#L1) the current base seems to be Ubuntu 20.04.

I was trying to use it today, but the >800MB size (!!) threw me off.

**Comment by haroonc** [comment]
Fixed by #836
