### ISSUE TITLE
[BUG] when setting a deployment replicas to zero, build times out

### ISSUE THREAD

**Issue by ffissore** [GoogleCloudPlatform/cloud-builders#766]
## Affected builder image

gcr.io/cloud-builders/gke-deploy

## Expected Behavior

When scaling down a deployment (setting its `replicas` to `0`), gke-deploy should call `kubectl apply`, confirm that the number of replicas has changed, and report success.

## Actual Behavior

When scaling down a deployment (setting its `replicas` to `0`), gke-deploy keeps on calling `kubectl get Deployment POD NAME -n NAMESPACE --output=yaml`, until it times out.
It's like its success state depended on having a running deployment, although the goal was indeed to scale it down

## Steps to Reproduce the Problem

1. set up a cloud build pipeline, have it spin up a container with multiple replicas
2. change the replicas to zero, submit the change to cloudbuild, check how it keeps on "polling" the deployment until it times out

**Comment by joonlim** [comment]
Hi Federico, thanks for reporting this issue.

I believe this is an issue that should be fixed. We are not currently prioritizing work for gke-deploy, but please feel free to propose a PR and send it to me.

**Comment by ffissore** [comment]
Hi @joonlim can you point me to when/how this was fixed? we have seen this issue happening this very morning

**Comment by ffissore** [comment]
Sorry, I misread your comment. I'll try to set up a PR with a fix

**Comment by ffissore** [comment]
@joonlim FYI I just created #767
