### ISSUE TITLE
[FR] Add `version` command to gke-deploy, reporting the git SHA used to build it

### ISSUE THREAD

**Issue by ffissore** [GoogleCloudPlatform/cloud-builders#773]
## Detailed Feature Information

**Which builder is relevant to this request?**
gcr.io/cloud-builders/gke-deploy

**Is your feature request related to a problem? Please describe.**
#767 was merged with a fix to #766, but we are still experiencing it. Either the fix was insufficient or it hasn't been deployed to gcr.io yet.
There's no way to know which SHA of this repo `gke-deploy` is based on, so I cannot know if it's just old or if the fix didn't fix.

**Describe the solution you'd like**
Add command `gke-deploy version`: it should print the SHA used to build the binary, and any other information you think is relevant

**Describe alternatives you've considered**
I thought about building it myself and compare the binaries, but I don't know if go builds are deterministic (same code = same binary checksums)

**Comment by joonlim** [comment]
Hi Federico, apologies for responding to this so late. I have returned from leave and am still catching up on things.

It looks like the latest image should have the changes you need. Please let me know if it doesn't.

We aren't prioritizing adding new features to gke-deploy. I'd be happy to take a look at any PRs, though.

**Comment by ffissore** [comment]
I confirm the image has been updated, as we haven't seen the problem occurring any more

**Comment by ffissore** [comment]
As for the `version` command, I'll try to set up a PR

**Comment by haroonc** [comment]
Closing issue as the original reported problem was fixed.
