### ISSUE TITLE
[BUG] Docker image latest uses outdated client 19.03.8 and doesn't match server version 20.10.6

### ISSUE THREAD

**Issue by grobie** [GoogleCloudPlatform/cloud-builders#778]
## Affected builder image

`gcr.io/cloud-builders/docker`

## Expected Behavior

The docker client should match the server version 20.10.6 which was released on May 20th in GCP.

## Actual Behavior

The latest image still points to 19.03.8 as it was pinned in https://github.com/GoogleCloudPlatform/cloud-builders/pull/764. No tagged version for 20.10.6 is available yet.

## Steps to Reproduce the Problem

1. `docker run --rm -it gcr.io/cloud-builders/docker:latest --version`

**Comment by rotilho** [comment]
Are there any plans to fix it? I prefer to use cloud-builders images since they are cached.

**Comment by spiritualpad** [comment]
I think the problem may be that docker-ce only supports up till 19.03 on ubuntu xenial, as referenced in the page https://docs.docker.com/engine/install/ubuntu/

If they'd want to update to docker-ce version 20, they'd have to upgrade the ubuntu version as well.

**Comment by akauppi** [comment]
Seems to be based on Ubuntu 20.0.4 now: https://github.com/GoogleCloudPlatform/cloud-builders/blob/master/docker/Dockerfile-19.03.9#L1

**Comment by ferrarimarco** [comment]
I think https://github.com/GoogleCloudPlatform/cloud-builders/pull/826 fixes this?

**Comment by leeonlee** [comment]
Sorry for the delay. The new version will be cached starting some time next week when we get a release out.
