### ISSUE TITLE
Bazel image with different Ubuntu version as base

### ISSUE THREAD

**Issue by yixizhang** [GoogleCloudPlatform/cloud-builders#78]
Shall we also have `gcr.io/cloud-builders/bazel:xenial`, for example?

Our team is building a CI system on top of cloud builders, and plan to use `bazel test` for our Python3 code base built on top of `Ubuntu:xenial`.

Though we can do it on our own and host the image in cloud registry, however I believe it makes more sense to have the official support in this case.

**Comment by ImJasonH** [comment]
I'm somewhat hesitant to officially support a new version of the `bazel` builder, so maybe it makes sense to either:

1. upgrade the official `bazel` builder to Xenial (we don't have many users today, should be easy enough)
1. ask you to host your own Xenial-based `bazel` builder for now, until we upgrade, which we don't have a timeline for now.

Given those two options, (1) is likely to take longer to come to fruition, and might expand to include upgrading all our images to Xenial at once, for consistency. If (2) is possible in the meantime, that might be a better bet.

WDYT?

**Comment by bendory** [comment]
@yixizhang Can you help us understand your use case? Why does the underlying version of ubuntu matter when you are running the same version of bazel?

**Comment by yixizhang** [comment]
@ImJasonH Thanks for proposing option (1). That sounds good to me in the long term, and I'm okay of doing (2) in the meantime.

@bendory Good question. We are a Python3 + Bazel shop, and as you can imagine we checked in all deps to source code. We can but given limited bandwidth for now we only build deps against Xenial.

So to answer your question, if the underlying ubuntu doesn't match, when we do `bazel test` there's infra error.

**Comment by ImJasonH** [comment]
The bazel builder was updated to be `FROM ubuntu:xenial` in #133

**Comment by yixizhang** [comment]
Thank you!
