### ISSUE TITLE
[BUG] Build failed: function.js does not exist

### ISSUE THREAD

**Issue by pedroarmando** [GoogleCloudPlatform/cloud-builders#780]
## Affected builder image

gcr.io/google.com/cloudsdktool/cloud-sdk

## Expected Behavior

An error message that could help me to understand what was wrong.

## Actual Behavior

ERROR: (gcloud.functions.deploy) OperationError: code=3, message=Build failed: function.js does not exist; Error ID: 7485c5b6

## Steps to Reproduce the Problem

1. Put your source code and your cloudbuild.yaml file in some subdirectory of your repository.

./sub/myCloudFunction
./sub/myCloudFunction/cloudbuild.yaml

2. Set the value of the `source` argument in your `cloudbuild` file to: .
```
steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - myCloudFunction
  - --entry-point=myCloudFunction
  - --runtime=nodejs14
  - --trigger-event=google.storage.object.delete
  - --trigger-resource=some-bucket-name
  - --region=europe-west3  
  - --source=.
 ```
3. Create a trigger build and set the `Cloud Build configuration file location` to: `/myCloudFunction/cloudbuild.yaml`

## Additional Info

I followed this documentation: [Deploying to Cloud Functions](https://cloud.google.com/build/docs/deploying-builds/deploy-functions). Regarding the `source` argument:
> --source=. implies that the source code is in the current working directory.

If I use the absolute path, it works ok: 
```
- --source=./sub/myCloudFunction
```     
This made me lose a lot of time, with a more appropriated error message maybe we could save this time to others developers.

**Comment by bendory** [comment]
This is not the right forum to report this issue; the error messages are not coming from a builder supported by this repository.

1) The "builder" in question is not built in this repo, but rather lives here: https://github.com/GoogleCloudPlatform/cloud-sdk-docker. You can report the issue there. (I tried to transfer the issue to there for you, but I don't have the needed permissions.)

2) Possibly (if ^^^ isn't the right place to report this) this is a bug report for Google Cloud Functions -- it depends on where the error message is coming from.
