### ISSUE TITLE
[FR] Go: Create Docker images for all supported Go versions

### ISSUE THREAD

**Issue by mattayes** [GoogleCloudPlatform/cloud-builders#785]
## Notice

**To request a feature in the hosted Google Cloud Build service, please contact your Google Cloud Support representative or suggest your feature using [Google's public issue tracker](https://issuetracker.google.com/issues/new?component=190802&template=1162743).**

This GitHub issue tracker is intended for feature requests in the officially supported builder images __only__. This issue tracker is __not__ the right place to request features like triggers or notifications.

If you're not sure where to suggest your feature, use [Google's public issue tracker](https://issuetracker.google.com/issues/new?component=190802&template=1162743).

## Detailed Feature Information

**Which builder is relevant to this request?**
Go

**Is your feature request related to a problem? Please describe.**
My team runs into an issue where we often have the max builds (10) going at a time, resulting in high build latency and a poor experience for our engineers. Often, many of these builds are for now-defunct commits, unnecessarily starving the queue.

**Describe the solution you'd like**
We're trying to add a stage to our test Cloud Build configuration that uses the `gcr.io/cloud-buillders/go:debian` Docker image to run a Go script that will cancel these superfluous builds and help us reduce build latency. Some of the features we'd like to use were introduced in [Go 1.16](https://golang.org/doc/go1.16). Unfortunately currently you only support one Go version, [Go 1.15]():
* [Debian](https://github.com/GoogleCloudPlatform/cloud-builders/blob/master/go/Dockerfile.debian#L1)
* [Alpine](https://github.com/GoogleCloudPlatform/cloud-builders/blob/master/go/Dockerfile.alpine#L1)

We'd like Go Cloud Builder Docker images to be available for all [supported Go versions](https://github.com/golang/go/wiki/Go-Release-Cycle#release-maintenance), currently [Go 1.15 and 1.16](https://golang.org/dl/#stable) with [1.17 in beta](https://golang.org/dl/#unstable).

**Describe alternatives you've considered**
We could fork your Dockerfile and change it to Go 1.16. This would only solve the problem for us, though.

**Additional context**
Happy to work on this if y'all are willing.

**Comment by bendory** [comment]
It is challenging right now to roll this buildstep forward at `:latest` due to [1.16 changes in the default behavior of Go modules](https://golang.org/doc/go1.16#go-command):
    "More precisely, the `GO111MODULE` environment variable now defaults to `on`. "

I just created https://github.com/GoogleCloudPlatform/cloud-builders/pull/786 to begin building `1.16` options for users like you who choose to opt-in to the new behavior.

**Comment by mattayes** [comment]
Thanks @bendory!
