### ISSUE TITLE
[BUG] gke-deploy with gcs output fails to copy expanded manifest for application

### ISSUE THREAD

**Issue by jordangarrison** [GoogleCloudPlatform/cloud-builders#790]
## Affected builder image

`gcr.io/cloud-builders/gke-deploy`

## Expected Behavior

I should be able to apply a manifest via a GCS bucket using the following command syntax

```sh
gke-deploy run \
  --cluster my-cluster \
  --location my-region \
  --project my-project-123456 \
  --output gs://deployments-bucket/my-region/my-cluster/my-env/my-app/my-version/epoch \
  --filename manifest/manifest.yaml
```
to deploy a file. The only difference between this and creating the structure locally and then copying the resulting expanded and suggested folders into GCS is a prefix of `gs://deployments-bucket` per the following doc from the gke-deploy cli.

```sh
  -o, --output string           Target directory or GCS path to store suggested and expanded Kubernetes configuration files. Prefix this value with "gs://" to indicate a GCS path. Suggested files will be stored in "<output>/suggested" and expanded files will be stored in "<output>/expanded". (default "./output")
```

## Actual Behavior

When running the above command `gsutil` throws an error from within the gke-command

```
2021/07/28 14:41:23 Downloading file(s) gs://deployments-bucket/my-region/my-cluster/my-env/my-app/my-version/epoch/expanded from /var/folders/rs/7hh5xjzs36lgfbsfbsx8v_p00000gp/T/gke_deploy_temp_241939743.
Error: failed to apply deployment: failed to download configuration files from GCS "gs://deployments-bucket/my-region/my-cluster/my-env/my-app/my-version/epoch/expanded": copy file(s) with gsutil failed: Omitting prefix "gs://deployments-bucket/my-region/my-cluster/my-env/my-app/my-version/epoch/expanded/". (Did you mean to do cp -r?)
CommandException: No URLs matched. Do the files you're operating on exist?
 exit status 1
```

## Steps to Reproduce the Problem

1. Run gke-deploy command using `--output` with the `gs://bucket-name` prefix

## Additional Info

I am currently running this locally to reproduce the issue.

**Comment by joonlim** [comment]
Thanks for finding this issue. I've gone ahead and submitted a fix and will begin the process to update the image used for Cloud Build.

**Comment by jordangarrison** [comment]
Awesome, thanks for the quick response with this @joonlim!
