### ISSUE TITLE
Support for private clusters in kubectl builder [FR]

### ISSUE THREAD

**Issue by lopezvit** [GoogleCloudPlatform/cloud-builders#810]
## Detailed Feature Information

**Which builder is relevant to this request?**
kubectl

**Is your feature request related to a problem? Please describe.**
After creating a private cluster, you can only go down the route of using private pools to connect to the cluster, but since the option `--internal-ip` is not available (via environment variables for example) when calling to `gcloud container clusters get-credentials`, it is impossible to communicate with it.

**Describe the solution you'd like**
Add a new environment variable `CLOUDSDK_USE_INTERNAL_IP` that, when present and equals to `true` makes calling to `gcloud container clusters get-credentials` use the flag `--internal-ip`

**Describe alternatives you've considered**
Use 2 steps instead, with different images (gcloud container/kubectl run)

**Comment by dpkirchner** [comment]
You can pass the `--internal-ip` flag by setting the environment variable `CLOUDSDK_GET_CREDENTIALS_OPTS=--internal-ip`. However, that will not be sufficient to do what you actually want -- even if you're on a private worker pool, there's no way for GCB to access GKE without a convoluted and expensive process. See https://cloud.google.com/build/docs/private-pools/accessing-private-gke-clusters-with-cloud-build-private-pools for details.

**Comment by haroonc** [comment]
Thanks @dpkirchner for the details. Based on above information, I am going to close this issue.
