### ISSUE TITLE
Conditional triggering based on git commit message[FR]

### ISSUE THREAD

**Issue by yashsaini77** [GoogleCloudPlatform/cloud-builders#811]
I want to trigger/skip any step/task based on the Git commit message for example if the cloud build pipeline gets the commit message as "skip-docker-creation" so pipeline should not create docker images. 

I was able to fetch the git commit message using this 

--
steps:
   - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args: [ '-c', 'commit_message=$(git log --format=%B -n 1) && echo "Commit message is ${commit_message}"'] 
    
What should be the next step to configure skipping docker image creation if the git commit message comes as "skip-docker-creation" otherwise the cloud build pipeline should create docker images.

**Comment by bendory** [comment]
Can you please clarify your ask here -- are you requesting a feature enhancement for the `git` builder or asking a question about Google's hosted Cloud Build service?

If the latter, what you are looking for is likely answered by [this doc](https://cloud.google.com/build/docs/automating-builds/create-manage-triggers#skipping_a_build_trigger).

**Comment by yashsaini77** [comment]
Git builder is fine it is providing the commit message. But now what I am searching for is I would like to have a pipeline of having a few tasks and out of which there will be a task of docker image creation. 
What I need is after capturing the git commit message the pipeline should not trigger the task of creating docker image.
Lets say user committed with the message as "skip-docker" so pipeline should be able to listen to it and then not create a docker image if the commit text is "skip-docker". 

Regarding the doc which you have linked, is regarding skipping the build itself. I don't want this I just want to skip a single task of docker creation, not the whole pipeline having various tasks/steps. I just want to skip docker image creation step based on the git commit message.

I am successful with capturing git commit message now I just need the further logic to implement this there is not much available on Google docs for this requirement.

I hope now you get my point.

**Comment by bendory** [comment]
Thanks for clarifying; what you are asking for is support for conditionals. That is not something we are going to implement as a builder feature -- builders are intended to be simple building blocks that you use as steps in larger pipelines, and conditional execution is something you would control on your own either via pipeline configuration or via `bash` scripting, much as you have done in your example.

If I needed what you are describing, I would make my own custom builder image that contains both `docker` and `git` and is able to script the behavior you describe. The [Community Builders repo](https://github.com/GoogleCloudPlatform/cloud-builders-community) contains both simple tool builders (like this repo) as well as builders with more complex behaviors; feel free to submit a PR there for a new builder proposal.
