### ISSUE TITLE
[FR] Provide an official Skaffold builder

### ISSUE THREAD

**Issue by agrinh** [GoogleCloudPlatform/cloud-builders#813]
## Detailed Feature Information

**Which builder is relevant to this request?**
No existing one.

**Describe the solution you'd like**
A new, official cloud builder for use with [Skaffold](https://skaffold.dev/), pre-loaded on GCB nodes, complete with an entrypoint setting up cluster credentials similar to https://github.com/GoogleCloudPlatform/cloud-builders/blob/master/kubectl/kubectl.bash

**Describe alternatives you've considered**
So far using the `gcr.io/k8s-skaffold/skaffold` images, but these are not pre-loaded in GCB and requires manually setting the cluster context.

**Comment by bendory** [comment]
Thanks for the feedback. As you mention, `gcr.io/k8s-skaffold/skaffold` is a suitable image for GCB workloads (and many other uses).

With regard to hosted GCB, please report issues or feature requests to your Google Cloud Support team or use the public issue tracker at
https://issuetracker.google.com/issues/new?component=190802&template=1162743. This repo is for the open-sourced builders only.
