### ISSUE TITLE
[FR] Making the gcloud tool accesible from within other builders to allow for non-bash scripts/tools

### ISSUE THREAD

**Issue by Wazbat** [GoogleCloudPlatform/cloud-builders#815]
## Detailed Feature Information

I am trying to use the gcloud tool from within a node script, specifically within nx, however, neither of the two builders are suitable
The npm builder does not have access to gcloud
And the gcloud builder does not have npm or node installed

In summary, I would like to access the gcloud tool from within other builders like npm. Which would allow me to write scripts in languages other than bash or use tools like nx which require node to be installed

**Which builder is relevant to this request?**
npm or gcloud

**Is your feature request related to a problem? Please describe.**
I'm trying to use nx to deploy a monorepo to google cloud. I've managed to figure out how to grab the last successful commit hash so I've got that sort of working, however I've hit a roadblock.
nx requires node to run. I can use it to only run the build, test, and deploy commands on affected apps which it calculates from the diff.

However, I cannot actually use the deploy script to deploy. If I add something like "gcloud app deploy" inside that app's dcript, when using the npm builder (with entrypoint npx to run the nx cli), it doesn't have access to the gcloud cli

**Describe the solution you'd like**
A version of either of these builders that has a configured gcloud tool available. For example me being able to specify something like `npm:gcloud` to use this specific builder, who's image would have gcloud configured and ready

**Describe alternatives you've considered**
I've tried working around this by writing bash scripts and passing around affected app names with build scripts to workspace text files and then looping through them inside the gcloud image using yet another bash script but it's an overcomplicated mess and I've honestly given up with it at this point.

**Additional context**
I may actually be completely wrong with how I'm thinking this through, if so I'd like to apologise, but I'd also love to see some examples of how others are using tools like nx with Google cloud build, especially seeing how they got around issues like the fact that the git history isn't available

**Comment by bendory** [comment]
We don't have plans to offer these kinds of "combined builders" at this time; as you can imagine, these combinations quickly become an exponential problem.

I would suggest that you base your own builder image on either `gcloud` or `npm` to create your desired toolchain combination.

**Comment by Wazbat** [comment]
Ah, that's fair. It's already possible with some builders by using hacks like
```yaml
- name: "gcr.io/cloud-builders/kubectl"
    entrypoint: python3
    args: ["/workspace/script.py"]
```
However I understand that this isn't intentional

I'm just a JS/TS developer so having to make my own builder is a bit of a barrier to me as I'm not too skilled with docker, specifically basing containers off other images and the effects that might have.
The convenience of cloud build means that you can just throw together a simple yaml file instead of needing to learn yet another tool. However limitations like this mean that I'm very limited in what tools I can use, though I understand why this decision was made
