### ISSUE TITLE
 gcr.io/cloud-builders/git: 'fetch ' is not a git command.

### ISSUE THREAD

**Issue by exaucae** [GoogleCloudPlatform/cloud-builders#820]
## Affected builder image

 `gcr.io/cloud-builders/git`

## Expected Behavior

pull repository 

## Actual Behavior

clones repository then throws error: `git fetch is not recognized`

````
BUILD
Starting Step #0
Step #0: Already have image (with digest): gcr.io/cloud-builders/git
Step #0: Cloning into 'myrepo'...
Step #0: git: 'fetch
' is not a git command. See 'git --help'.
Step #0: 
Step #0: The most similar command is
Step #0: 	fetch
Step #0: error: pathspec 'main?' did not match any file(s) known to git
Finished Step #0
ERROR
ERROR: build step 0 "gcr.io/cloud-builders/git" failed: step exited with non-zero status: 1

````

## Additional Info

Repository is a set of subproject-projects in folder. Not a monorepo. Build is triggered by path. This error appears on newly added sub-jects folders. I'm curious about how it recognizes other commands. The **terraform** build config is the same for all sub-projects:

````tf
 dynamic "step" {
        content {
          name = "gcr.io/cloud-builders/git"
          entrypoint = "bash"
          dir = "$${_PATH}"
          args = [
                  "-c",  
                  <<-EOF
                  git config --global user.name xxx
                  git config --global user.email xxxx
                  git remote set-url origin https://xxx:$$GITHUB_TOKEN@github.com/Awesome/Repo.git
                  git clone https://xxx:$$GITHUB_TOKEN@github.com/Awesome/Repo.git
                  git fetch
                  git checkout $BRANCH_NAME
                  EOF
          ]
          secret_env = [ "GITHUB_TOKEN" ]
        }
      }
````

**Comment by bendory** [comment]
In your bug report, I see this:

> Step #0: git: 'fetch
> ' is not a git command. See 'git --help'.

which indicates to me that you've somehow got an embedded newline in your configuration such that you are trying to execute "git fetch\n" rather than your intended `git fetch`.

Please check your configuration.

**Comment by vongohren** [comment]
To update, this was a windows run the command versus mac it seems. Because I reran the recipe for this build and it worked. So dont understand why that should be a difference.
We got these changes to the recipe when we tried running it from a different OS

![image (1)](https://user-images.githubusercontent.com/1012055/156572202-fc255661-eca0-4d6f-a17b-7e24275782c3.png)

@bendory do you have any thoughts on that?

**Comment by bendory** [comment]
Most likely explanation: Windows `\r\n` vs. Linux `\r`, aka `CRLF` vs `CR`.

**Comment by exaucae** [comment]
I confirm it. Fix for futur reference: `git config --global core.autocrlf false `
