### ISSUE TITLE
Go 1.18 builder

### ISSUE THREAD

**Issue by delfick** [GoogleCloudPlatform/cloud-builders#825]
Hello,

Can we have an official cloud builder for Go 1.18 please?

Thanks

**Which builder is relevant to this request?**
Go

**Is your feature request related to a problem? Please describe.**
I want to upgrade my service to 1.18

**Describe the solution you'd like**
The latest builder is 1.17 and I want to keep using official cloud builder

**Describe alternatives you've considered**
I could use other docker images to build with

**Comment by mwiczer** [comment]
Change is merged. This should be available in the next week.
