### ISSUE TITLE
[FR] Make builders available via Artifact Registry

### ISSUE THREAD

**Issue by haroonc** [GoogleCloudPlatform/cloud-builders#844]
## Make builders available via Artifact Registry

At the moment cloud builders are only available via [Container Registry](https://cloud.google.com/container-registry). Given that [Artifact Registry](https://cloud.google.com/artifact-registry) is the suggested registry for GCP, builder images should be available in Artifact Registry as well.

**Which builder is relevant to this request?**
All officially supported images.

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
All officially supported images should be available via [Artifact Registry](https://cloud.google.com/artifact-registry) 

**Describe alternatives you've considered**
N/A

**Comment by akauppi** [comment]
As a GCP and Cloud Build user, I would be happy to see this. 

However, I can also imagine that nothing really changes. The official images suffer from far larger problems than whether they are stored in registry A or B.

**Comment by Hibrix-net** [comment]
I just receive the following notification from Google:

_Container Registry will be phased out, starting May 15, 2024. Please review the options below for how to upgrade your projects to Artifact Registry._ 

What will happen with the official cloud builders then? Are they going to suddenly disappear?

**Comment by tonymet** [comment]
what are the official URLs for Cloud Builders on artifact registry? 

e..g `gcr.io/cloud-builders/gsutil → us-west1-docker.pkg.dev`

**Comment by tonymet** [comment]
```
 docker pull us-west1-docker.pkg.dev/clo
ud-builders/gs-util
Using default tag: latest
Error response from daemon: Head "https://us-west1-docker.pkg.dev/v2/cloud-builders/gs-util/manifests/latest": denied: Permission "artifactregistry.repositories.downloadArtifacts" denied on resource "projects/cloud-builders/locations/us-west1/repositories/gs-util" (or it may not exist)
```

**Comment by haroonc** [comment]
Hello @tonymet 

We used Artifact Registry (AR) migration option that [supports](https://cloud.google.com/artifact-registry/docs/transition/transition-from-gcr#transition-options) keeping `gcr.io` URLs. Therefore you can continue using `gcr.io/cloud-builders/gsutil`.

However, if you wanted to use AR specific URLs you can use `us-docker.pkg.dev/cloud-builders/gcr.io/gsutil`.

Note: I think the builder image you wanted is **gsutl**, without the **-**
