### ISSUE TITLE
[FR] Add `apt` Cloud Builder

### ISSUE THREAD

**Issue by ymotongpoo** [GoogleCloudPlatform/cloud-builders#846]
## Detailed Feature Information

**Which builder is relevant to this request?**
apt package builder (not exist)

**Is your feature request related to a problem? Please describe.**
As of today, there are no official or company-maintained (i.e. secure and reliable) docker image that contains all required commands to build apt packages.

In order to build apt packages, the following commands should be supported by the image:

* fakeroot
* dpkg-deb
* devscripts
* pbuilder
* cdbs

and the packages required for them are:

* build-essential
* dpkg-dev
* fakeroot
* devscripts
* pbuilder
* cdbs

However, major public Docker images don't contain them. (In minimum cases, having fakeroot and dpkg-deb is enough, but fakeroot is not included in those images). Such as:

* [cimg/base](https://github.com/CircleCI-Public/cimg-base)
* [buildpack-deps:bullseye](https://github.com/docker-library/buildpack-deps/blob/master/debian/bullseye/Dockerfile)

**Describe the solution you'd like**
Add `apt` builder in the collection.

**Describe alternatives you've considered**
Add instructions on how to build apt packages in the Cloud Build official doc.

**Additional context**
Artifact Registry now supports repositories for apt and rpm packages, and more Cloud Build integration with it are expected. (Currently, only `gcloud` command [supports uploading apt package](https://cloud.google.com/artifact-registry/docs/os-packages/debian/store-apt) to the repository, but I hope Cloud Build add features.)

Creating apt and rpm packages in Cloud Build is straightforward steps after creating artifacts such as execution binaries and jar files, and it should makes sense to provide our official builders to support such process, given we have `docker` builder.

**Comment by haroonc** [comment]
Merged builder in  GoogleCloudPlatform/cloud-builders-community#649
