### ISSUE TITLE
[FR] Bump all node images to include latest LTS version

### ISSUE THREAD

**Issue by hspak** [GoogleCloudPlatform/cloud-builders#867]
## Detailed Feature Information

**Which builder is relevant to this request?**
Node, NPM, Yarn

**Is your feature request related to a problem? Please describe.**
All the node images are built only up to node 14. The current node LTS has been on 16 for some time and it's about to be 18 in a moments notice.

While we can use the official node images (which we are today), the cloudbuild pre-cached images saves significant CI time (~30 seconds) and it would be great if these could be kept up to date.

**Describe the solution you'd like**
Cloudbuild should continue to publish the latest node LTS verions for their node images.

**Describe alternatives you've considered**
Alternatively, if Cloudbuild could provide a mechanism to pre-cache our own custom image -- that would be amazing as well. 🙏 🙏 

**Additional context**
There's currently a handful of PR's open for node images that all appear to be stale:
- https://github.com/GoogleCloudPlatform/cloud-builders/pull/795
- https://github.com/GoogleCloudPlatform/cloud-builders/pull/842
- https://github.com/GoogleCloudPlatform/cloud-builders/pull/721

So I believe there's significant interest and would love to see Cloudbuild offer the latest node LTS versions!

**Comment by arvinddayal** [comment]
#869 should take care of this.

**Comment by hspak** [comment]
Thank you for the fast fix!

`gcr.io/cloud-builders/npm:latest` now points to node 19 which isn't an LTS release. I see that `gcr.io/cloud-builders/npm:lts` points to node 18 correctly, but it doesn't appear to be pre-cached. Is there any chance that Cloudbuild would cache the `lts` tag as well?

Here's a screenshot of a sample run showing the `lts` image is not cached for us:
![Screen Shot 2022-10-27 at 10 52 10 AM](https://user-images.githubusercontent.com/841216/198362972-515d8574-c927-4fd9-a1cc-31e53b4c9f55.png)
