### ISSUE TITLE
Move default dependency resolution to internal google maven mirror

### ISSUE THREAD

**Issue by adamresson** [GoogleCloudPlatform/cloud-builders#88]
I noticed the discussion in #50 by @aslo and @skelterjohn 

Does it make sense to point to the internal google cloud maven mirror described here:
https://www.infoq.com/news/2015/11/maven-central-at-google

I can work up a PR is someone thinks it's worthwhile. While it's nice to have a few 'predefined' dependencies, pointing to what should be a 'faster' maven server seems to make sense in my mind.

**Comment by skelterjohn** [comment]
It's in our plans. Perhaps your issue will encourage @aslo to bump some other things to get it done ;)

And PRs are always welcome - cc @aslo on PRs for java builders.

**Comment by aslo** [comment]
@adamresson Yep! This is something that I'm currently looking into :)

Right now there's some performance testing that's underway to ensure that pulling dependencies from the GCP maven mirror is indeed as speedy as we expect. Once we confirm, we'll update this builder image.
