### ISSUE TITLE
[BUG] Java Builder doc currently recommends openjdk (DEPRECATED) should recommend Temurin

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/cloud-builders#895]
## Notice

This GitHub issue tracker is intended for bugs with the officially supported builder images __only__. This issue tracker is __not__ the right place to report issues with triggers or notifications.

If you're not sure where to report your issue, use [Google's public issue tracker](https://issuetracker.google.com/issues/new?component=190802&template=1162743).

## Affected builder image

gcr.io/cloud-builders/javac

## Expected Behavior

Use Temurin instead of OpenJDK.  Google is now a member of the Temurin project.

## Actual Behavior

The README is recommending using [openjdk](https://hub.docker.com/_/openjdk) on hub.docker.com and the Dockerfile uses OpenJDK.  If you visit the hub.docker.com page you'll notice that OpenJDK image is deprecated.

**Comment by leeonlee** [comment]
Fixed wtih https://github.com/GoogleCloudPlatform/cloud-builders/commit/7f4c7792792fb0117230109981846063373e0860
