### ISSUE TITLE
gcloud: crcmod is not fast with gsutil rsync

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/cloud-builders#9]
when I use `gsutil rsync` command in the `gcr.iocloud-builders/gcloud` image, I get this warning:

```
Step #2: WARNING: You have requested checksumming but your crcmod installation isn't
Step #2: using the module's C extension, so checksumming will run very slowly. For help
Step #2: installing the extension, please see "gsutil help crcmod".
```

This is discussed in detail at https://cloud.google.com/storage/docs/gsutil/addlhelp/CRC32CandInstallingcrcmod

### Impact 

When I try to upload my static blog contents (150 MB) to GCS bucket using `gsutil -m rsync`, it takes **60 seconds** in Google Cloud Container Builder as opposed to **5 seconds** in my laptop with a decent Internet connection.

**Comment by bendory** [comment]
Have you tried using the [gsutil](https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/gsutil) build step? I just confirmed that it has crcmod installed:

```
$ docker run --rm gcr.io/cloud-builders/gsutil version -l
gsutil version: 4.22
checksum: 2434a37a663d09ae21d1644f64ce60ca (OK)
boto version: 2.42.0
python version: 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
OS: Linux 3.13.0-108-generic
multiprocessing available: True
using cloud sdk: True
config path: no config found
gsutil path: /builder/google-cloud-sdk/platform/gsutil/gsutil
```
**`compiled crcmod: True`**
```
installed via package manager: False
editable install: False 
```

So using build step `gcr.io/cloud-builders/gsutil -m rsync` should meet your needs. Would you mind giving this a try if you haven't done so already?

**Comment by ahmetb** [comment]
The issue was present in both images. It's now fixed after this bug report.
