### ISSUE TITLE
Builds fail with unreachable commit ID

### ISSUE THREAD

**Issue by kbrownlees** [GoogleCloudPlatform/cloud-builders#90]
I have a trigger setup to run a build when a push occurs to a google source repository, there
seems to be a race condition where sometimes the builds fail with:

error loading template: could not fetch file from source: generic::not_found: unreachable commit IDs: XXX

If I go and manually run the trigger then the build executes fine, so it appears to be trying to fetch the commit before google source repository has fully synced?

Initially it only happened occasionally, but recently most pushes have failed to build.

**Comment by ImJasonH** [comment]
We've had sporadic reports of this issue in the past, it's hard to pin down exactly. We have some reliability improvements planned that might make this go away.
