### ISSUE TITLE
[Feature]: CloudSQL Proxy image

### ISSUE THREAD

**Issue by rimusz** [GoogleCloudPlatform/cloud-builders#92]

**Comment by bendory** [comment]
I am interpreting this as a feature request for a supported builder that runs the [CloudSQL Proxy](https://cloud.google.com/sql/docs/mysql/sql-proxy). Can you please help us understand your use case and what you envision doing with this?

**Comment by rimusz** [comment]
yes, that's correct.
In my I want to have as a step access to CloudSQL instance, e.g. to fetch some client details, and in the next step using [cloud-builders-helm](https://github.com/rimusz/cloud-builders-helm) to install/upgrade the Helm release.
Or something similar which needs data to be fetched from the CloudSQL instance and used in cloudbuilder pipeline.

**Comment by rimusz** [comment]
ideally mysql/postgres clients should come with the CloudSQL Proxy

**Comment by bendory** [comment]
Status update: we're discussing internally and will update the results of that conversation here.

**Comment by Carrotman42** [comment]
Hey @rimusz, I maintain the Cloud SQL Proxy and am happy to help out here. What specifically would you like in the build step? We already release a pre-compiled docker image for public use [0]. Can you describe exactly how you'd like to use it in cloud-builder?

[0] gcr.io/cloudsql-docker/gce-proxy

**Comment by rimusz** [comment]
my case is already explained above in my comment.
1) gce-proxy should have mysql/postgres clients
2) I can be able to pass SQL instance connection details as en vars
3) I can be able to pass shell commands  with e.g. `psql ..`

**Comment by Philmod** [comment]
Hey @rimusz, 
After a long reflection, we decided not to transfer the [existing builder](gcr.io/cloudsql-docker/gce-proxy) from where it is the most appropriately hosted.
If you need more the builder to have more features, I recommend you fork it or use it as a base image in a new builder.
