### ISSUE TITLE
Install libc6-compat in the alpine-based Java build steps

### ISSUE THREAD

**Issue by aslo** [GoogleCloudPlatform/cloud-builders#94]
This library is required by gRPC. We'll save users a lot of time by just installing it ourselves.

**Comment by skelterjohn** [comment]
Is gRPC used from *within* a build step, or would it be used in the image created by a build?

**Comment by aslo** [comment]
It would be within in the build step itself. I'll see if I can come up with a good example application where this would be necessary.

**Comment by svachmic** [comment]
Hi! What is the outcome of this  issue - is the recommended way to go to just use the non-alpine image? We used in our Spring-Boot app `openjdk:8-jre-alpine` but after having to implement Pub/Sub (gRPC), we had to fix the issue with missing `libc6-compat`. Now we're using `openjdk:8-jre` but the image size has almost doubled. I am not exactly a specialist on `libc6-compat` size, but aren't we now shipping our app with "too much stuff"? Thanks!
