### ISSUE TITLE
[BUG] `/gke-deploy: No such file or directory`

### ISSUE THREAD

**Issue by ffissore** [GoogleCloudPlatform/cloud-builders#995]
## Affected builder image

`gcr.io/cloud-builders/gke-deploy`

## Additional Info

PR #994 changed the path where to find `gke-deploy` from `/gke-deploy` to `/bin/gke-deploy`: this broke all our cloudbuild pipelines

**Comment by terrynguyen255** [comment]
This still occurs @haroonc 
Could you have a look?

```
- id: Deploy service to GKE
  name: "gcr.io/cloud-builders/gke-deploy"
  entrypoint: 'bash'
  args:
    - '-c'
    - |-
        bash -c  /gke-deploy apply \
        --filename=my-path/service.yaml \
        --cluster=my-cluster \
        --project=my-project --location=us-east1 \
        --timeout=60m
```
> Already have image (with digest): gcr.io/cloud-builders/gke-deploy
bash: line 2: /gke-deploy: No such file or directory

**Comment by haroonc** [comment]
Looking into this, I will update here once change is live in Cloud Build, thanks for your patience.
